### ISSUE TITLE
怎么在自己的 ChatGPT-Next-Web 站点中使用这个服务

### ISSUE THREAD

**Issue by sun0225SUN** [aaamoon/copilot-gpt4-service#1]
好像只能在大佬的 http://gpt4copilot.tech 内部使用，但是我看您仓库里面也只改了一些配置文件，没研究明白

**Comment by aaamoon** [comment]
是不是因为你的站点是https，我的那个后端服务是http的原因，其实你可以自己部署本仓库的后端服务

**Comment by ottocsb** [comment]
> 是不是因为你的站点是https，我的那个后端服务是http的原因，其实你可以自己部署本仓库的后端服务

打包个docker镜像吧，没写过go，不会部署go

**Comment by aaamoon** [comment]
好的，我研究下怎么打包docker，还没学过。。。

**Comment by aaamoon** [comment]
@sun0225SUN @ottocsb 有大佬提了个PR过来，已经支持docker部署了
