### ISSUE TITLE
"Stream" field should be false as default

### ISSUE THREAD

**Issue by Geniucker** [aaamoon/copilot-gpt4-service#10]
Other wise some translators can't work properly.

**Comment by aaamoon** [comment]
这个服务端主要是服务于ChatGPT-Next-Web这种客户端场景的，如果设置为false的话，需要等OpenAI全部流式数据返回后才能返回给客户端，这样客户端显示内容的时间会很长；具体是哪些场景需要默认设置为false呢？

**Comment by wouiSB** [comment]
主要是false是openai 的默认行为
我刚看了一下，ChatGPT-Next-Web发请求的时候自己就带了stream: true，所以不会有问题
我用的一个浏览器插件 沉浸式翻译 只支持stream: false的返回格式，但是他发请求的时候不会带stream字段

**Comment by Geniucker** [comment]
主要是false是openai 的默认行为
我刚看了一下，ChatGPT-Next-Web发请求的时候自己就带了stream: true，所以不会有问题
我用的一个浏览器插件 沉浸式翻译 只支持stream: false的返回格式，但是他发请求的时候不会带stream字段
