### ISSUE TITLE
建议把项目迁移到Gitlab或者Bitbucket之类的平台

### ISSUE THREAD

**Issue by D3-3109** [aaamoon/copilot-gpt4-service#101]
因为众所周知的原因，这种项目很有可能被Github官方判定为滥用&违反TOS，招致封仓甚至封号之类的制裁(因为有zhile的先例了)。
同时也是为了控制传播范围，建议开发者考虑把该项目迁移到Gitlab或者其他托管平台。

**Comment by ottocsb** [comment]
确实，我投gitlab一票

**Comment by aaamoon** [comment]
感谢提醒，已经备份到gitlab，https://gitlab.com/aaamoon/copilot-gpt4-service
