### ISSUE TITLE
有计划支持直接源码调用或者命令行工具么

### ISSUE THREAD

**Issue by wzshiming** [aaamoon/copilot-gpt4-service#102]
**Are there certain things to report that are not a bug or feature?**
Please tell us as exactly as possible about your request, thanks.
We will reply as soon as possible.

在有些场景如果提供的话会比较方便

**Comment by aaamoon** [comment]
自行部署后，命令行工具调用：
```
curl --location 'http://localhost:8080/v1/chat/completions' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer ghu_xx' \
--data '{
  "model": "gpt-4",
  "messages": [ {"role": "user", "content": "hello"}]
}'
```

**Comment by wzshiming** [comment]
这个我会用的, 我其实就是想在 命令行使用 不打算启服务

**Comment by aaamoon** [comment]
公共服务有可能会对Github Copilot账号造成风险，所以没有弄公共服务，推荐自己部署服务使用

**Comment by wzshiming** [comment]
不是公共服务, 就本地命令行

**Comment by wzshiming** [comment]
我看了下代码, 感觉就两个接口的事, 我打算自己封装一下

**Comment by wzshiming** [comment]
https://github.com/wzshiming/gh-gpt

参考了一下接口的逻辑然后给重写了一波, 自用

**Comment by wzshiming** [comment]
总体来说非常感谢这个项目提供了这点子, 为啥我没想到呢, 溜了溜了
