### ISSUE TITLE
文档中存在可能的表述错误

### ISSUE THREAD

**Issue by immelon0097** [aaamoon/copilot-gpt4-service#104]
“不建议方式”的第一条内容为
> 以公共服务的方式提供接口 多个 Token 在同一个 IP 地址进行请求, 容易被判定为异常行为

对应 README_EN.md 中为
> Providing an interface as a public service Making multiple token requests from the same IP address can be flagged as abnormal behavior.

按照常识来理解，这条建议应当为：
"以公共服务的方式提供接口。**同一个 Token 在多个 IP 地址**进行请求，容易被判定为异常行为"。

对应的英文为：
"Provide interfaces in the form of public services. A single token making requests from multiple IP addresses can easily be deemed as suspicious behavior."（来自 GPT4）

**Comment by aaamoon** [comment]
感谢提醒，可以直接提PR吗，文档中其他有问题的地方也可以直接改正过来
