### ISSUE TITLE
获取token的另一种可能方式

### ISSUE THREAD

**Issue by Giter-t** [aaamoon/copilot-gpt4-service#105]
在Visual Studio中使用Github Copilot扩展，会在%USERPROFILE%/AppData/Local下生成一个github-copilot文件夹，该文件夹中的hosts.json文件中的oauth_token即是Github Copilot Plugin Token。(不知道现在还可不可以这样获取)

**Comment by aaamoon** [comment]
应该是在IDEA安装Github Copilot扩展后才会有这个文件吧，目前已经有这种获取方式：
https://github.com/aaamoon/copilot-gpt4-service/blob/master/shells/get_copilot_token.sh#L16

**Comment by Giter-t** [comment]
> 应该是在IDEA安装Github Copilot扩展后才会有这个文件吧，目前已经有这种获取方式： https://github.com/aaamoon/copilot-gpt4-service/blob/master/shells/get_copilot_token.sh#L16

并不是，是在windows上安装VS的Github Copilot扩展后有的文件

**Comment by DullJZ** [comment]
经过实践确实可行

**Comment by xiongpahao** [comment]
如果是只安装了VSCode的Copilot扩展，有没有可能获取到token呢？我找了半天也没找到

**Comment by aaamoon** [comment]
@xiongpahao 我试过mac获取不到，windows就不清楚了

**Comment by DullJZ** [comment]
Windows系统安装了VS2022，VSCode，Pycharm的copilot扩展，暂时不清楚是哪个ide生成的发自我的 iPhone在 2024年1月11日，12:17，exia ***@***.***> 写道：﻿
@xiongpahao 我试过mac获取不到，windows就不清楚了

**Comment by Giter-t** [comment]
经过测试就是VS生成的，windows 上使用VS安装Github Copilot扩展并授权后会自动生成

**Comment by two-tigger** [comment]
现在我的还是无法生成，不知道什么原因

**Comment by two-tigger** [comment]
> github-copilot

我的并没有生成这个文件，现在这个方法还有效吗？
