### ISSUE TITLE
要如何配置GP4模型？

### ISSUE THREAD

**Issue by jimzk** [aaamoon/copilot-gpt4-service#110]
我的配置

<img width="865" alt="image" src="https://github.com/aaamoon/copilot-gpt4-service/assets/10106636/4b526916-4448-4154-8de2-e1b194930b00">

但回答还是GPT3的

<img width="887" alt="image" src="https://github.com/aaamoon/copilot-gpt4-service/assets/10106636/c2e185fa-e0e5-4c76-b43b-2370e163066f">

请问应该如何配置模型？

**Comment by aaamoon** [comment]
可能是因为你新建聊天的时候，还没有设置成GPT-4模型，当前聊天模型优先级高于全局设置模型

**Comment by jimzk** [comment]
感谢回复。但我确认过了，开始问答前的配置是GPT-4

<img width="896" alt="image" src="https://github.com/aaamoon/copilot-gpt4-service/assets/10106636/6dfd8477-c449-4eb3-a36b-772e41eaa9c8">

<img width="904" alt="image" src="https://github.com/aaamoon/copilot-gpt4-service/assets/10106636/b881d8bc-4c85-4c60-a7a8-691c19ed5611">

是不是模型名字的问题？有大小写么？

我的Token是通过[README上提供的脚本获取的](https://github.com/aaamoon/copilot-gpt4-service#%E9%80%9A%E8%BF%87-github-copilot-cli-%E6%8E%88%E6%9D%83%E8%8E%B7%E5%8F%96)。

**Comment by aaamoon** [comment]
区分大小写的，如果是GPT-4，传给服务端的model名是  model: "gpt-4"

**Comment by jimzk** [comment]
我把model名改成小写的gpt-4，model列表下就没有选项了

<img width="276" alt="image" src="https://github.com/aaamoon/copilot-gpt4-service/assets/10106636/ffa76226-e2f9-4659-8df4-e842debc5941">

请问你那边正确的gpt4配置是怎么样的？

**Comment by codieh** [comment]
> 我把model名改成小写的gpt-4，model列表下就没有选项了
> 
> <img alt="image" width="276" src="https://private-user-images.githubusercontent.com/10106636/295499815-ffa76226-e2f9-4659-8df4-e842debc5941.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NzgzMjEsIm5iZiI6MTcwNDg3ODAyMSwicGF0aCI6Ii8xMDEwNjYzNi8yOTU0OTk4MTUtZmZhNzYyMjYtZTJmOS00NjU5LThkZjQtZTg0MmRlYmM1OTQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA5MTM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlN2E1MzIzMjkxNjQ5MDdmZGQzMTUyYjVhMWJiNWI5YTk1NGQ0YWVhNzUzMjk3YzdlNTJiYzhkYjg4ZTUxMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s7PGOddwnOR3CLYtrGdx_2Xfh6zE1m3IV7ryLbCqyrU">
> 请问你那边正确的gpt4配置是怎么样的？

我也遇到了这个问题。或许是网站的问题，将NextChat换成本地部署的方式来使用就可以了
