### ISSUE TITLE
单文件nodejs版本

### ISSUE THREAD

**Issue by gcgcnfvd** [aaamoon/copilot-gpt4-service#111]
### Description

https://gist.github.com/gcgcnfvd/49acec97b08c66ce823efb08d99004a0

感谢 @aaamoon 大佬提供的go版本
参照大佬逻辑写了个nodejs版本， 不敢开仓库，害怕被封号 🤒  偷偷小号分享一波

### Why

share

### Alternatives

share

**Comment by youxiaohou** [comment]
你这不支持流返回吧

**Comment by gcgcnfvd** [comment]
> ### Description
> https://gist.github.com/gcgcnfvd/49acec97b08c66ce823efb08d99004a0
> 
> 感谢 @aaamoon 大佬提供的go版本 参照大佬逻辑写了个nodejs版本， 不敢开仓库，害怕被封号 🤒 偷偷小号分享一波
> 
> ### Why
> share
> 
> ### Alternatives
> share

@youxiaohou 

支持的， 
```diff
curl -i -X POST
-H "Content-Type:application/json"
-d
'{
"model": "gpt-4",
+++"stream": true,
"messages": [ {"role": "user", "content": "hello"}]
}'
'http://localhost:7177/v1/chat/completions'
```

这js版代码是把大佬的代码丢个GPT，让它给我重写成js的而已。跑一下，fix几个小问题，几分钟搞定 😮

**Comment by huaerss** [comment]
@gcgcnfvd  使用ChatGPT-Next-Web 配合node 后端 好像不是流响应
