### ISSUE TITLE
一键部署方式，可以用非8080端口吗

### ISSUE THREAD

**Issue by aiesst** [aaamoon/copilot-gpt4-service#112]
### Description

一键部署方式，可以用非8080端口吗，比如修改命令为8081

docker run -d \
  --name copilot-gpt4-service \
  --restart always \
  -p 8081:8081 \
  -e HOST=0.0.0.0 \
  aaamoon/copilot-gpt4-service:latest

**Comment by syx-413** [comment]
```docker
docker run -d
--name copilot-gpt4-service
--restart always
-p 8081:8080
-e HOST=0.0.0.0
aaamoon/copilot-gpt4-service:latest
```

**Comment by dw763j** [comment]
授人以渔：

-p  可指定主机IP:主机端口:docker内端口

如：

-p 127.0.0.1:9999:8080

表示在本地主机127.0.0.1的9999端口开放服务，可保障外界无法直接访问本服务（不使用-e HOST情况下），有利于增强控制性。
