### ISSUE TITLE
Failed to get authorization from token

### ISSUE THREAD

**Issue by JustinGuese** [aaamoon/copilot-gpt4-service#116]
### Description

nice work, I don't get it though...
set it up with docker, the next-web seems to communicate with the service according to logs, but the next-web ui just says "{
  "error": "Failed to get authorization from token"
}

service logs:

```
2024-01-10T13:11:09.683294244Z [OpenAI Route] params { path: [ 'v1', 'chat', 'completions' ] } 
2024-01-10T13:11:09.683347609Z [Server Config] using 1 of 1 api key 
2024-01-10T13:11:09.683355302Z [Auth] allowed hashed codes: [] 
2024-01-10T13:11:09.683361794Z [Auth] got access code:  
2024-01-10T13:11:09.683368544Z [Auth] hashed access code: xxxxxxxxxxxxxx 
2024-01-10T13:11:09.683375854Z [User IP] 188.174.216.159 
2024-01-10T13:11:09.683382079Z [Time] 1/10/2024, 1:11:09 PM 
2024-01-10T13:11:09.683388307Z [Auth] use user api key 
2024-01-10T13:11:09.683394363Z [Proxy] v1/chat/completions?path=v1&path=chat&path=completions 
2024-01-10T13:11:09.683401334Z [Base Url] http://copilot-service:8080

```

**Comment by JustinGuese** [comment]
if it helps I tried debugging the copilot-service with this python code:
```
from openai import OpenAI

client = OpenAI(
    base_url="http://localhost:8080",
    api_key="THE_COPILOT_CLI_API_KEY",
)


chat_completion = client.chat.completions.create(
    messages=[
        {"role": "user", "content": "tell me a funny joke about python programmers"},
    ],
    model="gpt-3.5-turbo",
)

print(chat_completion.choices[0].message.content)
```

which throws a 405 "method not allowed" error

Exception has occurred: APIStatusError
Method Not Allowed
httpx.HTTPStatusError: Client error '405 Method Not Allowed' for url 'http://localhost:8080/chat/completions'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405

During handling of the above exception, another exception occurred:

  File "/Users/jguese/code/tradingbot22-tradingbots-prefect/flows/gpttest.py", line 10, in <module>
    chat_completion = client.chat.completions.create(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openai.APIStatusError: Method Not Allowed

**Comment by aaamoon** [comment]
> me too

There are two scenarios that can cause this error. The first is that the token is wrong or expired, please get it again, and the second is that the GitHub account you are using does not have the Copilot permission

**Comment by aaamoon** [comment]
> if it helps I tried debugging the copilot-service with this python code:
> 
> ```
> from openai import OpenAI
> 
> client = OpenAI(
>     base_url="http://localhost:8080",
>     api_key="THE_COPILOT_CLI_API_KEY",
> )
> 
> 
> chat_completion = client.chat.completions.create(
>     messages=[
>         {"role": "user", "content": "tell me a funny joke about python programmers"},
>     ],
>     model="gpt-3.5-turbo",
> )
> 
> print(chat_completion.choices[0].message.content)
> ```
> 
> which throws a 405 "method not allowed" error
> 
> Exception has occurred: APIStatusError Method Not Allowed httpx.HTTPStatusError: Client error '405 Method Not Allowed' for url 'http://localhost:8080/chat/completions' For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405
> 
> During handling of the above exception, another exception occurred:
> 
> File "/Users/jguese/code/tradingbot22-tradingbots-prefect/flows/gpttest.py", line 10, in chat_completion = client.chat.completions.create( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ openai.APIStatusError: Method Not Allowed

The url is /v1/chat/completions

**Comment by JustinGuese** [comment]
retrying with 
client = OpenAI(
    base_url="http://localhost:8080/v1",

removes the 405 error, but gives me the same "Error code: 500 - {'error': 'Failed to get authorization from token'}"

**Comment by JustinGuese** [comment]
@aaamoon , do I need copilot permissions (have) or also the copilot *CLI* permissions (don't have)

**Comment by JustinGuese** [comment]
@aaamoon I found the problem! I had to authenticate the SERVER on which it was running, not my client! this is an awesome tool!
will delete the thread though bc of not getting blocked ;)
