### ISSUE TITLE
docker布署后报错

### ISSUE THREAD

**Issue by fatmonkey0923** [aaamoon/copilot-gpt4-service#117]
{
  "error": true,
  "message": "Failed to fetch"
}

![image](https://github.com/aaamoon/copilot-gpt4-service/assets/76645764/be91b9c5-51bc-4667-af3f-c11fe855ec26)

按说明配置服务运行也正常，但是无论说什么，回复都是如上的错误。

**Comment by aaamoon** [comment]
试一下命令行调用有没有返回
```
curl --location 'http://localhost:8080/v1/chat/completions' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer ghu_xx' \
--data '{
  "model": "gpt-4",
  "messages": [ {"role": "user", "content": "hello"}]
}'
```

**Comment by vandovsky** [comment]
i got the same problem there , but when i used curl its returned normal

`{"object": "chat.completion", "model": "gpt-4", "choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"finish_reason":"stop","index":0,"message":{"content":"Hello! How can I assist you today?","role":"assistant"}}],"created":1704926363,"id":"chatcmpl-8fbWFpmgbcl0153YmCqGfeNM2zeRM","prompt_filter_results":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"prompt_index":0}],"usage":{"completion_tokens":9,"prompt_tokens":8,"total_tokens":17}}`

**Comment by xiongpahao** [comment]
多半是你token复制错了，第一次生成的token前面有一段字符是多余的，重新运行一下获取token那段命令，它会给你纯净的token

**Comment by li1679829296** [comment]
是因为接口配置的有问题，地址不能用127.0.0.1，用机器的IP地址试试

**Comment by lxzcpro** [comment]
> 试一下命令行调用有没有返回
> 
> ```
> curl --location 'http://localhost:8080/v1/chat/completions' \
> --header 'Content-Type: application/json' \
> --header 'Authorization: Bearer ghu_xx' \
> --data '{
>   "model": "gpt-4",
>   "messages": [ {"role": "user", "content": "hello"}]
> }'
> ```

我在自己的服务器上部署遇到了同样的问题，返回为{"error":"Failed to get authorization from token"}

**Comment by aaamoon** [comment]
@lxzcpro 用最新的镜像试试

**Comment by Thewhitelight** [comment]
> > 试一下命令行调用有没有返回
> > ```
> > curl --location 'http://localhost:8080/v1/chat/completions' \
> > --header 'Content-Type: application/json' \
> > --header 'Authorization: Bearer ghu_xx' \
> > --data '{
> >   "model": "gpt-4",
> >   "messages": [ {"role": "user", "content": "hello"}]
> > }'
> > ```
> 
> 我在自己的服务器上部署遇到了同样的问题，返回为{"error":"Failed to get authorization from token"}

试试用host网络模式部署docker，我也是在服务器上部署遇到这个问题。通过host模式就正常访问网络了

**Comment by macongcong001** [comment]
我的是直接没有返回数据 或者是返回了空数据

**Comment by li1679829296** [comment]
> 我直接是没有返回数据或者是返回了空数据

你的【 ChatGPT-Next-Web】也是用docker部署的是吧？
这个问题可能是因为【ChatGPT-Next-Web】没有连接到【copilot-gpt4-service】的服务。
看你提供的截图，连接【copilot-gpt4-service】的服务的ip地址，你填写的是  127.0.0.1
然而127.0.0.1 是【ChatGPT-Next-Web】容器内的本地ip，不是宿主机的。
你需要填写宿主机的ip地址，才能访问到【copilot-gpt4-service】的服务。

不知道我有没有表达清楚，当然你也可能不是这个问题。
