### ISSUE TITLE
Translate to Portuguese (Brazil)

### ISSUE THREAD

**Issue by felipebossolani** [aaamoon/copilot-gpt4-service#120]
### Description

Can you translate this into English? I am from Brazil, a third-world country, with limited access to the English language. Based on this, I would like to suggest translating the README into pt-BR. I can do that.

### Why

Democratize access to the tool!

### Alternatives

N/A

**Comment by aaamoon** [comment]
We are very sorry that maintaining an extra document is very stressful for our later maintenance, at present we only consider maintaining Chinese and English documents, if others need it, it is recommended that they can use a translation tool to translate and read the document.
