### ISSUE TITLE
聊天回复的内容是空

### ISSUE THREAD

**Issue by ZhangPeng-Bobby** [aaamoon/copilot-gpt4-service#123]
使用docker部署好，下载了charBox设置完毕，发送聊天没有报错，但是也没有回复。docker日志也没线索。
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/24525068/8e1fba32-cb20-4899-ac6a-d1b20057f35b)
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/24525068/de5476c1-5863-472a-8771-fc037a4524df)
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/24525068/2b1e161c-7b58-46ba-a6ba-04bed019ba2b)

**Comment by aaamoon** [comment]
试下curl有没有返回
```
curl --location 'http://localhost:8080/v1/chat/completions' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer ghu_xx' \
--data '{
  "model": "gpt-4",
  "messages": [ {"role": "user", "content": "hello"}]
}'
```

**Comment by ZhangPeng-Bobby** [comment]
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/24525068/8f297be5-1c2d-4a8b-bd70-5478f3de885d)

执行完确实啥也没有

**Comment by aaamoon** [comment]
你确定服务有跑起来吗，就算是随便填个token起码也有个报错返回
<img width="573" alt="image" src="https://github.com/aaamoon/copilot-gpt4-service/assets/25700476/157e5e4c-1111-4383-b73b-32e51e94cfdf">

**Comment by ZhangPeng-Bobby** [comment]
瞎填一个token是有返回的
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/24525068/dc66e7ef-6ee7-41e5-9b44-2d0e270818e4)

**Comment by aaamoon** [comment]
看起来你本地向Github请求是没问题的，但是Github向OpenAI那边请求接口没响应，感觉像是超时了

**Comment by ZhangPeng-Bobby** [comment]
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/24525068/0cb91a32-4b7f-401d-b97a-4ac39c454d99)
每次的成功返回延迟确实比较高

**Comment by zhh210** [comment]
遇到一样的问题，有推荐的解决办法吗

**Comment by ZhangPeng-Bobby** [comment]
> Referen

我的mac mini 和 mac book都是这个现象。。Windows还没试

**Comment by zhh210** [comment]
有可能是这个原因：仔细看了下我的github copilot page, 只有`GitHub Copilot in the CLI`状态显示是Enabled。`Copilot Chat in the IDE` 和 `Copilot Chat in github.com` 显示都是`Disabled`. GitHub特么继承了微软的尿性一样坑啊...
