### ISSUE TITLE
似乎是支持其他模型调用的，甚至函数调用

### ISSUE THREAD

**Issue by Justin3go** [aaamoon/copilot-gpt4-service#125]
文档中写道：
> 模型支持情况
> 据测试：模型参数支持 GPT-4 和 GPT-3.5-turbo ，实测使用其他模型均会以默认的 3.5 处理（对比 OpenAI API 的返回结果，猜测应该是最早的版本 GPT-4-0314 和 GPT-3.5-turbo-0301 ）

但据我测试，几乎支持所有模型的调用，截图如下：

![LobeChat_随便聊聊_2024-01-11](https://github.com/aaamoon/copilot-gpt4-service/assets/63507251/0c18abc0-0c71-4fa2-a446-18a5e62e08a3)

我使用的是[LobeChat](https://github.com/lobehub/lobe-chat)这个客户端，值得注意的是，需要在proxyUrl中加上`v1`后缀才能生效，并且不支持本地localhost的方式以及需要https

**Comment by Steve0x2a** [comment]
这个需要https是客户端的限制么？

**Comment by Justin3go** [comment]
> 这个需要https是客户端的限制么？

应该是vercel的限制

**Comment by Justin3go** [comment]
上面的尝试可能有误，这个iusse关闭

**Comment by xiongpahao** [comment]
LobeChat可以用Docker部署在本地的，我就是这么干的。而且我发现无论是NextChat还是LobeChat都可以随意切换模型
![Screenshot 2024-01-11 at 15 01 28](https://github.com/aaamoon/copilot-gpt4-service/assets/12950426/00fa1bda-dd68-48ca-927d-4d33eebdcedd)
![Screenshot 2024-01-11 at 15 04 55](https://github.com/aaamoon/copilot-gpt4-service/assets/12950426/2f85c5bf-acf5-4072-981b-dccca4382fae)

**Comment by xiongpahao** [comment]
> LobeChat可以用Docker部署在本地的，我就是这么干的。而且我发现无论是NextChat还是LobeChat都可以随意切换模型 ![Screenshot 2024-01-11 at 15 01 28](https://private-user-images.githubusercontent.com/12950426/295819549-00fa1bda-dd68-48ca-927d-4d33eebdcedd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NTcwMjgsIm5iZiI6MTcwNDk1NjcyOCwicGF0aCI6Ii8xMjk1MDQyNi8yOTU4MTk1NDktMDBmYTFiZGEtZGQ2OC00OGNhLTkyN2QtNGQzM2VlYmRjZWRkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDA3MDUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxYzliMWMyY2ZkNjIxZmJjMzQwMThmMWM4Njk0NjY0MmY4YjcwYzEyYTdmYTA4MGVmNTNiMDVjYTc0ZjNmYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BHTfZuRZZN4DUy3pf1fwDyWAtuKU49HEB-5r7RYtZSc) ![Screenshot 2024-01-11 at 15 04 55](https://private-user-images.githubusercontent.com/12950426/295819582-2f85c5bf-acf5-4072-981b-dccca4382fae.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NTcwMjgsIm5iZiI6MTcwNDk1NjcyOCwicGF0aCI6Ii8xMjk1MDQyNi8yOTU4MTk1ODItMmY4NWM1YmYtYWNmNS00MDcyLTk4MWItZGNjY2E0MzgyZmFlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDA3MDUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4OTk2YmQ5YWUzMmI0NmNhZjg0ZmQ2YTcyZTRlNDU0YjBlN2IyZDFlZmU1OWNhNWRmYTc1Yzk3NjY3NzM4MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-KdEH4fne75UTVLoE9M2RughC0YbavJ1TtiqiYWqkXI)

好吧，LobeChat切换模型好像经常失效……不知道为啥
