### ISSUE TITLE
Cloudflare worker 方式响应内容为空

### ISSUE THREAD

**Issue by harisonkhlil** [aaamoon/copilot-gpt4-service#131]
### Description

使用环境：
客户端：部署在 vercel 服务上的 nextGPT web
服务端：部署在 Cloudflare 上的 worker 服务
使用模型： gpt-4

响应内容：空响应

本地部署的 127.0.0.1:8080 没有问题

**Comment by aaamoon** [comment]
服务端部署使用 Cloudflare worker 会有封号风险，不建议使用，详见：
https://github.com/aaamoon/copilot-gpt4-service/blob/master/README_CN.md#%E4%B8%8D%E5%BB%BA%E8%AE%AE%E6%96%B9%E5%BC%8F
