### ISSUE TITLE
电脑上部署后，手机怎么用这个api（纯小白）

### ISSUE THREAD

**Issue by SuperrNaruto** [aaamoon/copilot-gpt4-service#133]

**Comment by Steve0x2a** [comment]
可以使用类似chatx这类客户端，配置自定义的api地址。但需要手机能连上电脑的服务。

**Comment by SuperrNaruto** [comment]
手机怎么脸上电脑的服务呢> 可以使用类似chatx这类客户端，配置自定义的api地址。但需要手机能连上电脑的服务。

**Comment by InternetBugs** [comment]
> 手机怎么脸上电脑的服务呢> 可以使用类似chatx这类客户端，配置自定义的api地址。但需要手机能连上电脑的服务。

位于同一个局域网内，直接用内网ip连接
