### ISSUE TITLE
Linux/MacOS平台获取Copilot Token报错

### ISSUE THREAD

**Issue by Payne-Wang** [aaamoon/copilot-gpt4-service#136]
### Description

运行的是这个代码：bash -c "$(curl -fsSL https://raw.githubusercontent.com/aaamoon/copilot-gpt4-service/master/shells/get_copilot_token.sh)"

![image](https://github.com/aaamoon/copilot-gpt4-service/assets/44337721/c569d022-3985-4904-8cc8-2b7483693d52)

**Comment by robscc** [comment]
同遇到问题

**Comment by Payne-Wang** [comment]
> > 同样的问题，完整的报错内容：
> > ```
> > Github Copilot CLI token not found. Please authorize.
> > /usr/local/lib/node_modules/@githubnext/github-copilot-cli/dist/index.js:31
> > `,E.label=1;case 1:return E.trys.push([1,3,,4]),[4,CT.confirmDirExists(this._tempDir)];case 2:return E.sent(),[3,4];case 3:return o=E.sent(),console.log(this.TAG,"Failed to create directory for log file: "+(o&&o.message)),[2];case 4:return E.trys.push([4,6,,11]),[4,CT.accessAsync(this._fileFullPath,OQe.constants.F_OK)];case 5:return E.sent(),[3,11];case 6:s=E.sent(),E.label=7;case 7:return E.trys.push([7,9,,10]),[4,CT.appendFileAsync(this._fileFullPath,r)];case 8:return E.sent(),[2];case 9:return n=E.sent(),console.log(this.TAG,"Failed to put log into file: "+(s&&s.message)),[2];case 10:return[3,11];case 11:return E.trys.push([11,17,,18]),[4,CT.getShallowFileSize(this._fileFullPath)];case 12:return c=E.sent(),c>this.maxSizeBytes?[4,this._createBackupFile(r)]:[3,14];case 13:return E.sent(),[3,16];case 14:return[4,CT.appendFileAsync(this._fileFullPath,r)];case 15:E.sent(),E.label=16;case 16:return[3,18];case 17:return m=E.sent(),conso
> > 
> > SyntaxError: Unexpected token .
> >     at Module._compile (internal/modules/cjs/loader.js:723:23)
> >     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
> >     at Module.load (internal/modules/cjs/loader.js:653:32)
> >     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
> >     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
> >     at Module.require (internal/modules/cjs/loader.js:692:17)
> >     at require (internal/modules/cjs/helpers.js:25:18)
> >     at Object.<anonymous> (/usr/local/lib/node_modules/@githubnext/github-copilot-cli/cli.js:2:1)
> >     at Module._compile (internal/modules/cjs/loader.js:778:30)
> >     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
> > \033[0;31mGithub Copilot CLI token not found. Please try again.\033[0m
> > ```
> 
> 经测试是nodejs版本的问题，升级到20后问题解决

确实如此，将node.js升级到20后解决啦， 感谢大佬！问题我关了
