### ISSUE TITLE
使用 最新代码 Code Build 的时候，请求  返回的数据是这个 ，大佬能看下是哪里错了吗

### ISSUE THREAD

**Issue by tomridder** [aaamoon/copilot-gpt4-service#137]
{"object": "chat.completion.chunk", "model": "gpt-4", "choices":[],"created":0,"id":"","prompt_filter_results":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"prompt_index":0}]}

下面是 部署成功后的截图

<img width="1178" alt="image" src="https://github.com/aaamoon/copilot-gpt4-service/assets/13205117/61555fbe-f263-4f03-99f7-987216f6a2c1">

<img width="798" alt="image" src="https://github.com/aaamoon/copilot-gpt4-service/assets/13205117/34c5be4e-acf8-4dae-90b2-41a28aafb81d">

token 和 应该都是没问题的

**Comment by aaamoon** [comment]
/v1/chat/completions是post方法，url那里访问相当于get

**Comment by tomridder** [comment]
> /v1/chat/completions是post方法，url那里访问相当于get

截图只是为了说明 我们部署成功了 ，问题是返回的日志不对

**Comment by tomridder** [comment]
{"object": "chat.completion.chunk", "model": "gpt-4", "choices":[],"created":0,"id":"","prompt_filter_results":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"prompt_index":0}]}

**Comment by aaamoon** [comment]
试下curl请求下看返回什么
