### ISSUE TITLE
两个问题的回答都在胡说八道，模型是GPT4，什么情况？

### ISSUE THREAD

**Issue by davidxiao** [aaamoon/copilot-gpt4-service#138]
![Screen Shot 2024-01-11 at 20 54 52](https://github.com/aaamoon/copilot-gpt4-service/assets/4176280/ce074547-1eb8-4eff-8c74-b388e4cc27f2)
![Screen Shot 2024-01-11 at 20 56 19](https://github.com/aaamoon/copilot-gpt4-service/assets/4176280/04032ede-f1ab-44dc-beff-91c81cd54f65)
![Screen Shot 2024-01-11 at 20 56 39](https://github.com/aaamoon/copilot-gpt4-service/assets/4176280/ad149ed8-797b-4629-a130-67c992453daf)

**Comment by davidxiao** [comment]
试了GPT-4-0314，也一样

**Comment by aaamoon** [comment]
只支持gpt-4，不支持gpt-4-32k、gpt-4-0314等

**Comment by davidxiao** [comment]
是我搞错了，我用的不是latest的docker image，用latest image就好了，
非常感谢，
@aaamoon
