### ISSUE TITLE
大佬吗code 403怎么办啊

### ISSUE THREAD

**Issue by summer-pursuit** [aaamoon/copilot-gpt4-service#142]
{
  "code": 403,
  "error": "{\"error_details\":{\"url\":\"https://github.com/github-copilot/signup?editor={EDITOR}\",\"message\":\"No access to GitHub Copilot found. You are currently logged in as summer-pursuit.\",\"title\":\"Signup for GitHub Copilot\",\"notification_id\":\"no_copilot_access\"},\"message\":\"Resource not accessible by integration\"}"
}
报错信息，但是我已经开通账号，有token了还是报错，该怎么办

**Comment by aaamoon** [comment]
你没有开通Github Copilot吧
