### ISSUE TITLE
  "error": "Failed to get authorization from token"

### ISSUE THREAD

**Issue by shawyb** [aaamoon/copilot-gpt4-service#143]
### Description

![屏幕截图 2024-01-11 211640](https://github.com/aaamoon/copilot-gpt4-service/assets/32785966/eaa43653-d171-4040-90d8-63de28c200df)

**Comment by shawyb** [comment]
按照md获取的token，怎么报错了，咋回事呢

**Comment by aaamoon** [comment]
试一下最新版的镜像

**Comment by shawyb** [comment]
> 试一下最新版的镜像

![image](https://github.com/aaamoon/copilot-gpt4-service/assets/32785966/afd25e37-6cfe-4581-ae9d-5a85358c184f)
这个吗，我昨天下的latest

**Comment by aaamoon** [comment]
是的，d1179那个，是今天发布的，优化了一下返回的错误信息更好地排查你那个问题

**Comment by demaxiyasai2** [comment]
希望更新

**Comment by ShenChen1** [comment]
Hi,

I got this issue as well.
{
  "error": "Failed to get authorization from token"
}

And I just had a try on my laptop with `d1179a6`, finally got this log.
{
  "code": 500,
  "error": "Get \"https://api.github.com/copilot_internal/v2/token\": dial tcp *.*.*.*:443: i/o timeout"
}

**Comment by aaamoon** [comment]
@ShenChen1 443: i/o timeout表示你访问不到Github接口，要能翻墙

**Comment by ShenChen1** [comment]
@aaamoon  谢谢回复，配置了proxy以后变成了这样
```
{
  "code": 404,
  "error": "{\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest\"}"
}
```
用的这个命令：
```
docker run -d \
>   --name copilot-gpt4-service \
>   --restart always \
>   -p 8080:8080 \
>   -e HOST=0.0.0.0 \
>   -e http_proxy=http://xxx.xxx.xxx.xxx:8080/ \
>   -e https_proxy=http://xxx.xxx.xxx.xxx:8080/ \
>   aaamoon/copilot-gpt4-service:d1179a6
```

**Comment by aaamoon** [comment]
@ShenChen1 proxy路径有问题，可以先排查下

**Comment by ShenChen1** [comment]
@aaamoon 
重新通过github-copilot-cli生成了token，已经可以了，谢谢！
