### ISSUE TITLE
service unavailable

### ISSUE THREAD

**Issue by Thewhitelight** [aaamoon/copilot-gpt4-service#145]
### Description

```
curl --location 'http://***:3001/v1/chat/completions' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer ghu_xxxx' \
--data '{
  "model": "GPT-4-0314",
  "messages": [ {"role": "user", "content": "hello"}]
}'
```

`{"code":500,"error":"Get \"https://api.github.com/copilot_internal/v2/token\": dial tcp: lookup api.github.com: i/o timeout"}%`

**Comment by lisakhan** [comment]
需要科学上网

**Comment by Thewhitelight** [comment]
> 需要科学上网

curl https://api.github.com/copilot_internal/v2/token
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest"
}

**Comment by lisakhan** [comment]
第一次的错误来看， lookup api.github.com: i/o timeout，就是网络问题，不是dns被污染了，就是无法直接连接
第二次的信息正常
