### ISSUE TITLE
invalid Host header

### ISSUE THREAD

**Issue by Nabeel-javaid** [aaamoon/copilot-gpt4-service#146]
### Description

when trying to build it using

`docker compose up -d` the following issues appears

`http: invalid Host header`

NOTE: Steps i've done 

`git clone https://github.com/aaamoon/copilot-gpt4-service && cd copilot-gpt4-service`

made an .env and placed this in it

```solidity
HOST=localhost # Service listening address
PORT=8080 # Service listening port
CACHE=true # Whether to enable persistence
CACHE_PATH=db/cache.sqlite3 # Path to persistent cache (only used when CACHE=true)
DEBUG=false # Whether to enable debug mode, more logs will be output when enabled
LOGGING=true # Whether to enable logging
LOG_LEVEL=info # Log level, optional values: panic, fatal, error, warn, info, debug, trace (Note: Only effective when LOGGING=true)
```

and tried `docker compose up -d` but the issue appears

**Comment by Geniucker** [comment]
Can you provide a full building log

**Comment by Nabeel-javaid** [comment]
> Can you provide a full building log

![image](https://github.com/aaamoon/copilot-gpt4-service/assets/95472385/ee11a062-05a9-4231-b232-4970f7c806e7)

**Comment by funnyzak** [comment]
> > Can you provide a full building log
> 
> ![image](https://private-user-images.githubusercontent.com/95472385/296223680-ee11a062-05a9-4231-b232-4970f7c806e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNjA5MjAsIm5iZiI6MTcwNTA2MDYyMCwicGF0aCI6Ii85NTQ3MjM4NS8yOTYyMjM2ODAtZWUxMWEwNjItMDVhOS00MjMxLWIyMzItNDk3MGY3YzgwNmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDExNTcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5ZGZhZjRhODhlNjEwZjI1MGUxNTc3YzJmMzk4YTZlM2NmNTU4OWM1MjQ0ZDNhYmNiNmNjNTE0OWU1OTQwNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s9yygBL-WjV2WdUbTKas80lPD9Y_yh6TnzQ4yZUzJdY)

Seems to be a docker problem, please try reinstalling the stable version of docker.

**Comment by Nabeel-javaid** [comment]
> > > Can you provide a full building log
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/95472385/296223680-ee11a062-05a9-4231-b232-4970f7c806e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNjA5MjAsIm5iZiI6MTcwNTA2MDYyMCwicGF0aCI6Ii85NTQ3MjM4NS8yOTYyMjM2ODAtZWUxMWEwNjItMDVhOS00MjMxLWIyMzItNDk3MGY3YzgwNmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDExNTcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5ZGZhZjRhODhlNjEwZjI1MGUxNTc3YzJmMzk4YTZlM2NmNTU4OWM1MjQ0ZDNhYmNiNmNjNTE0OWU1OTQwNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s9yygBL-WjV2WdUbTKas80lPD9Y_yh6TnzQ4yZUzJdY)
> 
> Seems to be a docker problem, please try reinstalling the stable version of docker.

yup! its working now, thanks
