### ISSUE TITLE
iOS 客户端显示的都是GPT3

### ISSUE THREAD

**Issue by sheng-di** [aaamoon/copilot-gpt4-service#149]
无论是 opencat 还是 chatx，无论怎样问，都提示是 3

**Comment by liaozhangsheng** [comment]
人家根本不会告诉你他是几，只能自己测试。具体看readme

**Comment by sheng-di** [comment]
使用 nextchat 一问一个准，可能是他有自己的一些预制的提示词吧。不过看着手机上输出的速度比较慢，应该是4也能通过。文档里说的一些基本的测试。

**Comment by sheng-di** [comment]
不大对，用起来和桌面的 nextchat 感觉不一样，总能感觉出来它是 3

**Comment by aaamoon** [comment]
可以找一些经典问题判断是不是4.0
