### ISSUE TITLE
Bad credentials

### ISSUE THREAD

**Issue by bigdataer01** [aaamoon/copilot-gpt4-service#152]
### Description

hay,I used NextChat as client,then it throw exception like this:
{
  "code": 401,
  "error": "{\"message\":\"Bad credentials\",\"documentation_url\":\"https://docs.github.com/rest\"}"
}

it seems token is error,but i got token from this script :
bash -c "$(curl -fsSL https://raw.githubusercontent.com/aaamoon/copilot-gpt4-service/master/shells/get_copilot_token.sh)"

the generated token for me just like this :\033[0;32mghu_xxxxx\033[0m
may it encoded?
so what should i do,please?

**Comment by aaamoon** [comment]
The token is ghu_xxxxx.

**Comment by bigdataer01** [comment]
> The token is ghu_xxxxx.

it works,thx
