### ISSUE TITLE
How to start copilot-gpt4-service?

### ISSUE THREAD

**Issue by tangze-Asuka** [aaamoon/copilot-gpt4-service#153]
I have a very simple question, that is how to start copilot-gpt4-service, can't it be started in local terminal? Can't it be started from a local terminal, only from Docker?

**Comment by aaamoon** [comment]
https://github.com/aaamoon/copilot-gpt4-service/issues/102#issuecomment-1884292414

**Comment by tangze-Asuka** [comment]
Thank you.
