### ISSUE TITLE
获取copilot token 404

### ISSUE THREAD

**Issue by shenguanjiejie** [aaamoon/copilot-gpt4-service#154]
### Description

无论用不用墙外代理 都是一样404
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/9425605/cec11f95-730e-4ef9-8db9-1900b83b39af)

**Comment by aaamoon** [comment]
你那个url有问题，试下
`bash -c "$(curl -fsSL https://raw.githubusercontent.com/aaamoon/copilot-gpt4-service/master/shells/get_copilot_token.sh)"`

**Comment by shenguanjiejie** [comment]
哦哦 那没有问题了. 我是从pull request里面复制了这条命令, 所以有问题. 我关掉
