### ISSUE TITLE
docker部署时，怎么设置token

### ISSUE THREAD

**Issue by leiguorui** [aaamoon/copilot-gpt4-service#157]
### Description

我在其他电脑使用docker部署，启动时可以设置token吗

### Why

其他电脑部署

### Alternatives

docker启动时设置token

**Comment by aaamoon** [comment]
如果是使用ChatGPTNextWeb的话，可以参考：https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web?tab=readme-ov-file#docker-recommended
