### ISSUE TITLE
[Feature & Question]实测可以选择gpt-4v，但是似乎有bug

### ISSUE THREAD

**Issue by antonis2010** [aaamoon/copilot-gpt4-service#16]
希望作者可以解决默认token数的问题和传入图片url的json相关问题

下图为gpt-4v
![IMG_2377](https://github.com/aaamoon/copilot-gpt4-service/assets/149255073/8ccd71e5-5429-498c-8d0b-a5b92a317b22)

此图为gpt-4
![IMG_2376](https://github.com/aaamoon/copilot-gpt4-service/assets/149255073/0c524a97-0357-44a5-a9a6-fcc21223f27d)

这是gpt-4v的api请求范式
`
curl https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
    "model": "gpt-4-vision-preview",
    "messages": [
      {
        "role": "user",
        "content": [
          {
            "type": "text",
            "text": "What’s in this image?"
          },
          {
            "type": "image_url",
            "image_url": {
              "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg"
            }
          }
        ]
      }
    ],
    "max_tokens": 300
  }'
 `

**Comment by aaamoon** [comment]
据其他大佬测试：模型参数仅支持 GPT-4 和 GPT-3.5-turbo ，实测使用其他模型均会以默认的 3.5 处理（对比 OpenAI API 的返回结果，猜测应该是最早的版本 GPT-4-0314 和 GPT-3.5-turbo-0301 ），所以应该是不支持图片传入的

**Comment by antonis2010** [comment]
实测GPT-4 Turbo可以使用的，知识库显示为2023年4月，而GPT-4 显示为2021年9月
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/149255073/5d19d60d-9f22-4ef1-b630-9bbdfbfa937f)

证明Github并没有禁用任何模型

**Comment by aaamoon** [comment]
GPT-4能回答的问题，在GPT-4-32K和GPT-4-Turbo中都是回答不出来的，这估计只是模型传参误导了它的知识库日期回答，实际上回答质量相当于GPT-3.5

**Comment by antonis2010** [comment]
如果你仔细看图的话，会发现GPT-4 Turbo回答出了二十大的详细信息，足以证明其确实是2023年4月知识库
以下还有两张GPT4和GPT4 Turbo关于北京冬奥会的回答
GPT4
![IMG_2380](https://github.com/aaamoon/copilot-gpt4-service/assets/149255073/9de11ddf-a38b-4c94-b7dc-567bc45277dd)
GPT4 Turbo
![IMG_2381](https://github.com/aaamoon/copilot-gpt4-service/assets/149255073/355282d2-b2b7-4a6e-80ae-c1791dc59c5a)

**Comment by aaamoon** [comment]
哈哈我也不太清楚，希望有开通了ChatGPT plus的朋友帮忙验证一下

**Comment by Geniucker** [comment]
这样能判断gpt-4-turbo和gpt-4-vision-preview用的都是gpt-3.5-turbo
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/61449208/7be29935-307c-453e-abcd-050d231a127b)
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/61449208/8c17fed3-5e67-494e-9522-81adacb71f57)

**Comment by Geniucker** [comment]
我有gpt plus，如果有需要测试的问题可以 at 我具体问题
