### ISSUE TITLE
Add Text Embedding Feature in API Call by Integrating Self-Hosted Endpoint Server

### ISSUE THREAD

**Issue by elohffa** [aaamoon/copilot-gpt4-service#160]
### Description

Currently, our API does not support text embedding, which can limit the functionality and flexibility of our application, especially for functionalities that involves natural language processing or machine learning.

### Why

I propose that we add a text embedding feature to our API calls by integrating a self-hosted endpoint server. This will enable our API to convert input text data into meaningful numerical representations (embeddings) that can be used for further processing, analysis or modeling.

Integrating text embedding in our API will allow us to harness the power of advanced techniques in machine learning and natural language processing. This can significantly improve the capabilities of our application, enabling it to handle complex tasks such as text classification, semantic analysis, and more.

### Alternatives

Modify our current API that accept  openai embed api call in our call  and  then include a new option to relay this url to user self define url ,  This endpoint will accept raw text data, pass them to the self-hosted server for processing, and then return the computed embeddings to the calling client.

**Comment by Geniucker** [comment]
I'll work on it after going back dorm

**Comment by Geniucker** [comment]
Having implemented the python version https://github.com/Geniucker/CoGPT/commit/a387ef5019f753b125a86a820f8f486907a77758, now I'm trying to implement for this repo.

**Comment by Geniucker** [comment]
Can you provider some code so that I can reproduce the problem

**Comment by Geniucker** [comment]
I'm not sure why it can't get cont_type
actually I've set it
<img width="548" alt="image" src="https://github.com/aaamoon/copilot-gpt4-service/assets/61449208/ffa8fe74-d9e8-4b7a-88ca-47d84f1a11ce">

**Comment by Geniucker** [comment]
Seems that copilot doesn't accept number inputs

**Comment by Geniucker** [comment]
Hi, in my test the former one will get 400 Bad Request and the latter one will get normal response. However, both request body works  while using official openai API
I'm not sure how to do with it.
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/61449208/660b3f83-7347-4f78-bc4a-7c260d15042e)
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/61449208/128e0c13-d262-4723-8547-2073ac466663)

**Comment by Geniucker** [comment]
> > Seems that copilot doesn't accept number inputs
> 
> Hi , can u add "model": "text-embedding-ada-002" on response body , because offical openai response have a model thanks
> 
> your repsonse body Response Body: {"data":[{"embedding":[0.0039346158,-0.013658603,0.0010296266,-0.0069053937,6,0.00078510016,-0.00682296,-0.00639811,-0.012701105],"index":0}],"usage":{"prompt_tokens":1,"total_tokens":1}}
> 
> openai response example : { "data": [ { "embedding": [ -0.006929283495992422, -0.005336422007530928, ... -4.547132266452536e-05, -0.024047505110502243 ], "index": 0, "object": "embedding" } ], "model": "text-embedding-ada-002", "object": "list", "usage": { "prompt_tokens": 5, "total_tokens": 5 } }

I'm gonna add it now

**Comment by Geniucker** [comment]
Added in [f519397](https://github.com/aaamoon/copilot-gpt4-service/pull/167/commits/f51939724c6093135bc33aeb56c3563f2553ae64)

**Comment by Geniucker** [comment]
Can you tell which fields will cause problems
And BTW a new issue will be appreciated

**Comment by Geniucker** [comment]
@elohffa feel free to tell where to modify here #213
