### ISSUE TITLE
Instructions for chatbox

### ISSUE THREAD

**Issue by thelege2nd** [aaamoon/copilot-gpt4-service#164]
Hello, please include instructions for chatbox windows client.

I have [copilot-gpt4-service running on http://localhost:8080/ and I have chatbox windows client downloaded.

I am not quite sure how to integrate them together.

Thank you

**Comment by thelege2nd** [comment]
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/12984941/ad92891f-81fe-493a-9e98-3304e7ab59e6)

These are the settings im using. Is anything wrong here?

**Comment by aaamoon** [comment]
I don't see anything wrong, can you use it normally now?

**Comment by thelege2nd** [comment]
> I don't see anything wrong, can you use it normally now?
when I removed the / at the end of the URL, I get ' API Error: Status Code 500, {"error":"Failed to get authorization from token"}

I have ran the bat file and got the authorization key.
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/12984941/c8160922-b485-4387-b9cd-290a82828021)

**Comment by thelege2nd** [comment]
I just re-authored it, and now it works. 

![image](https://github.com/aaamoon/copilot-gpt4-service/assets/12984941/11a06a43-d521-4e02-8d3a-fe12d9b6a5c4)

Thank you for following up.
