### ISSUE TITLE
为什么我在vps上部署后还是用不了部署后的api（真小白🥺🥺）api是不是这样的http://vps的ip:8080

### ISSUE THREAD

**Issue by SuperrNaruto** [aaamoon/copilot-gpt4-service#165]
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/100200996/2d488de6-6e8e-463d-b7c1-48c86758241f)

**Comment by SuperrNaruto** [comment]
没问题好像是nextchat的问题

**Comment by poisonoff** [comment]
请问这个问题如何解决呢?
