### ISSUE TITLE
github copilot cli有产生ghu_*但同时收到failed to authenticate的迷惑消息最后Connection reset by peer

### ISSUE THREAD

**Issue by zhh210** [aaamoon/copilot-gpt4-service#168]
用了这个script

```
# The script below will automatically install Github Copilot CLI and obtain the Github Copilot Plugin Token through authorization
bash -c "$(curl -fsSL https://raw.githubusercontent.com/aaamoon/copilot-gpt4-service/master/shells/get_copilot_token.sh)"
```
貌似是成功生成了CLI token, 但是返回消息里同时说unable to verify waitlist access又很迷惑：
```
Then go to https://github.com/login/device, paste the code in and approve the access.
Failed to authenticate: You do not have access to GitHub Copilot CLI. Please join the waitlist at https://githubnext.com/projects/copilot-cli/., Unable to verify waitlist access.
Your Github Copilot CLI token : ghu_****
```

然而用这个token还是用不了：
```
curl --location 'http://localhost:8080/v1/chat/completions' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer ghu_****' \
--data '{
  "model": "gpt-4",
  "messages": [ {"role": "user", "content": "hello"}]
}'
```
报错：
`curl: (56) Recv failure: Connection reset by peer`

**Comment by aaamoon** [comment]
`curl: (56) Recv failure: Connection reset by peer`应该是你那边网络的问题

**Comment by liuminda** [comment]
一样的问题
Failed to authenticate: You do not have access to GitHub Copilot CLI. Please join the waitlist at https://githubnext.com/projects/copilot-cli/., Unable to verify waitlist access.
Your Github Copilot CLI token : ghu_***

配置使用后报错 "error": "Failed to get authorization from token"

**Comment by liuminda** [comment]
> ur service still in pending and in the waiting list @liuminda

How do I check my progress on that project? It’s been almost a year since I started using copilot.

**Comment by aaamoon** [comment]
Obtaining the token does not matter whether the Github Copilot CLI has been enabled or not.

**Comment by kkocdko** [comment]
You can see tips [here](https://github.com/aaamoon/copilot-gpt4-service/pull/173/files).
