### ISSUE TITLE
当输入过长的时候无法正确返回结果

### ISSUE THREAD

**Issue by lxzcpro** [aaamoon/copilot-gpt4-service#17]
<img width="214" alt="image" src="https://github.com/aaamoon/copilot-gpt4-service/assets/140240700/f06bc084-144a-476c-8004-53779747246f">

**Comment by aaamoon** [comment]
GPT-4的最大tokens数为32768，即2^15，这相当于大约64000个单词或50页的文字

**Comment by lxzcpro** [comment]
> GPT-4的最大tokens数为32768，即2^15，这相当于大约64000个单词或50页的文字

我的输入大概在300多个单词 但是已经无法得到回复

**Comment by aaamoon** [comment]
我部署的那台服务器太烂了，一年80块买的，应该是返回超时了，我刚刚试了下如果请求我服务器的后端服务的话，500个单词确实没回复了，在本地后端服务用同样的500个单词去提问，是能够正常返回的

**Comment by lxzcpro** [comment]
> 我部署的那台服务器太烂了，一年80块买的，应该是返回超时了，我刚刚试了下如果请求我服务器的后端服务的话，500个单词确实没回复了，在本地后端服务用同样的500个单词去提问，是能够正常返回的

哦哦好的原来是这样
