### ISSUE TITLE
how to enable copilot on github

### ISSUE THREAD

**Issue by mansoorj91** [aaamoon/copilot-gpt4-service#170]
Hi
How can I enable GitHub copilot? because I get error 403 every time

**Comment by aaamoon** [comment]
https://github.com/features/copilot

**Comment by hajmansoor** [comment]
you mean I have to buy ?
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/156500929/6a3f2dfc-cf20-4f87-8409-6c821f343de6)

**Comment by aaamoon** [comment]
Yes, if you didn't buy it in the first place, it is not recommended to buy it for this service
