### ISSUE TITLE
服务器docker布署后报错 "error": true,   "message": "Failed to fetch" 

### ISSUE THREAD

**Issue by 0x3fffff** [aaamoon/copilot-gpt4-service#175]
```json
{
  "error": true,
  "message": "Failed to fetch"
}
```
![QQ截图20240113190018](https://github.com/aaamoon/copilot-gpt4-service/assets/41370274/13149895-197a-4617-ae71-b4487caba013)
![QQ截图20240113190150](https://github.com/aaamoon/copilot-gpt4-service/assets/41370274/fa548c0d-7f4f-4067-801d-b610bd3057db)

在命令行输入
```bash
curl --location 'http://localhost:8080/v1/chat/completions' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer ghu_xx' \
--data '{
  "model": "gpt-4",
  "messages": [ {"role": "user", "content": "hello"}]
}'
```
返回为{"error":"Failed to get authorization from token"}

直接访问http://服务器ip:8080显示
![QQ截图20240113190422](https://github.com/aaamoon/copilot-gpt4-service/assets/41370274/68c32d00-1759-4d7d-82b5-c2ee8579f552)

使用
```bash
docker run -d \
  --name copilot-gpt4-service \
  --restart always \
  -p 8080:8080 \
  -e HOST=0.0.0.0 \
  aaamoon/copilot-gpt4-service:latest
```
部署
用host网络模式也一样

**Comment by aaamoon** [comment]
可以试下拉取最新的镜像，然后用curl的方式试一下看错误码返回什么

**Comment by aaamoon** [comment]
你那边的网络访问不到github的接口

**Comment by 0x3fffff** [comment]
> 你那边的网络访问不到github的接口

可以，用的香港服务器
```bash
PING github.com (20.205.243.166) 56(84) bytes of data.
64 bytes from 20.205.243.166 (20.205.243.166): icmp_seq=1 ttl=112 time=37.7 ms
64 bytes from 20.205.243.166 (20.205.243.166): icmp_seq=2 ttl=112 time=38.2 ms
64 bytes from 20.205.243.166 (20.205.243.166): icmp_seq=3 ttl=112 time=37.5 ms
64 bytes from 20.205.243.166 (20.205.243.166): icmp_seq=4 ttl=112 time=37.5 ms
```

**Comment by armangido** [comment]
Try to allow the Insecure content option in site settings.

**Comment by iamxiao01** [comment]
这个问题有解决吗 @0x3fffff

**Comment by 0x3fffff** [comment]
> 这个问题有解决吗 @0x3fffff

没有，容器里可以ping到api.github.com但是curl拿不到，防火墙什么的都关了，时区也改过，实在不知道什么原因了

**Comment by lowa9** [comment]
这个问题有具体解决方法吗？我也遇到过，经常是重启服务才解决，也不知道哪里出错了😭

**Comment by wilkinszhang** [comment]
我在stackoverflow上面找到的办法，copilot-gpt4-service使用的端口要加到可能位于命令 netsh interface ipv4 show exceptedportrange protocol=tcp 的任何排除端口范围内。
As per Docker issue for windows https://github.com/docker/for-win/issues/3171 :

You might have that port in any of the excluded port ranges of command netsh interface ipv4 show excludedportrange protocol=tcp

You can use solution mentioned in the above ticket.

Disable hyper-v (which will required a couple of restarts)

`dism.exe /Online /Disable-Feature:Microsoft-Hyper-V`

After finishing all the required restarts, reserve the port you want so hyper-v doesn't reserve it back

`netsh int ipv4 add excludedportrange protocol=tcp startport=50070 numberofports=1
`
Re-Enable hyper-V (which will require a couple of restart)

`dism.exe /Online /Enable-Feature:Microsoft-Hyper-V /All`

原链接：[(https://stackoverflow.com/a/65274083)](https://stackoverflow.com/a/65274083)
