### ISSUE TITLE
说明还是简单了点，小白还是不太明白详细操作

### ISSUE THREAD

**Issue by alexyang-sea** [aaamoon/copilot-gpt4-service#178]
虽然我已经在docker里运行了镜像了，但是打开http://localhost:8080 网址时找不到网页，是否是因为运行get_copilot_token.bat批处理后没有获取Copilot Token成功？如果获取成功了的话，还需要什么步骤才能打开网页成功？不需要gpt4的API-KEY了吗？下面是我运行了批处理后已经验证了的界面。
![2](https://github.com/aaamoon/copilot-gpt4-service/assets/137014157/9c9e5ee6-34a7-44f2-8b79-81989639ba51)

**Comment by SuperrNaruto** [comment]
http://localhost:8080/这个是部署出来的api,你可以在这个项目里的nextchat里用（小白加一）

**Comment by wx69wx** [comment]
小白不太明白，已部署过chatnextweb项目，它要求的环境变量就是api_key，这个服务安装得到了api地址和token填到哪里去？谢谢

**Comment by SuperrNaruto** [comment]
设置里/狗头

**Comment by alexyang-sea** [comment]
> 小白不太明白，已部署过chatnextweb项目，它要求的环境变量就是api_key，这个服务安装得到了api地址和token填到哪里去？谢谢

我是下的客户端启动的，但是启动后还是无法使用chatnextweb进行聊天，不知道是不是需要用到vercel这个来部署，感觉对小白来说太难啦点

**Comment by funnyzak** [comment]
你可以用 Chatbox，填写 API地址 和 Token 如下图：
<img width="578" alt="image" src="https://github.com/aaamoon/copilot-gpt4-service/assets/2562087/d35a1da5-56b7-4602-9050-718bf3a135bb">

**Comment by alexyang-sea** [comment]
> 你可以用 Chatbox，填写 API地址 和 Token 如下图： <img alt="image" width="578" src="https://private-user-images.githubusercontent.com/2562087/296802818-d35a1da5-56b7-4602-9050-718bf3a135bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzOTM2MjMsIm5iZiI6MTcwNTM5MzMyMywicGF0aCI6Ii8yNTYyMDg3LzI5NjgwMjgxOC1kMzVhMWRhNS01NmI3LTQ2MDItOTA1MC03MThiZjNhMTM1YmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTZUMDgyMjAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmY1MDU5MTJhYThlYTM5ZDcwM2I2YjllMmE2NDJhNGM0MmFkYjY4YzY1NjRmMGMxOTIyN2UyMWMwZmUwNjMwZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gAdGnE2Zc_JQHvQNkb-qk31fLs9Z7hsEApyLiBbsRJ4">

用chatbox还是不行，提示网络无法连接，是不是必须自己得有AIP Key才行？

**Comment by alexyang-sea** [comment]
> 推荐里只涉及到两个服务：
> 
> 1. copilot-gpt4-service，这个服务启动后不需要做任何事情，只需要这个服务的url就好，比如就是你的http://localhost:8080/
> 2. ChatGPT-Next-Web，这个服务直接docker部署就好
> 
> 然后
> 
> 1. [获取 Copilot token](https://github.com/aaamoon/copilot-gpt4-service/blob/master/README_CN.md#%E8%8E%B7%E5%8F%96-copilot-token)，格式类似这样的：_gho_22tydSJCxxxxxxxxxxxxxxxxxxxxxxxxBWA_
> 2. 随便打开一个浏览器
> 3. 打开ChatGPT-Next-Web页面，部署本地的话一般是http://localhost:3000
> 4. 点击左下角设置图标
> 5. 勾选自定义接口
> 6. 模型服务商选择openai
> 7. 接口地址填写“[http://localhost:8080/”](http://localhost:8080/%E2%80%9D)
> 8. Api key填写上面获取到的Copilot Token
> 9. 可以顺便改一下语言为中文
> 10. 右上角点击X就可以使用了
> 
> 这是我写给自己老婆的教程，补充了一些细节你可以看看能不能搞定

谢谢，你这个设置教程比较浅显易懂，但是我这样设置了，还是无法连上，不知道是不是docker部署有问题，现在docker上提示"该容器没有绑定挂载"是不是属于没部署好？docker镜像时就设置了名称和端口，其他不知道怎么设置就没填。
![1](https://github.com/aaamoon/copilot-gpt4-service/assets/137014157/bd86f8ed-8825-46be-8d7a-8046fe428cdf)
![2](https://github.com/aaamoon/copilot-gpt4-service/assets/137014157/7cbe0fd9-307e-4da0-8833-bdc68105a961)

**Comment by zhouyuexie** [comment]
我用的是docker compose部署的，你可以试试删掉旧的容器再重新在命令行中用[Docker 一键部署](https://github.com/aaamoon/copilot-gpt4-service/blob/master/README_CN.md#%E4%B8%80%E9%94%AE%E9%83%A8%E7%BD%B2%E6%96%B9%E5%BC%8F)方式来部署

**Comment by alexyang-sea** [comment]
还有个原因是不是因为我没有开通github copilot服务，因为我看开通要每个月10美刀，还是不便宜的

**Comment by SuperrNaruto** [comment]
你没开通github copilot当然用不了啊，就像有门没有钥匙😂> 还有个原因是不是因为我没有开通github copilot服务，因为我看开通要每个月10美刀，还是不便宜的

**Comment by shirenran** [comment]
> 还有个原因是不是因为我没有开通github copilot服务，因为我看开通要每个月10美刀，还是不便宜的

淘宝上可以买，比官网便宜很多，已经用了很久了

**Comment by tomridder** [comment]
> > 还有个原因是不是因为我没有开通github copilot服务，因为我看开通要每个月10美刀，还是不便宜的
> 
> 淘宝上可以买，比官网便宜很多，已经用了很久了

淘宝什么价格呢 大佬 给下链接吧
