### ISSUE TITLE
`cocopilot.org` 这个网站是官方的吗？

### ISSUE THREAD

**Issue by wangrongding** [aaamoon/copilot-gpt4-service#18]
cocopilot.org 这个网站是官方的吗？

<img width="629" alt="image" src="https://github.com/aaamoon/copilot-gpt4-service/assets/42437658/48ada1a7-0a74-443c-af38-02f8271f9a77">

<img width="1591" alt="image" src="https://github.com/aaamoon/copilot-gpt4-service/assets/42437658/d9e84e6f-de19-4575-bce1-2364b85cb83d">

会不会对拿到的 token 做记录或其它操作？

**Comment by aaamoon** [comment]
不是官方的，是 Pandora ChatGPT 作者 zhile 大佬维护的，我用了很久都没出过问题，如果实在不放心可以自行通过抓包获取 token

**Comment by wangrongding** [comment]
@aaamoon  感谢， 这个 网站的源码有开源出来吗？想学习一下🧐

**Comment by aaamoon** [comment]
@wangrongding 应该没有开源出来的
