### ISSUE TITLE
Null Null docker

### ISSUE THREAD

**Issue by thelege2nd** [aaamoon/copilot-gpt4-service#182]
Hello, where is there a NULL NULL after every response by AI?

![image](https://github.com/aaamoon/copilot-gpt4-service/assets/12984941/0edc25cb-b9f8-4985-b335-687d25894812)

How to fix this? I am using docker.

**Comment by funnyzak** [comment]
Try the latest image or pull the source code to start testing. 
Also, what client are you using?

**Comment by thelege2nd** [comment]
I did pull the latest image—the chatbox client. 

Do you have any ideas on what to do?

**Comment by funnyzak** [comment]
Try this image funnyzak/copilot-gpt4-service.

**Comment by Geniucker** [comment]
It should've been fixed in #132
