### ISSUE TITLE
Aligning the behaviour of official extensions

### ISSUE THREAD

**Issue by kkocdko** [aaamoon/copilot-gpt4-service#183]
I think some of the detail in the code may increase the risk of banning.

https://github.com/aaamoon/copilot-gpt4-service/blob/65226a13b9eb571a3da06313bd3d29ec4b4c9f32/main.go#L87-L88

Here a different `Machineid` and `Sessionid` are created for each time, while the behaviour of the official extension is Machineid stays the same, and a new Sessionid is used when there is a new session. My exploring in the `extension.js` of the official extension confirms my idea. Also, the current implementation is missing some headers.

```js
// /home/codespace/.vscode-remote/extensions/github.copilot-chat-0.11.1/dist/extension.js
let a = t64.get(jt), l = { Authorization: hae.format("Bearer %s", r), "X-Request-Id": i, "X-GitHub-Api-Version": "2023-07-07", "VScode-SessionId": a.sessionId, "VScode-MachineId": a.machineId, ...a.getEditorVersionHeaders(), ...e.getExtraHeaders ? e.getExtraHeaders() : {} };
require("fs").writeFileSync("/tmp/copilot-headers.json",JSON.stringify(l));

// {"Authorization":"Bearer tid=xxx...","X-Request-Id":"cc8a3d0b-xxxx-xxxx-a3d6-0f4831ebc58f","X-GitHub-Api-Version":"2023-07-07","VScode-SessionId":"79180284-xxxx-423d-ad93-328528801acd1705243019488","VScode-MachineId":"99ddb858-xxxx-40cb-bd00-45a24ef59798","Editor-Version":"vscode/1.85.1","Editor-Plugin-Version":"copilot-chat/0.11.1","Openai-Organization":"github-copilot","Copilot-Integration-Id":"vscode-chat"}
// {"Authorization":"Bearer tid=xxx...","X-Request-Id":"3e4926ce-xxxx-xxxx-a4f2-829c2da8c9bc","X-GitHub-Api-Version":"2023-07-07","VScode-SessionId":"79180284-xxxx-423d-ad93-328528801acd1705243019488","VScode-MachineId":"99ddb858-xxxx-40cb-bd00-45a24ef59798","Editor-Version":"vscode/1.85.1","Editor-Plugin-Version":"copilot-chat/0.11.1","Openai-Organization":"github-copilot","Copilot-Integration-Id":"vscode-chat"}
```

While I haven't personally be blocked, I think we may need to make some fixes to align the behaviour of the official extensions.

**Comment by aaamoon** [comment]
Thanks for reporting this issue. If you're able, could you please submit a Pull Request? Thanks!

**Comment by Geniucker** [comment]
I'm also wondering if it's necessary to cache machine id and session id cuz. Seems that the session id doesn't change before restarting the workspace. 
If needed, this may be referred https://github.com/Geniucker/CoGPT/commit/1217ac10f712c292c3e842b76aed4d8fc530c31e

**Comment by Geniucker** [comment]
> I'm also wondering if it's necessary to cache machine id and session id. Seems that the session id doesn't change before restarting the workspace. If needed, this may be referred [Geniucker/CoGPT@1217ac1](https://github.com/Geniucker/CoGPT/commit/1217ac10f712c292c3e842b76aed4d8fc530c31e)

In this way we're able to use different machine ID for different token

**Comment by funnyzak** [comment]
I checked the extension.js code and saw that the Machine Id is obtained by reading the machine hardware information, so if the hardware hasn't changed then the Machine ID should be the same.

The sessionid seems to be randomly generated each time a new conversation starts.

> I'm also wondering if it's necessary to cache machine id and session id. Seems that the session id doesn't change before restarting the workspace.我还想知道是否有必要缓存机器ID和会话ID。似乎在重新启动工作区之前会话 ID 没有更改。 If needed, this may be referred [Geniucker/CoGPT@1217ac1](https://github.com/Geniucker/CoGPT/commit/1217ac10f712c292c3e842b76aed4d8fc530c31e) 如果需要，可以参考 Geniucker/CoGPT@ 1217ac1

**Comment by Geniucker** [comment]
Seems it's better to ask here. Hi @kkocdko , how did you know machineid is a UUID instead of a hexstring with length 64.

**Comment by Geniucker** [comment]
Seems that both appear in vscode's code. I'm not sure which one is actually used

**Comment by funnyzak** [comment]
@Geniucker copilot chat 局部代码，供参考
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/2562087/1acad70e-0fa6-45b4-873d-83337496345f)


> Seems it's better to ask here. Hi @kkocdko , how did you know machineid is a UUID instead of a hexstring with length 64.

**Comment by Geniucker** [comment]
还有好几个实现，看来不同系统不一样，linux看起来不是UUID。vscode代码里面还有一个实现是MAC地址的sha256，我感觉还是保留原来的吧
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/61449208/b316e561-c72b-488b-8af3-73d3fbba695d)

**Comment by Geniucker** [comment]
但是我看来我的wsl的/etc/machine-id只有32位，感觉也怪怪的

**Comment by funnyzak** [comment]
不同平台获取 MachineId 的方式应该是不一样的。 Linux 看代码应该是 32 位16进制字符串。

![image](https://github.com/aaamoon/copilot-gpt4-service/assets/2562087/352b8cf1-40d2-4725-a844-07b940c5fa5c)


> 还有好几个实现，看来不同系统不一样，linux看起来不是UUID。vscode代码里面还有一个实现是MAC地址的sha256，我感觉还是保留原来的吧 ![image](https://private-user-images.githubusercontent.com/61449208/298292888-b316e561-c72b-488b-8af3-73d3fbba695d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MDUwOTgsIm5iZiI6MTcwNTgwNDc5OCwicGF0aCI6Ii82MTQ0OTIwOC8yOTgyOTI4ODgtYjMxNmU1NjEtYzcyYi00ODhiLThhZjMtNzNkM2ZiYmE2OTVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDAyMzk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlNDgwZjY4NmQwY2RhYmMxYzI4YWVmNDM1YWViYWVhZTUzMDgyODMwMzEzZTY5MzU2YzA1MTIzYmY0MThhY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uizantFecpvaFLHzxrpg_7Eir2-xiam-Sm1FKcCbJfU)
