### ISSUE TITLE
can we use this project with open-interpreter

### ISSUE THREAD

**Issue by arifsha39** [aaamoon/copilot-gpt4-service#184]
### Description

can we use this service as a custom endpoint in  this project https://github.com/KillianLucas/open-interpreter

if yes pls guide us how to do so

if not all good 

thx for this awesome project 

### Why

becuase it will help me to use gpt4 for free on my selected project 

### Alternatives

i dont have any 

thx..

**Comment by Geniucker** [comment]
Yes, but you are supposed to use a .py file
Here is a possible code
```python
from interpreter import interpreter

interpreter.offline = True
# Whether to ask before executing code
interpreter.auto_run = False
# Model to use
interpreter.llm.model = "gpt-3.5-turbo"
# api_base
interpreter.llm.api_base = "http://localhost:8080/v1" # don't forget to add /v1
# your key
interpreter.llm.api_key = "YOUR_KEY"

interpreter.chat(stream=True)
```
