### ISSUE TITLE
使用 openai 官方 python 库会报错

### ISSUE THREAD

**Issue by IwfWcf** [aaamoon/copilot-gpt4-service#189]
### Description

```
import openai

# optional; defaults to `os.environ['OPENAI_API_KEY']`
openai.api_key = 'ghu_xxx'

# all client options can be configured just like the `OpenAI` instantiation counterpart
openai.base_url = "https://xxx.com"
openai.default_headers = {"x-foo": "true"}

completion = openai.chat.completions.create(
    model="gpt-4",
    messages=[
        {
            "role": "user",
            "content": "How do I output all files in a directory using Python?",
        },
    ],
)
print(completion.choices[0].message.content)
```

报错信息

```
Traceback (most recent call last):
  File "/Users/iwfwcf/Downloads/BallonsTranslator/test_api.py", line 10, in <module>
    completion = openai.chat.completions.create(
  File "/Users/iwfwcf/Downloads/BallonsTranslator/venv/lib/python3.9/site-packages/openai/_utils/_utils.py", line 271, in wrapper
    return func(*args, **kwargs)
  File "/Users/iwfwcf/Downloads/BallonsTranslator/venv/lib/python3.9/site-packages/openai/resources/chat/completions.py", line 643, in create
    return self._post(
  File "/Users/iwfwcf/Downloads/BallonsTranslator/venv/lib/python3.9/site-packages/openai/_base_client.py", line 1112, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/Users/iwfwcf/Downloads/BallonsTranslator/venv/lib/python3.9/site-packages/openai/_base_client.py", line 859, in request
    return self._request(
  File "/Users/iwfwcf/Downloads/BallonsTranslator/venv/lib/python3.9/site-packages/openai/_base_client.py", line 949, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.APIStatusError: Method Not Allowed
```

**Comment by IwfWcf** [comment]
使用 https://github.com/wpv-chan/cf-copilot-service 部署在 cf 的版本就没有这个问题

**Comment by IwfWcf** [comment]
知道原因了，要改成 openai.base_url = "https://xxx.com/v1/" 这样

**Comment by thangckt** [comment]
hi, 

I have a problem that the model used in python API and from Next-Chat is not the same.
From Next-Chat, I can get the model gpt-4.
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/46436648/2d28bf89-133f-43e9-91c8-e62c12f4cce5)

However, when I try with python, it is always gpt-3
```
import openai

openai.api_key = OPENAI_API_KEY
openai.base_url = "http://127.0.0.1:8080/v1/"

completion = openai.chat.completions.create(
    model="gpt-4-1106-preview",
    messages=[{"role": "user", "content": "What is your model?", } ],
)
print(completion.choices[0].message.content)
```
Output:
```
I am an AI language model developed by OpenAI called GPT-3 (Generative Pre-trained Transformer 3). I have been trained on a vast amount of text data to generate human-like responses to various prompts and questions.
```
anyone know how to solve this problem?

Thanks

**Comment by aaamoon** [comment]
@thangckt The model should be gpt-4, not gpt-4-1106-preview.
https://github.com/aaamoon/copilot-gpt4-service?tab=readme-ov-file#model-support

**Comment by thangckt** [comment]
hi @aaamoon 

I just want to know why there is a different response between python API and Chat-Next-Web?

**Comment by Aryavui** [comment]
don't trust it's response abouting it's version, you should use other prompts to test it's version

**Comment by thangckt** [comment]
hi @Aryavui 

Does anyway that we can get the same response?

**Comment by Geniucker** [comment]
Here are all models supported. Unsupported models will be ignored and a default model will be used. The default model may be gpt-3.5-turbo
<img width="862" alt="image" src="https://github.com/aaamoon/copilot-gpt4-service/assets/61449208/309a6be9-1188-4e29-9b17-57345d3a66da">

**Comment by thangckt** [comment]
hi @Geniucker 

It is strange that I use the same setting, but responses are different between webapp and python API

**Comment by Geniucker** [comment]
Can you provide an example?

**Comment by thangckt** [comment]
I described [here](https://github.com/aaamoon/copilot-gpt4-service/issues/189#issuecomment-1897981772)

**Comment by Geniucker** [comment]
> Here are all models supported. Unsupported models will be ignored and a default model will be used. The default model may be gpt-3.5-turbo <img alt="image" width="862" src="https://private-user-images.githubusercontent.com/61449208/297742079-309a6be9-1188-4e29-9b17-57345d3a66da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MDAzOTAsIm5iZiI6MTcwNTYwMDA5MCwicGF0aCI6Ii82MTQ0OTIwOC8yOTc3NDIwNzktMzA5YTZiZTktMTE4OC00ZTI5LTliMTctNTczNDVkM2E2NmRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDE3NDgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjY2U0Zjc5MDU2OTM1ZmU5NWI1ZGZlYjU0NTc1MjIwNDE5NTVhYmU2OGYwMDU3YjIyZThiYzYzZjE5ZDE0OWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GyRA8fFIA1dIfe2mr9s1pnGT6EvypKDYNegTEvlYDDw">

If you use a model not in this list, gpt-3.5-turbo will be used. Maybe that's the cause

**Comment by thangckt** [comment]
yes, I understand what you mentioned.
Then it should also `gpt-3.5-turbo` in webapp, right?
But it does not.

**Comment by Geniucker** [comment]
Sorry for misunderstanding your question.
I just checked the request of chatgpt next we, here's the request body:
```
{
    "messages": [
        {
            "role": "system",
            "content": "\nYou are ChatGPT, a large language model trained by OpenAI.\nKnowledge cutoff: 2023-04\nCurrent model: gpt-4-1106-preview\nCurrent time: 1/19/2024, 2:04:10 AM\nLatex inline: $x^2$ \nLatex block: $$e=mc^2$$\n\n"
        },
        {
            "role": "user",
            "content": "hi"
        }
    ],
    "stream": true,
    "model": "gpt-4-1106-preview",
    "temperature": 0.5,
    "presence_penalty": 0,
    "frequency_penalty": 0,
    "top_p": 1
}
```
Hence the model used is actually gpt-3.5-turbo, but due to the system prompt, he said he was gpt-4-1106-preview

**Comment by thangckt** [comment]
@Geniucker 
I am clear 
Thank you so much for your guide
