### ISSUE TITLE
请问这个是什么问题？

### ISSUE THREAD

**Issue by lww0751** [aaamoon/copilot-gpt4-service#19]
{
  "error": true,
  "message": "empty response"
}

![Uploading 微信截图_20240105121238.png…]()

**Comment by aaamoon** [comment]
1.你的github账号有开通copilot吗
2.试下重新获取token
3.可以截图一下客户端配置页面看看吗

**Comment by lww0751** [comment]
![微信截图_20240105125159](https://github.com/aaamoon/copilot-gpt4-service/assets/155702763/36edd783-b99e-46c4-8202-e7dd19abbbfc)

**Comment by aaamoon** [comment]
看不出什么问题，如果有需要的话可以把token发到linexia6@gmail.com我本地调试下

**Comment by kailifapon** [comment]
I have met the same issue.

**Comment by maker997** [comment]
也是相同的问题，发送消息没有响应

**Comment by aaamoon** [comment]
出现这个问题有可能是：1、没有github copilot权限   2、token过期了  3、后端服务器挂了
如果有需要的话可以把token发到[linexia6@gmail.com](mailto:linexia6@gmail.com)我本地调试下

**Comment by aaamoon** [comment]
@kailifapon I don't see any problems, if you need to, you can send the token to linexia6@gmail.com me for local debugging

**Comment by SuperRonin** [comment]
也是相同的问题，发送消息没有响应

**Comment by SuperRonin** [comment]
是不是被和谐了

![image](https://github.com/aaamoon/copilot-gpt4-service/assets/22882883/2f798049-b882-4437-9241-3654e4c8a16b)

**Comment by aaamoon** [comment]
@SuperRonin 出现这个问题有可能是：1、没有github copilot权限 2、token过期了 3、后端服务器挂了 4、淘宝远程授权的账号是不行的
如果有需要的话可以把token发到[linexia6@gmail.com](mailto:linexia6@gmail.com)我本地调试下

**Comment by aaamoon** [comment]
服务端已更新对错误信息的更好展示：
401: 使用的 Github Copilot Plugin Token 过期了或者错误，请重新获取
403: 使用的账号没有开通 Github Copilot

**Comment by ZZzz-hub** [comment]
@aaamoon 同样的错但是返回的是200，response为空

**Comment by aaamoon** [comment]
@ZZzz-hub 
试下curl的方式看看返回什么
```
curl --location 'http://127.0.0.1:8080/v1/chat/completions' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer ghu_xx' \
--data '{
  "model": "gpt-4",
  "messages": [ {"role": "user", "content": "hello"}]
}'
```
