### ISSUE TITLE
获取token报错，是不是我没有权限使用GitHub Copilot 

### ISSUE THREAD

**Issue by zhang7249** [aaamoon/copilot-gpt4-service#190]
### Description

Then go to https://github.com/login/device, paste the code in and approve the access.
Failed to authenticate: You do not have access to GitHub Copilot CLI. Please join the waitlist at https://githubnext.com/projects/copilot-cli/., Unable to verify waitlist access.

**Comment by funnyzak** [comment]
终端运行 `~/.copilot-cli-access-token `，看看有打印吗？！
