### ISSUE TITLE
本地源码部署是怎么部署的啊

### ISSUE THREAD

**Issue by Tryici** [aaamoon/copilot-gpt4-service#191]
本地源码部署是怎么部署的啊，不太懂，求教程

**Comment by aaamoon** [comment]
与客户端一起部署：https://github.com/aaamoon/copilot-gpt4-service/blob/master/example/docker-compose/with-next-chatgpt-web.docker-compose.yaml

**Comment by Tryici** [comment]
可以打开nextchat的页面了，然后请问设置中的访问密码、接口地址怎么填呢，
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/61930737/e4948417-6550-48ba-8004-20aab8a18c51)
报了这个错，如何配置呢~感谢

**Comment by x-sual-sam** [comment]
访问密码是你自己设置的，接口地址，如果是本地虚拟机的话，直接虚拟机地址+8080端口即可，不要写localhost

**Comment by Tryici** [comment]
我是在本地使用docker运行的，但它好像还是不能正确运行，我填写如下
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/61930737/95e9bd34-3467-419d-ad6d-f7a6ee583d74)

**Comment by thangckt** [comment]
hi, 
I get the same problem 

```sh
{
  "error": true,
  "message": "Failed to fetch"
}
```
Do you know how to solve it?
Thanks

**Comment by aaamoon** [comment]
> 我是在本地使用docker运行的，但它好像还是不能正确运行，我填写如下 ![image](https://private-user-images.githubusercontent.com/61930737/296920491-95e9bd34-3467-419d-ad6d-f7a6ee583d74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzODc5MzMsIm5iZiI6MTcwNTM4NzYzMywicGF0aCI6Ii82MTkzMDczNy8yOTY5MjA0OTEtOTVlOWJkMzQtMzQ2Ny00MTlkLWFkNmQtZjdhNmVlNTgzZDc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA2NDcxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiZTM4MTU5Yjc0NmQ1OGQxZDQwYjNkNzE4YjY5MmM3MmYxNzQ0OWQwYTk5NWQ1MDgxOTQ0MWQ1MzlmMTNhYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._lUtF2t4K4TC5iqlNvn63uZK9F_5gSNVs-TqrCtakTo)

试下把https改成http看看

**Comment by aaamoon** [comment]
> hi, I get the same problem
> 
> ```shell
> {
>   "error": true,
>   "message": "Failed to fetch"
> }
> ```
> 
> Do you know how to solve it? Thanks

It may be because the chatgpt-next-web you deployed is https and the server is http

**Comment by Tryici** [comment]
> > 我是在本地使用docker运行的，但它好像还是不能正确运行，我填写如下 ![image](https://private-user-images.githubusercontent.com/61930737/296920491-95e9bd34-3467-419d-ad6d-f7a6ee583d74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzODc5MzMsIm5iZiI6MTcwNTM4NzYzMywicGF0aCI6Ii82MTkzMDczNy8yOTY5MjA0OTEtOTVlOWJkMzQtMzQ2Ny00MTlkLWFkNmQtZjdhNmVlNTgzZDc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA2NDcxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiZTM4MTU5Yjc0NmQ1OGQxZDQwYjNkNzE4YjY5MmM3MmYxNzQ0OWQwYTk5NWQ1MDgxOTQ0MWQ1MzlmMTNhYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._lUtF2t4K4TC5iqlNvn63uZK9F_5gSNVs-TqrCtakTo)
> 
> 试下把https改成http看看

可以了，非常感谢！

**Comment by Tryici** [comment]
> hi, I get the same problem你好 我遇到了同样的问题
> 
> ```shell
> {
>   "error": true,
>   "message": "Failed to fetch"
> }
> ```
> 
> Do you know how to solve it? Thanks你知道怎么解决吗？ 谢谢

![image](https://github.com/aaamoon/copilot-gpt4-service/assets/61930737/dd0b344d-4cc3-4515-9c1b-766e819e836b)
change "https" to "http", and then it works! As above.

**Comment by thangckt** [comment]
hi @aaamoon @Tryici 

There is no "s" in my url
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/46436648/2326a268-eba0-4824-9fab-06604d529393)
But still error

**Comment by alexyang-sea** [comment]
请问这里的API Key是自己自定义的吗？

**Comment by aaamoon** [comment]
> > 可以打开nextchat的页面了，然后请问设置中的访问密码、接口地址怎么填呢， ![image](https://private-user-images.githubusercontent.com/61930737/296813312-e4948417-6550-48ba-8004-20aab8a18c51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzOTI5NDksIm5iZiI6MTcwNTM5MjY0OSwicGF0aCI6Ii82MTkzMDczNy8yOTY4MTMzMTItZTQ5NDg0MTctNjU1MC00OGJhLTgwMDQtMjBhYWI4YTE4YzUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA4MTA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxNTZhNGNmN2QxNmVlNWZhZGEwM2NlY2YxOWQxNjNjYzA4YTg2M2MwMzc4ZGMzNTk2NzMyNDk5NjlhOWI3M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8Ambe3kYlQGrRsezXc8MRDntysCdnHFluruT4B_FPQw) 报了这个错，如何配置呢~感谢
> 
> 我也是报了这个错，但也没有s啊，我是用docker部署的，用的nextchat客户端登录的，是不是还是哪里设置不对？API Key是自己随便定义的吗？ ![1](https://private-user-images.githubusercontent.com/137014157/296976154-d467aaf1-d30f-49ac-a4f2-cf49a26ae6e5.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MTYxMTcsIm5iZiI6MTcwNTQxNTgxNywicGF0aCI6Ii8xMzcwMTQxNTcvMjk2OTc2MTU0LWQ0NjdhYWYxLWQzMGYtNDlhYy1hNGYyLWNmNDlhMjZhZTZlNS5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQxNDM2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MmNjMWRhMzFkYWY4YWNhYTQ1NjEwZTNmMmY0NjZlZGFlOTUyODVhMWUxMDFhZDU0N2Y0NjQyOWNiZmMyMDljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Q_bGyZbQ0bgx1BZG6_93JILOQcgIBGezixBqF6eWwMY)

试下curl能不能正常请求

**Comment by thangckt** [comment]
after rebuild server
I can get it work now

Thanks.

**Comment by alexyang-sea** [comment]
> after rebuild server I can get it work now
> 
> Thanks.

May I ask what exact steps you took to achieve this?I haven't succeeded so far.

**Comment by thangckt** [comment]
> May I ask what exact steps you took to achieve this?I haven't succeeded so far.

The problem is possibly due to I suddenly close the the terminal that run the service. 
It should be keep to alway open.

**Comment by alexyang-sea** [comment]
> > May I ask what exact steps you took to achieve this?I haven't succeeded so far.
> 
> The problem is possibly due to I suddenly close the terminal that runs the service. It should be keep to alway open.

API Key do I need to have purchased it officially from OPENAI to log in?

**Comment by alexyang-sea** [comment]
放弃了，看来想在本地免费部署GPT4是不可能得，开通 Github Copilot 服务也还是需要有偿订阅，还是老老实实用潘多拉的共享账号算啦。

**Comment by two-tigger** [comment]
> 放弃了，看来想在本地免费部署GPT4是不可能的，开通 Github Copilot 服务也还是需要有偿订阅，还是老老实实用潘多拉的共享账号算啦。

账号淘宝可以买，但本地部署还是比较复杂，建议装虚拟机或者买服务lunix部署

**Comment by tomridder** [comment]
> > 放弃了，看来想在本地免费部署GPT4是不可能的，开通 Github Copilot 服务也还是需要有偿订阅，还是老老实实用潘多拉的共享账号算啦。
> 
> 账号淘宝可以买，但本地部署还是比较复杂，建议装虚拟机或者买服务lunix部署

淘宝什么价格呢 大佬 给下链接吧
