### ISSUE TITLE
使用Chatbox返回的回答字符串前后都有"null"

### ISSUE THREAD

**Issue by Marvin-z** [aaamoon/copilot-gpt4-service#193]
### Description

![图片](https://github.com/aaamoon/copilot-gpt4-service/assets/26019999/4354e8e8-4103-4920-9d63-4dbdb1097a23)

**Comment by Marvin-z** [comment]
但是用NextChat的时候没有

**Comment by funnyzak** [comment]
更新下最新代码.

或升级Image => aaamoon/copilot-gpt4-service:d2392e6
