### ISSUE TITLE
alpine:latest镜像不支持时区设置

### ISSUE THREAD

**Issue by wust-lzy** [aaamoon/copilot-gpt4-service#194]
### Description

容器内时区不对，不支持设置时区环境变量

/app # export TZ=Asia/Shanghai
/app # date
Tue Jan 16 03:19:45 UTC 2024

### Why

alpine 是精简版镜像，默认不带 timezone

### Alternatives

alpine安装timezone包或者更换其他镜像

**Comment by 0x3fffff** [comment]
楼主解决了吗，我可能也是这个问题，可以ping到但curl拿不到

**Comment by wust-lzy** [comment]
> 楼主解决了吗，我可能也是这个问题，可以ping到但curl拿不到

可以下载源码， 在dockerfile里面换一个镜像，或者等作者出新的镜像吧

**Comment by funnyzak** [comment]
我这边测试看看。

> > 楼主解决了吗，我可能也是这个问题，可以ping到但curl拿不到
> 
> 可以下载源码， 在dockerfile里面换一个镜像，或者等作者出新的镜像吧

**Comment by funnyzak** [comment]
> 我这边测试看看。
> 
> > > 楼主解决了吗，我可能也是这个问题，可以ping到但curl拿不到
> > 
> > 
> > 可以下载源码， 在dockerfile里面换一个镜像，或者等作者出新的镜像吧

PR #198 已调整时区问题，等待后续PR合并后镜像更新。

**Comment by funnyzak** [comment]
@0x3fffff @wust-lzy 镜像已经更新。 可以通过如下tag拉取：

```bash
docker pull aaamoon/copilot-gpt4-service:latest
# 或者
docker pull aaamoon/copilot-gpt4-service:master
```
