### ISSUE TITLE
Where do I put config.env ?

### ISSUE THREAD

**Issue by ryleenhughes** [aaamoon/copilot-gpt4-service#197]
Hello, thank you for providing this nice and excellent project!  
I'm reading the README, and i saw you wrote that: 
```
Use environment variables or environment variable configuration file config.env to configure the service (environment variables take precedence over config.env), the default configuration items are as follows:
```   

Would you mind explain a little that where exactly i should put this config file into? is it the `~`? or the root dir of this repo?   
I also noticed that it says you can put them into system environment variables, but wouldn't those names (fields) too common that influenced other software?
Thank you for answering!

**Comment by jmanhype** [comment]
ive done all of that and im getting failed to fetch error please hlp

**Comment by aaamoon** [comment]
Please try curl to see if it returns properly.
`
curl --location 'http://127.0.0.1:8080/v1/chat/completions' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer ghu_xx' \
--data '{
  "model": "gpt-4",
  "messages": [ {"role": "user", "content": "hello"}]
}'
`

**Comment by ryleenhughes** [comment]
@aaamoon Thank you so much for telling! So i don't really need to do this if i'm using docker, right? now i got it, i'll close this ticket.
