### ISSUE TITLE
接口是挂的，聊天不行

### ISSUE THREAD

**Issue by aiesst** [aaamoon/copilot-gpt4-service#20]
![Uploading 微信图片_20231214175535.png…]()

**Comment by aaamoon** [comment]
出现这个问题有可能是：1、没有github copilot权限 2、token过期了 3、淘宝远程授权的账号是不行的 4、后端服务器挂了
如果有需要的话可以把token发到`linexia6@gmail.com`我本地调试下，备注下github名称
