### ISSUE TITLE
推荐了本地部署，但是却没有写如何本地部署

### ISSUE THREAD

**Issue by keenorchen** [aaamoon/copilot-gpt4-service#201]
### Description

文档说明写到：

经社区验证和讨论，最佳实践方式为:

本地部署，仅个人使用（推荐）；
自用服务器集成 [ChatGPT-Next-Web](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web) 部署, 服务不公开；
服务器部署, 公开但个人使用 (例如多客户端使用场景）

但是最推荐的本地部署却没有写具体方法。

### Why

文档前后逻辑不一致

### Alternatives

补充本地部署文档

**Comment by keenorchen** [comment]
本地指的是Windows电脑，没有docker，更没有K8s

**Comment by Quantatirsk** [comment]
这里说的本地环境，是相对cloudflare pages 或者vercel服务而言，指的是向api发送请求的ip地址在本地

**Comment by zhouyuexie** [comment]
https://github.com/aaamoon/copilot-gpt4-service/issues/178#issuecomment-1895297518

可以看看我刚刚在另一个issue里的回复

**Comment by Geniucker** [comment]
一个可能的方法是使用任务计划开机启动

**Comment by kkocdko** [comment]
如个懒得用 Docker 之类的，那就自己编译，或者从本项目的 GitHub Actions 里下载来运行就可以。

https://github.com/aaamoon/copilot-gpt4-service/actions/runs/7573320201

```
Artifacts
Produced during runtime
Name	Size	
copilot-gpt4-service-darwin-amd64
10.5 MB	
copilot-gpt4-service-darwin-arm64
10.2 MB	
copilot-gpt4-service-linux-amd64
10.6 MB	
copilot-gpt4-service-linux-arm64
10.1 MB	
copilot-gpt4-service-windows-amd64
10.7 MB	
copilot-gpt4-service-windows-arm64
10.1 MB
```

**Comment by JokinYang** [comment]
> 如个懒得用 Docker 之类的，那就自己编译，或者从本项目的 GitHub Actions 里下载来运行就可以。
> 
> https://github.com/aaamoon/copilot-gpt4-service/actions/runs/7573320201
> 
> ```
> Artifacts
> Produced during runtime
> Name	Size	
> copilot-gpt4-service-darwin-amd64
> 10.5 MB	
> copilot-gpt4-service-darwin-arm64
> 10.2 MB	
> copilot-gpt4-service-linux-amd64
> 10.6 MB	
> copilot-gpt4-service-linux-arm64
> 10.1 MB	
> copilot-gpt4-service-windows-amd64
> 10.7 MB	
> copilot-gpt4-service-windows-arm64
> 10.1 MB
> ```

使用了Github Action构建的copilot-gpt4-service-windows-amd64，在运行时提示如下错误
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/22725499/cd2be57a-09a5-4489-bb55-6c82316486bd)

**Comment by funnyzak** [comment]
针对 copilot-gpt4-service 本地部署的方式，如安装 Go 环境源码启动 或 Docker方式启动，对于菜鸟有点复杂了。

觉得再简单的方式，就是服务编译为不同平台的执行程序。然后：
- Windows 平台，把程序把放到windows的启动文件夹就可以随机启动了。
- Mac或Linux 平台，就把程序写到shell脚本里，把脚本设置到系统登陆项，也随机启动。

**Comment by Geniucker** [comment]
> > 如个懒得用 Docker 之类的，那就自己编译，或者从本项目的 GitHub Actions 里下载来运行就可以。
> > https://github.com/aaamoon/copilot-gpt4-service/actions/runs/7573320201
> > ```
> > Artifacts
> > Produced during runtime
> > Name	Size	
> > copilot-gpt4-service-darwin-amd64
> > 10.5 MB	
> > copilot-gpt4-service-darwin-arm64
> > 10.2 MB	
> > copilot-gpt4-service-linux-amd64
> > 10.6 MB	
> > copilot-gpt4-service-linux-arm64
> > 10.1 MB	
> > copilot-gpt4-service-windows-amd64
> > 10.7 MB	
> > copilot-gpt4-service-windows-arm64
> > 10.1 MB
> > ```
> 
> 使用了Github Action构建的copilot-gpt4-service-windows-amd64，在运行时提示如下错误 ![image](https://private-user-images.githubusercontent.com/22725499/297964117-cd2be57a-09a5-4489-bb55-6c82316486bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDQ4OTEsIm5iZiI6MTcwNTY0NDU5MSwicGF0aCI6Ii8yMjcyNTQ5OS8yOTc5NjQxMTctY2QyYmU1N2EtMDlhNS00NDg5LWJiNTUtNmM4MjMxNjQ4NmJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA2MDk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmMmFjOGI2YThjOGI5ZDdkM2RlYTNmZWUwMTUzNDU1NTY3ZDM0NDU2OTZiOTFhYzA4YzcwNTQwYmEwOTU3MTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rq6DFS9SslK32Efjl0f7Ap0asLsE-vLeAkfWeUlxpYI)

go-sqlite3 需要 cgo， #198 更换了 sqlite 驱动，不再需要 cgo，现在须有有人进行测试

**Comment by Geniucker** [comment]
只要这个服务是你个人使用，都是可以的

**Comment by KikiingOne** [comment]
想在现成的，云端一键部署的chatnext里面用，url是什么，用本地的那个不行

**Comment by two-tigger** [comment]
> 想在现成的，云端一键部署的chatnext里面用，url是什么，用本地的那个不行

请问现在部署报错405如何解决？

**Comment by two-tigger** [comment]
> 如个懒得用 Docker 之类的，那就自己编译，或者从本项目的 GitHub Actions 里下载来运行就可以。
> 
> https://github.com/aaamoon/copilot-gpt4-service/actions/runs/7573320201
> 
> ```
> Artifacts
> Produced during runtime
> Name	Size	
> copilot-gpt4-service-darwin-amd64
> 10.5 MB	
> copilot-gpt4-service-darwin-arm64
> 10.2 MB	
> copilot-gpt4-service-linux-amd64
> 10.6 MB	
> copilot-gpt4-service-linux-arm64
> 10.1 MB	
> copilot-gpt4-service-windows-amd64
> 10.7 MB	
> copilot-gpt4-service-windows-arm64
> 10.1 MB
> ```

这个现在根本用不了。。。。。。。
