### ISSUE TITLE
照著方法做，但還是不行

### ISSUE THREAD

**Issue by keewing** [aaamoon/copilot-gpt4-service#202]
### Description

![image](https://github.com/aaamoon/copilot-gpt4-service/assets/156865648/e5175370-27df-41b0-970c-ab335eebcee7)
前面全都是照著做，但卻不行，也有 curl http://127.0.0.1:8080 ，跑出Failed to connect to 127.0.0.1 port 8080

**Comment by aaamoon** [comment]
试下：
```
curl --location 'http://127.0.0.1:8080/v1/chat/completions' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer ghu_xx' \
--data '{
  "model": "gpt-4",
  "messages": [ {"role": "user", "content": "hello"}]
}'
```

**Comment by keewing** [comment]
還是一樣  curl: (7) Failed to connect to 127.0.0.1 port 8080 after 2048 ms: Couldn't connect to server

**Comment by aaamoon** [comment]
你部署的端口是8099那就用8099，提示`Failed to get authorization from token`有两个原因
1、使用的 Github Copilot Plugin Token 过期了或者错误，请重新获取
2、使用的账号没有开通 Github Copilot
