### ISSUE TITLE
出现 Failed to get authorization from token

### ISSUE THREAD

**Issue by YukiCoco** [aaamoon/copilot-gpt4-service#203]
### Description

确定 GitHub Copilot 是开着的，可以从 vscode 插件进行对话，但是获取了一个 token 对话时显示
```
Failed to get authorization from token
```

下面是使用 curl 获取对话的信息
```
curl --location 'https://example/v1/chat/completions' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer ghu_xxx' \
--data '{
  "model": "gpt-4",
  "messages": [ {"role": "user", "content": "hello"}]
}'
```
```
< HTTP/2 500 
< access-control-allow-credentials: true
< access-control-allow-headers: *
< access-control-allow-methods: *
< access-control-allow-origin: *
< alt-svc: h3=":443"; ma=2592000
< content-type: application/json; charset=utf-8
< date: Wed, 17 Jan 2024 08:08:34 GMT
< server: Caddy
< content-length: 50
< 
* Connection #0 to host gptapi.kuri.su left intact
{"error":"Failed to get authorization from token"}
```

**Comment by zhouyuexie** [comment]
<img width="797" alt="Screenshot 2024-01-17 at 16 15 35" src="https://github.com/aaamoon/copilot-gpt4-service/assets/7876750/194df2e3-b825-42d1-beae-c5fdb27391a0">

你确定你的copilot是个人版本吗？

**Comment by YukiCoco** [comment]
> <img alt="Screenshot 2024-01-17 at 16 15 35" width="797" src="https://private-user-images.githubusercontent.com/7876750/297309304-194df2e3-b825-42d1-beae-c5fdb27391a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0Nzk2ODcsIm5iZiI6MTcwNTQ3OTM4NywicGF0aCI6Ii83ODc2NzUwLzI5NzMwOTMwNC0xOTRkZjJlMy1iODI1LTQyZDEtYmVhZS1jNWZkYjI3MzkxYTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTdUMDgxNjI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGM1OTg2NTA4YmJlZmNhMzAwZDFlODBlMGZkNTAzNGNhNTcyYzI5ZTFlNmY4OThkMjc2ZDk0NWViMzhhYzcwMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.q5B9TwY2w-QIOg4CCdSajmY3tKu6y8gQ-AXJxAAYOt8">
> 你确定你的copilot是个人版本吗？

是的
![](https://niconiacg.visualstudio.com/a158c0e6-f968-4c72-b336-690f5a7c8b4c/_apis/git/repositories/f4cb0aa8-76ef-49d2-bee3-9a3deda56975/items?path=/2024/0/3/8167ca930313.png&$format=octetStream&api-version=5.0)

**Comment by zhouyuexie** [comment]
按理说这个问题和这个项目没关系才对。。。你的vscode登录的github账号和网页上登录的是一样的吗？

实在不行可以试试在vscode上退出登录然后再登录一遍

**Comment by aaamoon** [comment]
应该是复制的token有误或者过期导致的，试下重新获取
