### ISSUE TITLE
how to store chats ?

### ISSUE THREAD

**Issue by mohatb** [aaamoon/copilot-gpt4-service#204]
**Are there certain things to report that are not a bug or feature?**
Please tell us as exactly as possible about your request, thanks.
We will reply as soon as possible.

Where does it store previous chats ? am using copilot-gpt4-service with chatgpt-next-web.enabled using the helm chart method. but I cannot find any documentation on how to store chats and settings on a pvc or DB. Whenever I refresh the page, chats are gone, any thoughts?

helm install copilot-gpt4-service aaamoon/copilot-gpt4-service \
  --set chatgpt-next-web.enabled=true \
  --set chatgpt-next-web.config.OPENAI_API_KEY=[ your openai api key ] \   #Token obtained by copilot
  --set chatgpt-next-web.config.CODE=[ backend access code ] \    # Access password for next chatgpt web ui
  --set chatgpt-next-web.service.type=NodePort \
  --set chatgpt-next-web.service.nodePort=30080

**Comment by Mark7888** [comment]
Reading through the code, I didn't find anything about storing chats. This module only stores authorization data in cache, and has an api endpoint (`/v1/chat/completions`), that does the complition. It creates a new conversation with your quote every time you ask something, there is no possibility to save or continue a conversation.

https://github.com/aaamoon/copilot-gpt4-service/blob/b6b23a1c13d39d9f7082e318c00c16412034c593/main.go#L134-L147

[ChatGPT-Next-Web](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web) might have a way of saving it, but this module doesn't.

(Correct me if I'm wrong)

**Comment by wust-lzy** [comment]
The chat data stored locally by next-chat-web

**Comment by mohatb** [comment]
do we know how they store it ? I guess they announce it only stores cache in the browser. but is there a way to change that ? at least to persist the customizations and settings.

**Comment by aaamoon** [comment]
You can go to [ChatGPT-Next-Web](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web) to see if there is a way to do this
