### ISSUE TITLE
API endpoint to be able to continue existing conversation

### ISSUE THREAD

**Issue by Mark7888** [aaamoon/copilot-gpt4-service#209]
### Description

At the moment, when you use the `/v1/chat/completions` endpoint, it created a new conversation with only the current content. 
I [forked](https://github.com/Mark7888/copilot-gpt4-service) the repo and added a [new method](https://github.com/Mark7888/copilot-gpt4-service/blob/629ff9c211c8ba80f996681733be3dded72069b7/main.go#L108) to be able to pass in whole conversations with history.
Does it fit the content of this repo? If it does, I could make a pull request to have this small feature.

### Why

I would like to use this module for my own project, and it would work perfectly, but I need the ability to continue existing conversations. Tried it out, and the copilot gpt api works the same as the official openai one, so I can pass in the history as well as the new content.

### Alternatives

Alternatively, I could use my own fork in my project, but it might also be useful for others.

**Comment by thangckt** [comment]
hi @Mark7888 

Can you post an example usage?

Thanks

**Comment by Mark7888** [comment]
Sure.

```bash
curl -X POST \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer YOUR_TOKEN_HERE" \
  -d '[
    {
        "role": "system",
        "content": "\nYou are ChatGPT, a large language model trained by OpenAI.\nKnowledge cutoff: 2021-09\nCurrent model: gpt-4\n"
    },
    {
        "role": "user",
        "content": "Remember this: Ronald has brown eyes."
    },
    {
        "role": "user",
        "content": "What color are Ronalds eyes?"
    }
]' \
  http://localhost:8080/v1/chat/conversation
```

Here is an example with `curl`, but you can use any tool or programming language to access this api. The POST request body contains the json data.

**Comment by Mark7888** [comment]
Reading a bit into the `openai` package, it calls the `/chat/completions` [endpoint](https://github.com/openai/openai-python/blob/3d61ed42aba652b547029095a7eb269ad4e1e957/src/openai/resources/chat/completions.py#L1300), and passes the json data into the post request body. But at this form, it's not really compatible, yet.

**Comment by thangckt** [comment]
@Mark7888 
thank you so much for your guide.

Can I ask a silly question, assume that I deploy the chatbot using Vercel at: url = `https://chat-gpt-next-xxxx-.vercel.app`
Does any we can use this url as an endpoint in python same as your above code?

Thank

**Comment by Mark7888** [comment]
I don't really understand, what you trying to do, but you can check out these python packages: [flask](https://pypi.org/project/Flask/), [django](https://pypi.org/project/Django/), [requests](https://pypi.org/project/requests/)
I hope this helps.

_By the way, this is not quite related to the topic of this issue anymore_

**Comment by Geniucker** [comment]
May the confusing code is [here](https://github.com/aaamoon/copilot-gpt4-service/blob/e745f3be9d26329eaa3d5e266279d4f092460e84/main.go#L107) and [here](https://github.com/aaamoon/copilot-gpt4-service/blob/e745f3be9d26329eaa3d5e266279d4f092460e84/main.go#L134)
A correct request body seems not to contain `content` field. I'm not sure why it's here but we're gonna modify it.
The original purpose of the latter code is to set the default body in case the `messages` field is empty

**Comment by Geniucker** [comment]
@aaamoon [this line](https://github.com/aaamoon/copilot-gpt4-service/blob/e745f3be9d26329eaa3d5e266279d4f092460e84/main.go#L107) seems confusing. Shall we just remove it and give a default value to the `message` field?

**Comment by Mark7888** [comment]
Thank you, that worked.

Well, yeah. [That](https://github.com/aaamoon/copilot-gpt4-service/blob/e745f3be9d26329eaa3d5e266279d4f092460e84/main.go#L107) line is really confusing.

I'm new to go, and I don't really understand, where does that `messages` variable comes from.
Is it copied [here](https://github.com/aaamoon/copilot-gpt4-service/blob/e745f3be9d26329eaa3d5e266279d4f092460e84/main.go#L147C27-L147C27)?

**Comment by Geniucker** [comment]
Yes ur right. If there's `messages` field in the request body, it will overwrite the one in `jsonBody`
