### ISSUE TITLE
知识库被设定在2021-09

### ISSUE THREAD

**Issue by 742445211** [aaamoon/copilot-gpt4-service#21]
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/47823535/d696ab18-9987-406c-8545-46df2081d20f)
每个问答都有这一段，请问怎么去掉呢？

**Comment by aaamoon** [comment]
把"注入系统级提示信息"这个配置关闭即可
<img width="1148" alt="截屏2024-01-05 下午3 05 59" src="https://github.com/aaamoon/copilot-gpt4-service/assets/25700476/fdad7295-bf90-45b7-bd75-044010c0fe09">

**Comment by 742445211** [comment]
去掉了，谢谢
