### ISSUE TITLE
"Method Not Allowed" in Langchain

### ISSUE THREAD

**Issue by thangckt** [aaamoon/copilot-gpt4-service#214]
### Description

Dear Developers, 

I try with python, and the code below work in `openai` backage
```
from openai import OpenAI
client = OpenAI(api_key=api_key, base_url = "http://127.0.0.1:8080/v1/")
```
However, when I try with OpenAI module in `langchain`, it raise the error "Method Not Allowed"
```
from langchain_openai import OpenAI
llm = OpenAI(api_key=api_key, base_url = "http://127.0.0.1:8080/v1/")
```

Can you have a little guide how to overcome this?
Thanks.

**Comment by funnyzak** [comment]
**/v1/** is not a valid routing path. Currently released version, only supported:

- /v1/chat/completions
- /v1/models
- /healthz

Default route requests uniformly return **405 Method Not Allowed**.

**Comment by Geniucker** [comment]
You can go to the definition of those classes to see what's the differences

**Comment by Geniucker** [comment]
I think it's the problem of Langchain. I just tested Langchain and found the default base api it used was `https://api.openai.com/v1/completions`, which will be deprecated January 4th, 2024. The request bodies of `https://api.openai.com/v1/completions` and `https://api.openai.com/v1/chat/completions` are different. This should be the cause of your problem.
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/61449208/bc672541-1027-41f9-b40b-3c639ffaad40)
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/61449208/db82bcee-54d5-435a-bf9c-7c1f42554e20)

**Comment by Geniucker** [comment]
By the way, if the `base_url` is `http://127.0.0.1:8080/v1/`, it will send request to `http://127.0.0.1:8080/v1/completions`, which is not implemented in this project, which will cause 4xx status. Theoretically, it should give "Not Found" instread of "Method Not Allowed". https://github.com/aaamoon/copilot-gpt4-service/blob/59efa6239f304fd8e625bf61f0bd058c40fc8b82/main.go#L307
I think this should be modified

**Comment by funnyzak** [comment]
> By the way, if the `base_url` is `http://127.0.0.1:8080/v1/`, it will send request to `http://127.0.0.1:8080/v1/completions`, which is not implemented in this project, which will cause 4xx status. Theoretically, it should give "Not Found" instread of "Method Not Allowed".
> 
> https://github.com/aaamoon/copilot-gpt4-service/blob/59efa6239f304fd8e625bf61f0bd058c40fc8b82/main.go#L307
> 
> 
> I think this should be modified. @funnyzak @aaamoon what do you think?

You are absolutely correct that the 404 was not found with the appropriate response. It should be modified.

**Comment by funnyzak** [comment]
The service has been updated and the NoRoute response has been changed to 404 not found.
