### ISSUE TITLE
关于个人操作流程的问题

### ISSUE THREAD

**Issue by SSSayon** [aaamoon/copilot-gpt4-service#217]
我完全是个 newbie，现在 gpt4 已经能正常问询了，想问一下我的操作过程是否正确：
平台：Windows 11
1. 安装 NextChat (从它 repo 的 release 那)
2. 从这个 repo 的 actions 直接下了 build 好的服务端(?)
3. 通过 Python 脚本得到 token
4. 对应填入，开始使用 gpt4

另外还有一点，我在浏览其它 issue 的时候看到了很多安全性的问题，请问我现在的流程安全吗？如果有时候挂着代理使用，这是否会带来风险？

提前感谢！

**Comment by aaamoon** [comment]
这样应该是没有风险的

**Comment by two-tigger** [comment]
请问为啥我的.bat执行一次失败以后就无法再次启动了，题主部署成功了吗？
