### ISSUE TITLE
获取token填入chatbox报错，我不知道是不是api域名填的有问题

### ISSUE THREAD

**Issue by aksjbdka** [aaamoon/copilot-gpt4-service#220]
### Description

我是mac端，用python获取三个token填入后都不可以，设置和报错如下
![CleanShot 2024-01-21 at 13 52 15@2x](https://github.com/aaamoon/copilot-gpt4-service/assets/139043817/c17c2794-9300-48fa-aa09-db01af0d78a0)
![CleanShot 2024-01-21 at 13 55 01@2x](https://github.com/aaamoon/copilot-gpt4-service/assets/139043817/85879d49-034a-41cb-880d-b079dc23f129)

**Comment by funnyzak** [comment]
看配置链接格式没有问题，从以下几个方面看看：

1. 确认开通 Github Copilot 服务。
2. 确认 copilot-gpt-service 启动，并本地监听 7890 端口。
3. 如果为容器启动，确认下 HOST 设置为 0.0.0.0。

**Comment by aksjbdka** [comment]
ok啦，我没有启动copilotgpt4服务，启动了之后就好了，谢谢您🙏
