### ISSUE TITLE
How to query a response via HTTP requests?

### ISSUE THREAD

**Issue by smjure** [aaamoon/copilot-gpt4-service#227]
First of all, thank you for the great tool, works very well :+1: 

I'm trying to get a response via HTTP request within a golang code (similar what nextChat does but via own Go code). I tried it with the following [snippet](https://github.com/sashabaranov/go-openai/issues/513#issuecomment-1851585302) where you can provide API endpoint and token and also tried it via "net/http" package in Go, but not working (probably couldn't expect it to work). How can I get response from `http://127.0.0.1:8080/` via HTTP request or perhaps there's a REST API? Thank you 🙏

**Comment by aaamoon** [comment]
The following might be an example:
```
package main

import (
	"bytes"
	"encoding/json"
	"log"
	"net/http"
)

type Message struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type RequestData struct {
	Model    string    `json:"model"`
	Messages []Message `json:"messages"`
}

func main() {
	url := "http://127.0.0.1:8080/v1/chat/completions"

	data := RequestData{
		Model: "gpt-4",
		Messages: []Message{
			{
				Role:    "user",
				Content: "hello",
			},
		},
	}

	jsonData, err := json.Marshal(data)
	if err != nil {
		log.Fatal(err)
	}

	req, err := http.NewRequest("POST", url, bytes.NewBuffer(jsonData))
	if err != nil {
		log.Fatal(err)
	}

	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer ghu_xx")

	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		log.Fatal(err)
	}
	defer resp.Body.Close()

	log.Println("Response status:", resp.Status)
}
```

**Comment by smjure** [comment]
Works like a charm, thank you :bow: 🙏

祝你好运

**Comment by aaamoon** [comment]
@petric3 Are there any error messages?

**Comment by petric3** [comment]
I get standard response on `localhost:8080`, otherwise all works fine using github token and localhost on NextChat, so your API works fine on my comp.
```
2024/02/29 07:55:52 Response status: 200 OK
2024/02/29 07:55:54 Response body: 非常重要：请不要将此服务公开，仅供个人使用，否则账户或 Copilot 将被封禁。Very important: please do not make this service public, for personal use only, otherwise the account or Copilot will be banned. 非常に重要：このサービスを公開しないでください、個人使用のみにしてください。そうしないと、アカウントまたは Copilot が禁止されます。
```
