### ISSUE TITLE
Warn the "gpt-4" not found

### ISSUE THREAD

**Issue by YutaoChow** [aaamoon/copilot-gpt4-service#230]
https://github.com/aaamoon/copilot-gpt4-service/blob/6b352d957af18863f8f2f7da7422c8caea5d53d8/main.go#L139

When I use the postman mock the request,and the model param is "gpt-4",it returns the error,and the "gpt-3.5-turbo" is normal。

<img width="604" alt="image" src="https://github.com/aaamoon/copilot-gpt4-service/assets/20595456/aff5ce29-2192-4c60-a05f-e954aad82386">

**Comment by aaamoon** [comment]
There may be an issue with requesting headers.

**Comment by YutaoChow** [comment]
Thanks,I check the code and found that use the wrong request url `https://copilot-proxy.githubusercontent.com/v1/chat/completions`.
It should be `https://api.githubcopilot.com/chat/completions`.
