### ISSUE TITLE
Start Output not respect the host config.

### ISSUE THREAD

**Issue by Zxilly** [aaamoon/copilot-gpt4-service#235]
### Description

https://github.com/aaamoon/copilot-gpt4-service/blob/83a6ccc51f147c8e891122e2c871becf09ceca32/main.go#L306-L321

This function should only print all ip if the host was set to `0.0.0.0`.

Currently, it will print all ip on the machine even the host was set `127.0.0.1`, which make user confusing.

![image](https://github.com/aaamoon/copilot-gpt4-service/assets/31370133/ea721ced-d0e0-4873-aaae-fcc7d27784a6)

**Comment by Zxilly** [comment]
Also， The default end point in the code is 0.0.0.0， But it in the readme is 127.0.0.1

**Comment by aaamoon** [comment]
@Zxilly It would be nice if could modify the README in that PR as well.

**Comment by Zxilly** [comment]
@aaamoon Which one should be selected as default? `127.0.0.1` or `0.0.0.0`?
