### ISSUE TITLE
似乎该接口没有审查？是所有第三方接口都这样吗

### ISSUE THREAD

**Issue by Rlxzmdd** [aaamoon/copilot-gpt4-service#237]
### Description

比官网的web更容易瑟瑟，但好像也比第三方输出力度大很多。

### Why

/

### Alternatives

/

**Comment by Geniucker** [comment]
有审查，但是在 stream=true 的情况下，有审查会直接返回空内容，我们不太好处理这种情况
stream=false 的情况下，会返回 422 状态码
