### ISSUE TITLE
同样遇到了空白信息的问题

### ISSUE THREAD

**Issue by demi2912** [aaamoon/copilot-gpt4-service#24]
当我重新试图申请那个API key的时候

Get device code failed
Please make sure you entered the information correctly.

我无法再进入那个页面了

**Comment by demi2912** [comment]
![1704440161424](https://github.com/aaamoon/copilot-gpt4-service/assets/92431211/5384e1c2-f34e-4ce2-921f-4febee357a59)
也就是变成这样

**Comment by aaamoon** [comment]
获取 Github Copilot Plugin Token 的页面是第三方维护的，建议过一会再重新试下获取

**Comment by aaamoon** [comment]
刚刚应该是请求量太大，那个页面某些请求挂掉了，现在看起来已经恢复
