### ISSUE TITLE
部署在国内阿里云 Windows 机器后，通过 vercel 站点发起的请求，无法使用流式传输

### ISSUE THREAD

**Issue by sheng-di** [aaamoon/copilot-gpt4-service#243]
### Description

问题：
> 部署在国内阿里云 Windows 机器后，通过 vercel 站点发起的请求，无法使用流式传输

将 https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web 部署后，直接通过 `域名+端口号`的方式请求该服务，前端返回的结果总是无法流式传输，最终 response 回来后会一并输出。

测试发现：
1. 阿里云后端 + vercel 前端，不支持流式传输。
2. 本地部署后端 + next chat 的本地客户端，支持流式传输。

怀疑是 content-type 的问题，br、gzip 之类的，不过还没搞明白为何。
对应的 next chat issue 链接：https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/3848
---
After deploying the project https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web on an Alibaba Cloud Windows machine in China, it seems that requests initiated from a Vercel site are unable to utilize streaming responses. When accessing the service directly via domain+port number, the frontend does not stream the response but instead outputs everything all at once when the response finally arrives.

Through testing, I found that:

Backend on Alibaba Cloud + Vercel frontend does not support streaming responses.
Local backend deployment + local Next Chat client does support streaming responses.
I suspect this might be an issue with the content-type, possibly related to br, gzip, or similar, but I have not been able to determine the exact cause. Here is the corresponding issue on Next Chat: https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/3848

Any assistance in resolving this issue would be greatly appreciated.

**Comment by aaamoon** [comment]
看起来这是ChatGPT-Next-Web的问题吧

**Comment by sheng-di** [comment]
> 看起来这是ChatGPT-Next-Web的问题吧

也有可能是 copilot 和 openai 接口的 content type encoding 之类的不一样，next chat 那个用 openai 后端可以流式。。

**Comment by sheng-di** [comment]
Update: 部署的 lobe-chat 也有这个问题。

**Comment by Geniucker** [comment]
我在azure试试

**Comment by Geniucker** [comment]
放一组返回的Header供对比

OpenAI:
```
{
    "Date": "Mon, 29 Jan 2024 09:30:32 GMT",
    "Content-Type": "text/event-stream",
    "Transfer-Encoding": "chunked",
    "Connection": "keep-alive",
    "access-control-allow-origin": "*",
    "Cache-Control": "no-cache, must-revalidate",
    "openai-model": "gpt-3.5-turbo-0613",
    "openai-organization": "user-4m647qnc60r4pdbrsc6a8fn1",
    "openai-processing-ms": "461",
    "openai-version": "2020-10-01",
    "strict-transport-security": "max-age=15724800; includeSubDomains",
    "x-ratelimit-limit-requests": "200",
    "x-ratelimit-limit-tokens": "40000",
    "x-ratelimit-remaining-requests": "199",
    "x-ratelimit-remaining-tokens": "39981",
    "x-ratelimit-reset-requests": "7m12s",
    "x-ratelimit-reset-tokens": "28ms",
    "x-request-id": "1daf0a85112a0c11bd38867b689c20ac",
    "CF-Cache-Status": "DYNAMIC",
    "Set-Cookie": "__cf_bm=11v0Y4kuA0dcKULmKUlY97yOmlXzRfflOC2Q55yGgRA-1706520632-1-ARtb1Up928E3S8soUgGHOuVRpqMYiGg0dxFJO7kmk0nOBLRZGd20blK53vC1xjv89Fszmnu9dE4TdbcswDp0VpM=; path=/; expires=Mon, 29-Jan-24 10:00:32 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=hmwijNqIIkMmjB_5DOk9gnuNt0DM5t2aJTJ5nmh7Z.U-1706520632030-0-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None",
    "Server": "cloudflare",
    "CF-RAY": "84d074f8ae3adb59-LAX",
    "alt-svc": "h3=\":443\"; ma=86400"
}
```

本项目:
```
{
    "Connection": "close",
    "Transfer-Encoding": "chunked",
    "Access-Control-Allow-Credentials": "true",
    "Access-Control-Allow-Headers": "*",
    "Access-Control-Allow-Methods": "*",
    "Access-Control-Allow-Origin": "*",
    "Cache-Control": "no-cache",
    "Content-Type": "text/event-stream; charset=utf-8",
    "Date": "Mon, 29 Jan 2024 09:35:49 GMT",
    "X-Accel-Buffering": "no"
}
```

**Comment by Geniucker** [comment]
update: 我使用vercel部署的chatgptnext 也能流式传输，不会是你的反代有问题吧

**Comment by Geniucker** [comment]
添加环境变量，还是可以流式传输
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/61449208/cf0b4a53-2674-4be4-a2e2-abfeb31356fa)

**Comment by sheng-di** [comment]
> 添加环境变量，还是可以流式传输
> 
> ![image](https://github.com/aaamoon/copilot-gpt4-service/assets/61449208/cf0b4a53-2674-4be4-a2e2-abfeb31356fa)
> 
> 

奇怪了。。。我也去试试 caddy 代吧。。一开始是 iis 的反代不支持流式传输，就采用了直接通过 vercel 服务端请求端口的方式。我推测原因可能如下：
- vercel 服务端请求 http 端口时，可能会修改响应。
- Caddy 可能具有修正 response 的功能。

具体的原因可能还得再排查。

**Comment by Geniucker** [comment]
你让他给出很长的回答也会一口气出来吗

**Comment by sheng-di** [comment]
> 你让他给出很长的回答也会一口气出来吗

是的，会一口气出来。

**Comment by funnyzak** [comment]
阿里云debian部署service，并配置反代 https。Vercel部署nextchat-web，通过vercel api请求可以流式输出。

是不是你的反代有问题？或者是服务器有什么安全设置，如Web云防火墙、云防火墙什么的。

**Comment by sheng-di** [comment]
> 阿里云debian部署service，并配置反代 https。Vercel部署nextchat-web，通过vercel api请求可以流式输出。
> 
> 
> 
> 是不是你的反代有问题？或者是服务器有什么安全设置，如Web云防火墙、云防火墙什么的。

我是通过 go build 出来一个 exe，然后直接启动它，暴露一个8080 端口。
然后 vercel 部署 next chat，api base 填写这个 http 的 8080 端口的地址，key 就写 token。

按理说这样的流程应该只有 vercel 的服务端有坑。。

**Comment by funnyzak** [comment]
> > 阿里云debian部署service，并配置反代 https。Vercel部署nextchat-web，通过vercel api请求可以流式输出。
> > 是不是你的反代有问题？或者是服务器有什么安全设置，如Web云防火墙、云防火墙什么的。
> 
> 我是通过 go build 出来一个 exe，然后直接启动它，暴露一个8080 端口。 然后 vercel 部署 next chat，api base 填写这个 http 的 8080 端口的地址，key 就写 token。
> 
> 按理说这样的流程应该只有 vercel 的服务端有坑。。

有这种可能性。 可能是中间服务给修改响应了，具体还得进一步排查。

**Comment by sheng-di** [comment]
Update: 同样的 windows 系统，同样的 exe 部署 8080，通过 nginx 反向代理，添加 SSL 证书变成 https。
在网页上设置 https 的接口地址，通过浏览器发起请求，可以流式传输。

**Comment by sheng-di** [comment]
Update: 同样，修改为 https 后，在 vercel 后端发起的请求也可以支持流式传输了。

因此，这个问题总结为，推测是 http 传输时，有不明的中间人有能力去篡改（修改、影响、干扰）请求的传输。
