### ISSUE TITLE
本地启动模式 + Nextchat 工具 ， 404 问题

### ISSUE THREAD

**Issue by freeozyl80** [aaamoon/copilot-gpt4-service#246]
### Description

# 启动方式： 本地启动：
```shell
└─[$]> go run .

Copilot-GPT4-Service startup configuration:
 - Port                : 8080
 - Cache               : true
 - CachePath           : db/cache.sqlite3
 - Host                : 0.0.0.0
 - Debug               : false
 - Logging             : false
 - LogLevel            : info
 - CopilotToken        :
 - CORSProxyNextChat   : false
 - RateLimit           : 0

Service is running at:
 - Local               : http://0.0.0.0:8080
 - Network             : http://127.0.0.1:8080
 - Network             : http://10.2.76.175:8080
 (Press CTRL+C to quit)

 警告：请不要将此服务公开，仅供个人使用，否则账户或 Copilot 将被封禁。
 Warning: Please do not make this service public, for personal use only, otherwise the account or Copilot will be banned.
 警告：このサービスを公開しないでください、個人使用のみにしてください。そうしないと、アカウントまたは Copilot が禁止されます。

[GIN] 2024/01/29 - 14:27:30 | 200 |      81.815µs |       127.0.0.1 | OPTIONS  "/v1/chat/completions"
[GIN] 2024/01/29 - 14:27:30 | 404 |  656.663168ms |       127.0.0.1 | POST     "/v1/chat/completions"
[GIN] 2024/01/29 - 14:27:31 | 404 |  362.859238ms |       127.0.0.1 | POST     "/v1/chat/completions"
```

**Comment by freeozyl80** [comment]
发送语句后：
{
  "code": 404,
  "error": "{\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest\"}"
}

**Comment by freeozyl80** [comment]
curl --location 'http://127.0.0.1:8080/v1/chat/completions' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer gho_xxxxx' \
--data '{
  "model": "gpt-4",
  "messages": [ {"role": "user", "content": "hello"}]
}'
{"code":404,"error":"{\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest\"}"}%

**Comment by aaamoon** [comment]
@funnyzak @Geniucker 我这边复现不了404的返回码，你们能复现么

**Comment by Geniucker** [comment]
@freeozyl80 能不能说一下用的哪个版本，如果是docker的话最好给一下哈希

**Comment by Geniucker** [comment]
我地方master分支无法复现

**Comment by freeozyl80** [comment]
版本： 4f9b3f0 ； 
log： 打开了；

ps: 会不会是Token不对，我是通过 gh auth token 获取的 token



Copilot-GPT4-Service startup configuration:
 - Port                : 8080
 - Cache               : true
 - CachePath           : db/cache.sqlite3
 - Host                : 0.0.0.0
 - Debug               : false
 - Logging             : true
 - LogLevel            : info
 - CopilotToken        :
 - CORSProxyNextChat   : true
 - RateLimit           : 0
 - EnableSuperToken    : false
 - SuperToken          :

Service is running at:
 - Local               : http://0.0.0.0:8080
 - Network             : http://127.0.0.1:8080
 - Network             : http://10.2.76.175:8080
(Press CTRL+C to quit)

 WARNING: CORS_PROXY_NEXTCHAT is enabled. This is a potential security risk if your service is not private.

 Warning: Please do not make this service public, for personal use only, otherwise the account or Copilot will be banned.
 警告：请不要将此服务公开，仅供个人使用，否则账户或 Copilot 将被封禁。

2024-01-29 17:30:01 INF Request Info:
Method: POST
Host: 127.0.0.1:8080
URL: /v1/chat/completions
2024-01-29 17:30:01 INF Response Time: 670.317181ms
Status: 404
[GIN] 2024/01/29 - 17:30:01 | 404 |  670.715077ms |       127.0.0.1 | POST     "/v1/chat/completions"

**Comment by aaamoon** [comment]
@freeozyl80 需要的token不是auth token，可以按照以下方法去获取token：
https://github.com/aaamoon/copilot-gpt4-service/blob/master/README_CN.md#%E8%8E%B7%E5%8F%96-copilot-token

**Comment by Geniucker** [comment]
那说的通了，这个404应该是github回的
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/61449208/cbaffc0a-98ed-4af6-bb71-4c961fd56dbd)

**Comment by freeozyl80** [comment]
3q 各位
