### ISSUE TITLE
申请了token也输入了但是不能回答问题

### ISSUE THREAD

**Issue by guochenchn** [aaamoon/copilot-gpt4-service#25]
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/12546392/8a4a3e69-e6c5-4b88-bd12-14591c14df60)
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/12546392/1d631979-fe23-4be3-81f5-4e71b896be87)

**Comment by aaamoon** [comment]
服务端已更新对错误信息的更好展示：
401: 使用的 Github Copilot Plugin Token 过期了或者错误，请重新获取
403: 使用的账号没有开通 Github Copilot
