### ISSUE TITLE
使用stream true 时，请求偶尔会出现乱码

### ISSUE THREAD

**Issue by zhengzhanpeng** [aaamoon/copilot-gpt4-service#251]
### Description

![WechatIMG28](https://github.com/aaamoon/copilot-gpt4-service/assets/29090726/579b3aea-5966-4011-87d4-4a3fb348eac5)
如图，会出现这种乱码现象，不知道是什么原因

**Comment by Geniucker** [comment]
请问使用的是最新版的吗，我在很老的版本使用bettergpt的时候遇到过这个问题

**Comment by sheng-di** [comment]
这个 agent 是什么软件？

**Comment by Geniucker** [comment]
有条件的话能不能抓包看看相应正不正常，因为之前我在用bettergpt的时候网页出现乱码，但是抓包看响应体是没有乱码的我也不知道具体的原因。如果不方便抓包的话能不能提供复现的方法
