### ISSUE TITLE
方法照着做了，且账号也开通了copilot，使用curl发送命令可以得到回复，但是用NextChat报错

### ISSUE THREAD

**Issue by gbzero** [aaamoon/copilot-gpt4-service#252]
具体操作如下：
1. 根据教程，在nas服务器上开启一个docker，端口号为7892；
2. 使用如下命令可以得到回复：
```shell
curl --location 'http://127.0.0.1:7892/v1/chat/completions' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer ghu_xxx' \
--data '{
  "model": "gpt-4",
  "messages": [ {"role": "user", "content": "hello"}]
}'
```
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/158181994/763fff60-050e-4cbb-ad85-3bd3f4a41a20)
3. 使用NextChat客户端，配置为：接口地址：http://192.168.3.15:7892/v1/chat/completions + ghu_xxx，聊天界面的回复如下：
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/158181994/619cccf7-b819-4bed-97eb-b1b39091bc4a)
请大佬指点一下，十分感谢！！！

**Comment by gbzero** [comment]
> 你写接口地址的时候，带上了路径？！
> 
> 应该是：`http://192.168.3.15:7892`

我也试过不带路径，也是一样的结果。

**Comment by funnyzak** [comment]
> > 你写接口地址的时候，带上了路径？！
> > 应该是：`http://192.168.3.15:7892`
> 
> 我也试过不带路径，也是一样的结果。

看看7892服务日志，有没有request。

**Comment by gbzero** [comment]
> > > 你写接口地址的时候，带上了路径？！
> > > 应该是：`http://192.168.3.15:7892`
> > 
> > 
> > 我也试过不带路径，也是一样的结果。
> 
> 看看7892服务日志，有没有request。 可能是 NextChat 的问题，类似跨域什么的，请求被 blocked。

通过NextChat发送消息时，服务器上没有日志；使用curl发消息时服务器有日志

**Comment by funnyzak** [comment]
1. 确定启动 Service 时，配置 **HOST** 为 `0.0.0.0`；
2. 确定 `http://192.168.3.15:7892` 是否正常访问；
3. 确定 nextchat 设置的api路径为：`http://192.168.3.15:7892`；

**Comment by gbzero** [comment]
> 1. 确定启动 Service 时，配置 **HOST** 为 `0.0.0.0`；
> 2. 确定 `http://192.168.3.15:7892` 是否正常访问；
> 3. 确定 nextchat 设置的api路径为：`http://192.168.3.15:7892`；

是正常访问的。目前问题已经解决了，虽然不知道原因是什么，但是我可以说一下我的解决方法：

**Comment by funnyzak** [comment]
> > 1. 确定启动 Service 时，配置 **HOST** 为 `0.0.0.0`；
> > 2. 确定 `http://192.168.3.15:7892` 是否正常访问；
> > 3. 确定 nextchat 设置的api路径为：`http://192.168.3.15:7892`；
> 
> 是正常访问的。目前问题已经解决了，虽然不知道原因是什么，但是我可以说一下我的解决方法：
> 
> 1. 在nas上部署NextChat的docker（与copilot-gpt4-service服务在同一nas上）；
> 2. 局域网连接nas上部署的NextChat服务（网页版NextChat），然后填上api路径`http://192.168.3.15:7892`与token，问题解决
>    ![image](https://private-user-images.githubusercontent.com/158181994/301175342-44ecb1fa-3f09-4cc9-91ce-9df797f3eafb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MTA3OTAsIm5iZiI6MTcwNjcxMDQ5MCwicGF0aCI6Ii8xNTgxODE5OTQvMzAxMTc1MzQyLTQ0ZWNiMWZhLTNmMDktNGNjOS05MWNlLTlkZjc5N2YzZWFmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMVQxNDE0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODhjODYwNzE0NWRmNDE5MGMzM2I2NmVkZDVlZmU2NGVlNDZhYmJmZDA4YWUxYjM0M2YzZGFhM2I1MTFkZjg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.A9c6I_Il5-B4UhB9Zdqpj1Rae6oWQySzTld_NadFR6Q)
> 
> 非常感谢大佬的帮助！！还请大佬能帮忙解答一下原因

我以为你的场景是本地 桌面版 NextChat 配置 api 地址。 

你两个服务是对应两个端口吗？觉得之前可能还是跨域的问题？！浏览器因为域的问题block了请求，然后后续你无意中设置了浏览器的对应cors设置？！

**Comment by Geniucker** [comment]
但是我们不是已经在响应头里面添加了CORS相关的内容了吗（不是很懂跨域

**Comment by gbzero** [comment]
> > > 1. 确定启动 Service 时，配置 **HOST** 为 `0.0.0.0`；
> > > 2. 确定 `http://192.168.3.15:7892` 是否正常访问；
> > > 3. 确定 nextchat 设置的api路径为：`http://192.168.3.15:7892`；
> > 
> > 
> > 是正常访问的。目前问题已经解决了，虽然不知道原因是什么，但是我可以说一下我的解决方法：
> > 
> > 1. 在nas上部署NextChat的docker（与copilot-gpt4-service服务在同一nas上）；
> > 2. 局域网连接nas上部署的NextChat服务（网页版NextChat），然后填上api路径`http://192.168.3.15:7892`与token，问题解决
> >    ![image](https://private-user-images.githubusercontent.com/158181994/301175342-44ecb1fa-3f09-4cc9-91ce-9df797f3eafb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MTA3OTAsIm5iZiI6MTcwNjcxMDQ5MCwicGF0aCI6Ii8xNTgxODE5OTQvMzAxMTc1MzQyLTQ0ZWNiMWZhLTNmMDktNGNjOS05MWNlLTlkZjc5N2YzZWFmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMVQxNDE0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODhjODYwNzE0NWRmNDE5MGMzM2I2NmVkZDVlZmU2NGVlNDZhYmJmZDA4YWUxYjM0M2YzZGFhM2I1MTFkZjg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.A9c6I_Il5-B4UhB9Zdqpj1Rae6oWQySzTld_NadFR6Q)
> > 
> > 非常感谢大佬的帮助！！还请大佬能帮忙解答一下原因
> 
> 我以为你的场景是本地 桌面版 NextChat 配置 api 地址。
> 
> 你两个服务是对应两个端口吗？觉得之前可能还是跨域的问题？！浏览器因为域的问题block了请求，然后后续你无意中设置了浏览器的对应cors设置？！

copilot-gpt4-service服务的端口是7892，NextChat的端口是3000，两个服务的IP都是192.168.3.15，我应该没有设置过cors（我也不清楚怎么设置>_<），在进行本地部署NextChat服务前我还尝试过使用NextChat官方搭建的网页版app，但是跟客户端是一样的结果（提示error）。

**Comment by funnyzak** [comment]
后续搭建一样场景，验证一下。

目前也是推测，不太确定😄

**Comment by funnyzak** [comment]
> > > > 1. 确定启动 Service 时，配置 **HOST** 为 `0.0.0.0`；
> > > > 2. 确定 `http://192.168.3.15:7892` 是否正常访问；
> > > > 3. 确定 nextchat 设置的api路径为：`http://192.168.3.15:7892`；
> > > 
> > > 
> > > 是正常访问的。目前问题已经解决了，虽然不知道原因是什么，但是我可以说一下我的解决方法：
> > > 
> > > 1. 在nas上部署NextChat的docker（与copilot-gpt4-service服务在同一nas上）；
> > > 2. 局域网连接nas上部署的NextChat服务（网页版NextChat），然后填上api路径`http://192.168.3.15:7892`与token，问题解决
> > >    ![image](https://private-user-images.githubusercontent.com/158181994/301175342-44ecb1fa-3f09-4cc9-91ce-9df797f3eafb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MTA3OTAsIm5iZiI6MTcwNjcxMDQ5MCwicGF0aCI6Ii8xNTgxODE5OTQvMzAxMTc1MzQyLTQ0ZWNiMWZhLTNmMDktNGNjOS05MWNlLTlkZjc5N2YzZWFmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMVQxNDE0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODhjODYwNzE0NWRmNDE5MGMzM2I2NmVkZDVlZmU2NGVlNDZhYmJmZDA4YWUxYjM0M2YzZGFhM2I1MTFkZjg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.A9c6I_Il5-B4UhB9Zdqpj1Rae6oWQySzTld_NadFR6Q)
> > > 
> > > 非常感谢大佬的帮助！！还请大佬能帮忙解答一下原因
> > 
> > 
> > 我以为你的场景是本地 桌面版 NextChat 配置 api 地址。
> > 你两个服务是对应两个端口吗？觉得之前可能还是跨域的问题？！浏览器因为域的问题block了请求，然后后续你无意中设置了浏览器的对应cors设置？！
> 
> copilot-gpt4-service服务的端口是7892，NextChat的端口是3000，两个服务的IP都是192.168.3.15，我应该没有设置过cors（我也不清楚怎么设置>_<），在进行本地部署NextChat服务前我还尝试过使用NextChat官方搭建的网页版app，但是跟客户端是一样的结果（提示error）。

官方搭建的应该是https吧，https里应该不能有http。

你的场景是：
1. NextChatWeb 地址为：http://192.168.3.15:3000
2. CopilotGpt4Server 地址为：http://192.168.3.15:7892
3. 然后在 NextChatWeb 网页前端设置 OPEN API地址为 http://192.168.3.15:7892，并设置 Token。
4. 然后使用，发现如上问题。

你看我描述对不？

**Comment by ParaN3xus** [comment]
这是nextchatweb的问题
