### ISSUE TITLE
无法获得token

### ISSUE THREAD

**Issue by xiaopaul** [aaamoon/copilot-gpt4-service#253]
### Description

我在Mac上尝试获得token，也已经在Github上启用了copilot的extension，但是还是链接不上，显示connection refused，请教怎么解决，谢谢。

$ bash -c "$(curl -fsSL https://raw.githubusercontent.com/aaamoon/copilot-gpt4-service/master/shells/get_copilot_token.sh)"
curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused

**Comment by aaamoon** [comment]
443应该是网络原因访问不到github接口服务，获取Token一共有三种推荐方式，可以试试另外两种

**Comment by funnyzak** [comment]
如何已经按照 VS Code 的 Copilot插件，试着如下命令：

**Comment by Geniucker** [comment]
> 如何已经安装 VS Code 的 Copilot插件，试着如下命令：
> 
> ```shell
> cat ~/.copilot-cli-access-token
> ```

这应该是copilot-cli的吧

**Comment by funnyzak** [comment]
> > 如何已经安装 VS Code 的 Copilot插件，试着如下命令：
> > ```shell
> > cat ~/.copilot-cli-access-token
> > ```
> 
> 这应该是copilot-cli的吧

搞错了😄

**Comment by funnyzak** [comment]
1. 你如果clone项目到本地，可以从 shells 文件夹看到 **get_copilot_token.sh** 脚本文件。
2. 在项目目录下，运行 `chmod +x ./shells/get_copilot_token.sh && bash ./shells/get_copilot_token.sh`
3. 然后根据提示，选择对应的方式获取token。
   <img width="454" alt="image" src="https://github.com/aaamoon/copilot-gpt4-service/assets/2562087/4413c1be-ffb3-425a-a592-a33f30b3fe0a">

**Comment by Trade-Offf** [comment]
我整理了一遍mac的使用流程，希望有帮助：https://juejin.cn/post/7329433979806908450

**Comment by Geniucker** [comment]
网络问题，你可能需要使用代理
