### ISSUE TITLE
简介中关于如何区分模型是不是gpt-4的办法太绕了

### ISSUE THREAD

**Issue by tangmingxing1988** [aaamoon/copilot-gpt4-service#254]
### Description

简介中关于如何区分模型是不是gpt-4，是询问为什么没有参加父母的婚礼。这个方法既不精确，又曲折不明，事实上，完全可以直接问他什么模型，数据库截止时间，gpt会直接回复。

### Why

我截图展示了官方的gpt-3.5和gpt-4，以及本项目的回复，都非常清晰的回复了模型。
![IMG_1172](https://github.com/aaamoon/copilot-gpt4-service/assets/2328380/2713d07f-a3f2-4cc4-849d-65aff7197b7e)
![IMG_1173](https://github.com/aaamoon/copilot-gpt4-service/assets/2328380/6f9962dc-3e54-4b9f-90c5-80100494eb7e)
![IMG_1174](https://github.com/aaamoon/copilot-gpt4-service/assets/2328380/a5339165-7ea7-4721-8998-b6ab953b9339)

### Alternatives

请将这个方法修改为，询问“ 我想知道你是什么模型，截止时间什么时候？”。

**Comment by aaamoon** [comment]
如果选择的是 gpt-4-32k-0613 模型，它回答自己是 gpt-4-32k-0613 模型，实际上这是 GPT-3.5-turbo 模型，因为 Github Copilot 只支持 GPT-4 和 GPT-3.5-turbo模型
<img width="1134" alt="image" src="https://github.com/aaamoon/copilot-gpt4-service/assets/25700476/63c31692-fda4-4d53-9c0c-611250dd7d81">

**Comment by ihategfw** [comment]
ChatGPT Next Web 选用 GPT4 模型的时候，内置了一个prompt，会暗示他的模型是GPT4

```json
{
    "messages": [
        {
            "role": "system",
            "content": "\nYou are ChatGPT, a large language model trained by OpenAI.\nKnowledge cutoff: 2021-09\nCurrent model: gpt-4\nCurrent time: 1/31/2024, 12:15:52 PM\nLatex inline: $x^2$ \nLatex block: $$e=mc^2$$\n\n"
        },
        {
            "role": "user",
            "content": "Hello"
        }
    ],
    "stream": true,
    "model": "gpt-4",
    "temperature": 0.5,
    "presence_penalty": 0,
    "frequency_penalty": 0,
    "top_p": 1
}
```
