### ISSUE TITLE
Encountering an error when sending the request.

### ISSUE THREAD

**Issue by thelege2nd** [aaamoon/copilot-gpt4-service#255]
Hi, I am getting an error when I try to chat with AI using Chatbox app while requests are being decrypted. 

![image](https://github.com/aaamoon/copilot-gpt4-service/assets/12984941/1722cbf2-9c9b-4cbc-b4bc-4d49af132cbf)

I am using Fiddler to decrypt all HTTPS traffic requests on my PC and I have included the following hosts to be skipped from deycrption, bt I'm still getting the error when sending the requests.

![image](https://github.com/aaamoon/copilot-gpt4-service/assets/12984941/a0334bc1-987b-4445-824e-f4d10929428a)

Is there any other hosts I should include so the requests can pass?

**Comment by funnyzak** [comment]
Try adding `api.githubcopilot.com` to the skip list!
