### ISSUE TITLE
最新的镜像部署后chatnext无法显示回复

### ISSUE THREAD

**Issue by fyl080801** [aaamoon/copilot-gpt4-service#259]
### Description

拉取最新镜像后在chatnext发消息，有chatnext和copilot-gpt4-service的日志也显示请求成功，但是请求没有返回任何结果

**Comment by fyl080801** [comment]
使用其他客户端也是同样的现象

**Comment by Geniucker** [comment]
你试试bettergpt是不是一样的现象

**Comment by Geniucker** [comment]
用curl请求一下看一下结果
```bash
curl 你的API地址/v1/chat/completions  \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer 你的token" \
  -d '{
     "model": "gpt-3.5-turbo",
     "messages": [{"role": "user", "content": "Say this is a test!"}],
     "temperature": 0.7,
     "stream": true
}'
```

**Comment by fyl080801** [comment]
> 用curl请求一下看一下结果
> 
> ```shell
> curl 你的API地址/v1/chat/completions  \
>   -H "Content-Type: application/json" \
>   -H "Authorization: Bearer 你的token" \
>   -d '{
>      "model": "gpt-3.5-turbo",
>      "messages": [{"role": "user", "content": "Say this is a test!"}],
>      "temperature": 0.7,
>      "stream": true
> }'
> ```

什么也没有返回

**Comment by fyl080801** [comment]
目前来看镜像版本 `[714abd0](https://hub.docker.com/layers/aaamoon/copilot-gpt4-service/714abd0/images/sha256-9eecc48ce8223706b9a942e39d3e4c640447943becb0f9679e43b3c1889e8638?context=explore)` 是正常的，之后的版本都存在这个问题

**Comment by funnyzak** [comment]
> > 用curl请求一下看一下结果
> > ```shell
> > curl 你的API地址/v1/chat/completions  \
> >   -H "Content-Type: application/json" \
> >   -H "Authorization: Bearer 你的token" \
> >   -d '{
> >      "model": "gpt-3.5-turbo",
> >      "messages": [{"role": "user", "content": "Say this is a test!"}],
> >      "temperature": 0.7,
> >      "stream": true
> > }'
> > ```
> 
> 什么也没有返回

我当前就是最新镜像容器，没发现问题。

你重新拉取最新镜像， 然后程序 LOG_LEVEL 设置为 debug, 通过日志 debug 输出看看。

**Comment by aaamoon** [comment]
我这边试了下最新镜像容器，也是正常运行的

**Comment by fyl080801** [comment]
> 我这边试了下最新镜像容器，也是正常运行的

我发现规律了，如果CACHE设置true就是正常的，之前都是false

**Comment by funnyzak** [comment]
> > 我这边试了下最新镜像容器，也是正常运行的
> 
> 我发现规律了，如果CACHE设置true就是正常的，之前都是false，日志：
> 
> ```
> 2024-02-04T08:28:02.200969766-08:00
> 2024-02-04 16:28:37 INF Request Info:
> Method: POST
> Host: copilot-gpt4.apps.svc:8080
> URL: /v1/chat/completions?path=v1&path=chat&path=completions
> 2024-02-04 16:28:37 DBG Request Header:
> map[Accept:[*/*] Accept-Encoding:[gzip, deflate] Accept-Language:[*] Authorization:[Bearer <token>] Cache-Control:[no-store] Connection:[keep-alive] Content-Type:[application/json] Sec-Fetch-Mode:[cors] User-Agent:[Next.js Middleware] X-Middleware-Subrequest:[app/api/openai/[...path]/route]]
> 2024-02-04 16:28:37 DBG Get GithubCopilot Authorization Token Success, Token: tid=83bda32e8a7518f58a6ae35c1c030523;exp=1707065917;sku=trial_30_monthly_subscriber;st=dotcom;chat=1;8kp=1:76a7b24939175cc3943fea0981df4f68686201ee39583d097fe7246eb393c1e0, ExpiresAt: 2024-02-04 16:58:37
> 2024-02-04 16:28:37 DBG Successfully obtained Github Copilot Authorization Token, will set in cache. Token: tid=83bda32e8a7518f58a6ae35c1c030523;exp=1707065917;sku=trial_30_monthly_subscriber;st=dotcom;chat=1;8kp=1:76a7b24939175cc3943fea0981df4f68686201ee39583d097fe7246eb393c1e0, ExpiresAt: 2024-02-04 16:58:37
> 2024-02-04 16:28:37 DBG Modify cache record, app_token: <token>, authorization: {<token> tid=83bda32e8a7518f58a6ae35c1c030523;exp=1707065917;sku=trial_30_monthly_subscriber;st=dotcom;chat=1;8kp=1:76a7b24939175cc3943fea0981df4f68686201ee39583d097fe7246eb393c1e0 1707065917 c06e2527-0280-4d59-b80e-3573c6ceb42f  0 1707064117}
> 2024-02-04 16:28:37 DBG Session expires, update sessionid, app_token: <token>, sessionid: 79555387-dc33-48a4-8469-8297f0e221d41707064117483, session_expires_at: 1707065017
> 2024-02-04 16:28:37 DBG Modify cache record, app_token: <token>, authorization: {  0  79555387-dc33-48a4-8469-8297f0e221d41707064117483 1707065017 1707064117}
> 2024-02-04 16:28:37 DBG Get authorization from cache success, app_token: <token>, will update session expire time
> 2024-02-04 16:28:37 DBG Vscode_machineid is empty, generate new one, app_token: <token>, vscode_machineid: 0dd515bb-15f4-4902-80e4-885552f31085
> 2024-02-04 16:28:37 DBG Modify cache record, app_token: <token>, authorization: {  0 0dd515bb-15f4-4902-80e4-885552f31085  0 1707064117}
> 2024-02-04 16:28:38 ERR Encountering an error when receiving the github copilot response: 400 Bad Request
> 2024-02-04 16:28:38 INF Response Time: 981.086789ms
> Status: 500
> 2024-02-04 16:28:38 DBG Response Header:
> map[Access-Control-Allow-Credentials:[true] Access-Control-Allow-Headers:[*] Access-Control-Allow-Methods:[*] Access-Control-Allow-Origin:[*] Content-Type:[application/json; charset=utf-8]]
> [GIN] 2024/02/04 - 16:28:38 | 500 |   981.26463ms |      10.42.7.74 | POST     "/v1/chat/completions?path=v1&path=chat&path=completions"
> ```

看日志你获取token成功了，但是是后续请求github copilot服务 400 了

**Comment by fyl080801** [comment]
> > > 我这边试了下最新镜像容器，也是正常运行的
> > 
> > 
> > 我发现规律了，如果CACHE设置true就是正常的，之前都是false，日志：
> > ```
> > 2024-02-04T08:28:02.200969766-08:00
> > 2024-02-04 16:28:37 INF Request Info:
> > Method: POST
> > Host: copilot-gpt4.apps.svc:8080
> > URL: /v1/chat/completions?path=v1&path=chat&path=completions
> > 2024-02-04 16:28:37 DBG Request Header:
> > map[Accept:[*/*] Accept-Encoding:[gzip, deflate] Accept-Language:[*] Authorization:[Bearer <token>] Cache-Control:[no-store] Connection:[keep-alive] Content-Type:[application/json] Sec-Fetch-Mode:[cors] User-Agent:[Next.js Middleware] X-Middleware-Subrequest:[app/api/openai/[...path]/route]]
> > 2024-02-04 16:28:37 DBG Get GithubCopilot Authorization Token Success, Token: tid=83bda32e8a7518f58a6ae35c1c030523;exp=1707065917;sku=trial_30_monthly_subscriber;st=dotcom;chat=1;8kp=1:76a7b24939175cc3943fea0981df4f68686201ee39583d097fe7246eb393c1e0, ExpiresAt: 2024-02-04 16:58:37
> > 2024-02-04 16:28:37 DBG Successfully obtained Github Copilot Authorization Token, will set in cache. Token: tid=83bda32e8a7518f58a6ae35c1c030523;exp=1707065917;sku=trial_30_monthly_subscriber;st=dotcom;chat=1;8kp=1:76a7b24939175cc3943fea0981df4f68686201ee39583d097fe7246eb393c1e0, ExpiresAt: 2024-02-04 16:58:37
> > 2024-02-04 16:28:37 DBG Modify cache record, app_token: <token>, authorization: {<token> tid=83bda32e8a7518f58a6ae35c1c030523;exp=1707065917;sku=trial_30_monthly_subscriber;st=dotcom;chat=1;8kp=1:76a7b24939175cc3943fea0981df4f68686201ee39583d097fe7246eb393c1e0 1707065917 c06e2527-0280-4d59-b80e-3573c6ceb42f  0 1707064117}
> > 2024-02-04 16:28:37 DBG Session expires, update sessionid, app_token: <token>, sessionid: 79555387-dc33-48a4-8469-8297f0e221d41707064117483, session_expires_at: 1707065017
> > 2024-02-04 16:28:37 DBG Modify cache record, app_token: <token>, authorization: {  0  79555387-dc33-48a4-8469-8297f0e221d41707064117483 1707065017 1707064117}
> > 2024-02-04 16:28:37 DBG Get authorization from cache success, app_token: <token>, will update session expire time
> > 2024-02-04 16:28:37 DBG Vscode_machineid is empty, generate new one, app_token: <token>, vscode_machineid: 0dd515bb-15f4-4902-80e4-885552f31085
> > 2024-02-04 16:28:37 DBG Modify cache record, app_token: <token>, authorization: {  0 0dd515bb-15f4-4902-80e4-885552f31085  0 1707064117}
> > 2024-02-04 16:28:38 ERR Encountering an error when receiving the github copilot response: 400 Bad Request
> > 2024-02-04 16:28:38 INF Response Time: 981.086789ms
> > Status: 500
> > 2024-02-04 16:28:38 DBG Response Header:
> > map[Access-Control-Allow-Credentials:[true] Access-Control-Allow-Headers:[*] Access-Control-Allow-Methods:[*] Access-Control-Allow-Origin:[*] Content-Type:[application/json; charset=utf-8]]
> > [GIN] 2024/02/04 - 16:28:38 | 500 |   981.26463ms |      10.42.7.74 | POST     "/v1/chat/completions?path=v1&path=chat&path=completions"
> > ```
> 
> 看日志你获取token成功了，但是是后续请求github copilot服务 400 了

 同一个token，如果设置CACHE：true就是成功的，否则就是400

**Comment by Geniucker** [comment]
cache=false的时候确实有问题，我看一下

**Comment by funnyzak** [comment]
> cache=false的时候确实有问题，我看一下

好

**Comment by Geniucker** [comment]
问题大概就是Cache的modify方法在cache=false的时候没有调用是直接覆盖而不是更新非零值字段
