### ISSUE TITLE
报错{"code":403,"error":"{\"error_details\":{\"url\":\"https://github.com/github-copilot/signup?editor={EDITOR}\",\"message\":\"No access to GitHub Copilot found. You are currently logged in as guochenchn.\",\"title\":\"Signup for GitHub Copilot\",\"notification_id\":\"no_copilot_access\"},\"message\":\"Resource not accessible by integration\"}"}data: {"choices":[{"index":0,"delta":{"content":null,"role":"assistant"}}],"created":1704445604,"id":"chatcmpl-8daS4chlUvIAfZ4CPQxzgBQaeFyF7"}

### ISSUE THREAD

**Issue by guochenchn** [aaamoon/copilot-gpt4-service#26]
{"code":403,"error":"{\"error_details\":{\"url\":\"https://github.com/github-copilot/signup?editor={EDITOR}\",\"message\":\"No access to GitHub Copilot found. You are currently logged in as guochenchn.\",\"title\":\"Signup for GitHub Copilot\",\"notification_id\":\"no_copilot_access\"},\"message\":\"Resource not accessible by integration\"}"}data: {"choices":[{"index":0,"delta":{"content":null,"role":"assistant"}}],"created":1704445604,"id":"chatcmpl-8daS4chlUvIAfZ4CPQxzgBQaeFyF7"}

data: {"choices":[{"index":0,"delta":{"content":"你","role":null}}],"created":1704445604,"id":"chatcmpl-8daS4chlUvIAfZ4CPQxzgBQaeFyF7"}

data: {"choices":[{"index":0,"delta":{"content":"好","role":null}}],"created":1704445604,"id":"chatcmpl-8daS4chlUvIAfZ4CPQxzgBQaeFyF7"}

data: {"choices":[{"index":0,"delta":{"content":"！","role":null}}],"created":1704445604,"id":"chatcmpl-8daS4chlUvIAfZ4CPQxzgBQaeFyF7"}

data: {"choices":[{"index":0,"delta":{"content":"有","role":null}}],"created":1704445604,"id":"chatcmpl-8daS4chlUvIAfZ4CPQxzgBQaeFyF7"}

data: {"choices":[{"index":0,"delta":{"content":"什","role":null}}],"created":1704445604,"id":"chatcmpl-8daS4chlUvIAfZ4CPQxzgBQaeFyF7"}

data: {"choices":[{"index":0,"delta":{"content":"么","role":null}}],"created":1704445604,"id":"chatcmpl-8daS4chlUvIAfZ4CPQxzgBQaeFyF7"}

data: {"choices":[{"index":0,"delta":{"content":"我","role":null}}],"created":1704445604,"id":"chatcmpl-8daS4chlUvIAfZ4CPQxzgBQaeFyF7"}

data: {"choices":[{"index":0,"delta":{"content":"可以","role":null}}],"created":1704445604,"id":"chatcmpl-8daS4chlUvIAfZ4CPQxzgBQaeFyF7"}

data: {"choices":[{"index":0,"delta":{"content":"帮","role":null}}],"created":1704445604,"id":"chatcmpl-8daS4chlUvIAfZ4CPQxzgBQaeFyF7"}

data: {"choices":[{"index":0,"delta":{"content":"助","role":null}}],"created":1704445604,"id":"chatcmpl-8daS4chlUvIAfZ4CPQxzgBQaeFyF7"}

data: {"choices":[{"index":0,"delta":{"content":"你","role":null}}],"created":1704445604,"id":"chatcmpl-8daS4chlUvIAfZ4CPQxzgBQaeFyF7"}

data: {"choices":[{"index":0,"delta":{"content":"的","role":null}}],"created":1704445604,"id":"chatcmpl-8daS4chlUvIAfZ4CPQxzgBQaeFyF7"}

data: {"choices":[{"index":0,"delta":{"content":"吗","role":null}}],"created":1704445604,"id":"chatcmpl-8daS4chlUvIAfZ4CPQxzgBQaeFyF7"}

data: {"choices":[{"index":0,"delta":{"content":"？","role":null}}],"created":1704445604,"id":"chatcmpl-8daS4chlUvIAfZ4CPQxzgBQaeFyF7"}

data: {"choices":[{"finish_reason":"stop","index":0,"delta":{"content":null,"role":null}}],"created":1704445604,"id":"chatcmpl-8daS4chlUvIAfZ4CPQxzgBQaeFyF7"}

data: [DONE]

**Comment by aaamoon** [comment]
HTTP返回码403: 使用的账号没有开通 Github Copilot
