### ISSUE TITLE
POST /v1/embeddings 无回复

### ISSUE THREAD

**Issue by brianboy** [aaamoon/copilot-gpt4-service#260]
### Description

感谢：首先很感谢您的项目，我可以已10美元的低价尝试 GPT4.
异常：如下

POST /v1/embeddings: 获取文本向量 API
访问这个接口没有任何返回数据

curl --location --request POST 'http://6.6.26.10:53001/v1/embeddings?path=v1&path=embeddings' \
--header 'Authorization: Bearer ghu_xxxxxx' \
--header 'Content-Type: application/json' \
--data-raw '{
    "input": "hello"
}'

其他接口是正常的，可以愉快的使用 GPT4聊天

**Comment by brianboy** [comment]
FROM    aaamoon/copilot-gpt4-service:5e31a12

ENV     HOST                0.0.0.0
ENV     PORT                3000
ENV     COPILOT_TOKEN       ghu_xxxxxx
ENV     SUPER_TOKEN         123456

**Comment by Geniucker** [comment]
抱歉只有有个改动只在/v1/chat/completions里进行了，忘记应用到/v1/embeddings里了

**Comment by brianboy** [comment]
感谢 👍
