### ISSUE TITLE
accessing from another computer

### ISSUE THREAD

**Issue by thelege2nd** [aaamoon/copilot-gpt4-service#264]
Hello, I want to access my local endpoint URL http://127.0.0.1:8080/ which is on the main computer running the copilot service. I basically want to chat with AI but from a different computer without having to install anything this repo on it. Any easy way to do this?

And yes, it's totally for private use.  Thank you.

**Comment by thangckt** [comment]
> And yes, it's totally for private use. 

I don't think there is anything private here. As my understand, you are using openai API with Copilot key, but not runing a local LLM model.

**Comment by thelege2nd** [comment]
> > And yes, it's totally for private use.
> 
> I don't think there is anything private here. As my understand, you are using openai API with Copilot key, but not runing a local LLM model.

Yes. How can I access my copilot from another device?
