### ISSUE TITLE
Useless trigger for docker_build

### ISSUE THREAD

**Issue by Geniucker** [aaamoon/copilot-gpt4-service#269]
这个触发条件是不是没有必要，合并pr本身会产生push时间，已经足够出发这个workflow了
https://github.com/aaamoon/copilot-gpt4-service/blob/5a89c4a26aa4d048bc2a9162d903bbb765757fc2/.github/workflows/docker_build.yml#L27-L28

**Comment by funnyzak** [comment]
也注意到了。
在 #122 去掉了
