### ISSUE TITLE
是否可以使用GPT4-turbo？

### ISSUE THREAD

**Issue by do02fw** [aaamoon/copilot-gpt4-service#272]
**Are there certain things to report that are not a bug or feature?**
Please tell us as exactly as possible about your request, thanks.
We will reply as soon as possible.
是否可以使用GPT4-turbo？未来会支持GPT4-turbo吗？

**Comment by aaamoon** [comment]
GPT4-turbo is not supported at this time. In the future, it depends on whether Github Copilot can support it.
