### ISSUE TITLE
function calling

### ISSUE THREAD

**Issue by thelege2nd** [aaamoon/copilot-gpt4-service#275]
Hi, does this service work with function calling built via Openai library?

I am trying to use a particular [AI coding app](https://github.com/codecompanion-ai/code-companion), but it's not working as it's supposed to. 

it's working as a chat only and AI is responding, but it's not executing my commands to navigate to specific files or opening them.

**Comment by aaamoon** [comment]
https://github.com/aaamoon/copilot-gpt4-service/issues/98
