### ISSUE TITLE
本地docker部署，请求时报错

### ISSUE THREAD

**Issue by SuperMaxine** [aaamoon/copilot-gpt4-service#28]
我通过docker在本地部署了aaamoon/copilot-gpt4-service:latest，在NextWeb客户端中填写地址为`http://127.0.0.1:8080`，在对NextWeb发送信息时迟迟没有回复，看docker的log发现docker成功接收了请求，但是紧接着报出错误`Encountering an error when sending the request.`。如果换填`https://gpt4copilot.tech/`就可以正常使用。上级路由通过透明代理做了全局代理，可以直接访问copilot、ChatGPT之类的服务，应该不是被墙了连接不了，想问下可能会是什么原因？
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/32979328/c5ee882e-18a9-4ad2-af24-2fd70327e803)

**Comment by GGGGarlic** [comment]
尝试在容器内部 `ping api.github.com` 是否可以正常获取到 ip 地址以及 icmp 响应?
