### ISSUE TITLE
Supporting multiple COPILOT_TOKEN

### ISSUE THREAD

**Issue by delta-whiplash** [aaamoon/copilot-gpt4-service#281]
### Description

I am proposing an enhancement to the way the COPILOT_TOKEN variable is handled within the application. My idea is to enable the COPILOT_TOKEN variable to accept an array of tokens, similar to how the SUPER_TOKEN variable currently functions. This change would allow for a form of load balancing by having the system select a GitHub Copilot token from the array for each chat completion request, either at random or through a round-robin selection process. This approach aims to distribute the workload evenly across multiple Copilot accounts, improving the efficiency and reliability of the service during concurrent use.

### Why

My friends and I, who are IT students, frequently use this tool for personal projects. We've encountered issues when sending messages simultaneously, leading to errors that we suspect are due to rate limits or concurrent access restrictions on a single GitHub Copilot token. Each of us has a GitHub Pro account through our student packs, which includes free Copilot access. By leveraging multiple tokens for load balancing, we believe we can significantly reduce these errors, making our projects run smoother and more reliably. This feature would greatly enhance our user experience by minimizing disruptions and optimizing our access to the GPT-4 capabilities.

### Alternatives

To address this issue, I've set up multiple instances of the project's Docker container, each with a different COPILOT_TOKEN. I then implemented a load balancer using relayd on my OPNsense firewall to distribute requests among these instances. While this solution works, it feels like an overcomplicated approach to what should be a simpler problem to solve. Integrating the load balancing feature directly into the application would streamline our setup, eliminating the need for multiple container instances and an external load balancing system. This internal solution would be much more efficient and user-friendly, allowing us and others in similar situations to focus on our projects without worrying about the underlying infrastructure complexities.

**Comment by delta-whiplash** [comment]
just saw there is a RATE_LIMIT variable what is you're recommandation about it in my context ?

**Comment by Geniucker** [comment]
Our goal is to help **personal user** use gpt through copilot. I think for normal usage, it's not easy to reach the frequency limit unless you're trying to do multiprocess works like translating an essay.
Above all, I think implementing load balance on multiple tokens will lead to more abuse.

**Comment by delta-whiplash** [comment]
okeey Am gonna stay with my workaround
