### ISSUE TITLE
Account has been blocked

### ISSUE THREAD

**Issue by missuo** [aaamoon/copilot-gpt4-service#283]
<img width="412" alt="image" src="https://github.com/aaamoon/copilot-gpt4-service/assets/55200481/79291098-64cd-45f9-8ebd-9eda9752a929">

It's been tested and if abused GitHub will block the account instead of canceling Copilot.

**Comment by tankxiaodi** [comment]
Could you please share with us exactly what you did?

**Comment by missuo** [comment]
不排除跟帐号有关系，我使用的小号都是某鱼/某宝收的，可能都是新号，昨天的帐号就用了一天，就已经 **Suspend** 了。大家注意，尽量别用大号，大号一般不会直接封号，会发邮件警告你的帐号的 Copilot 存在异常行为，如果继续使用的湖，会取消你的 Copilot 资格。

**Comment by aliuq** [comment]
个人使用，还是有共享给其他人？
单设备还是多设备？
🤣🤣慌慌的

**Comment by missuo** [comment]
> 个人使用，还是有共享给其他人？ 单设备还是多设备？ 🤣🤣慌慌的

这有什么单设备多设备的，所有的请求都是通过你的服务器发送的啊。哪来多设备一说。

**Comment by aliuq** [comment]
那个人使用，应该不会触及风控吧

**Comment by zhouyuexie** [comment]
昨天还用的挺好的，今天直接挂了，提示spammy_user，也没做什么
```
{
  "code": 403,
  "error": "{\"error_details\":{\"url\":\"https://support.github.com?editor={EDITOR}\",\"message\":\"Contact Support. You are currently logged in as xxx.\",\"title\":\"Contact Support\",\"notification_id\":\"spammy_user\"},\"message\":\"Resource not accessible by integration\"}"
}
```

**Comment by funnyzak** [comment]
> 昨天还用的挺好的，今天直接挂了，提示spammy_user，也没做什么
> 
> ```
> {
>   "code": 403,
>   "error": "{\"error_details\":{\"url\":\"https://support.github.com?editor={EDITOR}\",\"message\":\"Contact Support. You are currently logged in as xxx.\",\"title\":\"Contact Support\",\"notification_id\":\"spammy_user\"},\"message\":\"Resource not accessible by integration\"}"
> }
> ```

能说说使用场景、使用频率、部署方式吗，做个参考

**Comment by tomridder** [comment]
> 不排除跟帐号有关系，我使用的小号都是某鱼/某宝收的，可能都是新号，昨天的帐号就用了一天，就已经 **Suspend** 了。大家注意，尽量别用大号，大号一般不会直接封号，会发邮件警告你的帐号的 Copilot 存在异常行为，如果继续使用的话，会取消你的 Copilot 资格。

取消copilot资格是不是 copilot没有到期 但是显示 buy copilot …且点击了以后没反应

**Comment by missuo** [comment]
> > 不排除跟帐号有关系，我使用的小号都是某鱼/某宝收的，可能都是新号，昨天的帐号就用了一天，就已经 **Suspend** 了。大家注意，尽量别用大号，大号一般不会直接封号，会发邮件警告你的帐号的 Copilot 存在异常行为，如果继续使用的话，会取消你的 Copilot 资格。
> 
> 取消copilot资格是不是 copilot没有到期 但是显示 buy copilot …且点击了以后没反应

就是被封了。
