### ISSUE TITLE
W10本地模式加Nextchat  启动出现"message": "Failed to fetch"

### ISSUE THREAD

**Issue by long202258** [aaamoon/copilot-gpt4-service#286]
{
  "error": true,
  "message": "Failed to fetch"
}
Nextchat  报这个错误
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/97136192/1b77a509-1410-4f92-aa52-f44b0fd9e0c7)
请问这是什么原因？

**Comment by howtogo2303** [comment]
我也出现类似的问题了，应该坏了吧

**Comment by Geniucker** [comment]
> {
>   "error": true,
>   "message": "Failed to fetch"
> }
> Nextchat  报这个错误
> ![image](https://github.com/aaamoon/copilot-gpt4-service/assets/97136192/1b77a509-1410-4f92-aa52-f44b0fd9e0c7)
> 请问这是什么原因？

这是构建过程中因为网络问题无法下载依赖，所以没有成功构建

**Comment by Geniucker** [comment]
@funnyzak @aaamoon 要不先发个release，这样下载方便，测试那个pr也方便

**Comment by funnyzak** [comment]
我觉得可以，master打tag就可以

**Comment by howtogo2303** [comment]
{
  "code": 403,
  "error": "{\"message\":\"Sorry. Your account was suspended.\",\"documentation_url\":\"https://docs.github.com/rest\"}"
}

**Comment by funnyzak** [comment]
看到和 #283 一样，账号被禁用。
https://github.com/aaamoon/copilot-gpt4-service#not-recommended-approaches 对比不推荐方式，有哪些异常操作吗！


> { "code": 403, "error": "{"message":"Sorry. Your account was suspended.","documentation_url":"[https://docs.github.com/rest\"}](https://docs.github.com/rest%5C%22%7D)" }

**Comment by long202258** [comment]
什么时候发布呢？

**Comment by long202258** [comment]
> 我觉得可以，master打tag就可以

什么时候发布？

**Comment by funnyzak** [comment]
@aaamoon 你看是否发release呢

> > 我觉得可以，master打tag就可以
> 
> 什么时候发布？

**Comment by aaamoon** [comment]
> @aaamoon 你看是否发release呢
> 
> > > 我觉得可以，master打tag就可以
> > 
> > 
> > 什么时候发布？

好啊

**Comment by funnyzak** [comment]
发布 v0.2.0 ？

> > @aaamoon 你看是否发release呢
> > > > 我觉得可以，master打tag就可以
> > > 
> > > 
> > > 什么时候发布？
> 
> 好啊

**Comment by aaamoon** [comment]
> 发布 v0.2.0 ？
> 
> > > @aaamoon 你看是否发release呢
> > > > > 我觉得可以，master打tag就可以
> > > > 
> > > > 
> > > > 什么时候发布？
> > 
> > 
> > 好啊

好的，你那边发一下？

**Comment by funnyzak** [comment]
> > 发布 v0.2.0 ？
> > > > @aaamoon 你看是否发release呢
> > > > > > 我觉得可以，master打tag就可以
> > > > > 
> > > > > 
> > > > > 什么时候发布？
> > > 
> > > 
> > > 好啊
> 
> 好的，你那边发一下？

我试下
