### ISSUE TITLE
关于LangChain OpenAIEmbeddings中使用此项目提供的`/v1/embeddings`接口的疑问

### ISSUE THREAD

**Issue by spianmo** [aaamoon/copilot-gpt4-service#288]
根据OpenAI的文档，实际`/v1/embeddings`接口是支持四种输入的，而LangChain的OpenAIEmbeddings使用的输入正是embedding 的整数数组，虽然在Readme中看到了`copilot-gpt4-service`不支持后两种input，但还是想问一下后期有计划实现吗？不能实现的原因是由于什么。或者大家有没有将此项目使用在LangChain的Embedding步骤的经验，是如何处理`input`字段的。

`POST /v1/embeddings`: 获取文本向量 API

- 请注意，此 API 与 OpenAI API 不完全兼容。 对于 `input` 字段，OpenAI API 接受以下类型：
  - string: 将转换为 embedding 的字符串。
  - array: 将转换为 embedding 的字符串数组。
  - array: 将转换为 embedding 的整数数组。
  - array: 将转换为 embedding 的包含整数的数组的数组。

**Comment by Geniucker** [comment]
gh copilot的api本身只支持字符串数组

**Comment by spianmo** [comment]
> gh copilot的api本身只支持字符串数组，甚至也不支持二维数组，readme里写错了

好吧，那难搞了，得去改LangChain库了，改成input为字符串数组的方式应该就没问题了，但是又得考虑一次性向量化的tokens长度了
