### ISSUE TITLE
Encountering an error when sending the request

### ISSUE THREAD

**Issue by You0** [aaamoon/copilot-gpt4-service#289]
"error": "Encountering an error when sending the request: Post \"https://api.githubcopilot.com/chat/completions\": dial tcp: lookup api.githubcopilot.com on 192.168.31.1:53: no such host"

对话过程中会显示这个错误，是什么情况。使用的是NextChat

**Comment by aaamoon** [comment]
应该是服务端访问不到Github接口，要能翻墙才行

**Comment by funnyzak** [comment]
网络问题。

有可能是DNS问题，改下DNS试试。 如：8.8.8.8
