### ISSUE TITLE
使用chatbox报错：遇到了来自 OpenAI API 的错误，一般是由错误设置或账户问题引起的。。。

### ISSUE THREAD

**Issue by watermeloncq** [aaamoon/copilot-gpt4-service#291]
### Description

我用的docker部署，成功部署后，按照要求在浏览器中输入http://localhost:8080 进行测试，能够正常显示“Very important: please do not make this service public...”

然后，我通过get_copilot_token.py成功获取了Copilot Token，为ghu_kuTLe....(略)

于是，我打开了chatbox，并在chatbox设置中设定如下：
**“AI模型提供方”**：OpenAI API
**“OpenAI API 密匙”**：ghu_kuTLe....(略)
**”API 域名“**：http://127.0.0.1:8080
**“模型 & Token”** 中设定 **“模型”**：gpt-4

chatbox按照这样的设置后，输入prompt会报错，报错完整信息如下：
遇到了来自 OpenAI API 的错误，一般是由错误设置或账户问题引起的。请检查 AI 设置和账户情况，或者[点击这里查看常见问题文档](https://chatboxai.app/redirect_app/faqs/zh-Hans)。

API Error: Status Code 403, {"code":403,"error":"{\"error_details\":{\"url\":\"https://github.com/github-copilot/signup?editor={EDITOR}\",\"message\":\"No access to GitHub Copilot found. You are currently logged in as entle129.\",\"title\":\"Signup for GitHub Copilot\",\"notification_id\":\"no_copilot_access\"},\"message\":\"Resource not accessible by integration\"}"}

这是什么原因？通过上面说明可知，我用docker成功部署copilot-gpt4-service，并按照要求在chatbox中设置了token和API域名地址，也选择了gpt-4模型，但仍然不能使用。是漏掉了什么吗？

**Comment by Geniucker** [comment]
没开通copilot

**Comment by Geniucker** [comment]
没开通copilot

**Comment by watermeloncq** [comment]
> 没开通copilot

请问是要在github上绑定银行卡才能开通吗？

**Comment by aaamoon** [comment]
@watermeloncq 开通 github copilot 后，通过 copilot-gpt4-service 可以在本地客户端使用 gpt-4
