### ISSUE TITLE
因为有些gho token 会失效···所以能否加一个token请求失败后 踢出当前token的功能

### ISSUE THREAD

**Issue by tomridder** [aaamoon/copilot-gpt4-service#294]
### Description

因为有些gho token 会失效···所以能否加一个token请求失败后 踢出当前token的功能

### Why

因为有些gho token 会失效···所以能否加一个token请求失败后 踢出当前token的功能

### Alternatives

因为有些gho token 会失效···所以能否加一个token请求失败后 踢出当前token的功能

**Comment by Geniucker** [comment]
踢出指的是从哪里踢出

**Comment by funnyzak** [comment]
什么使用场景，可以具体描述看看。

**Comment by tomridder** [comment]
因为有的时候并不是只有一个 gho token,而是一群，所以轮训请求的时候把失效的gho token去除。大概这个功能

**Comment by Geniucker** [comment]
使用哪个token不应该是你自己的上证轮询应用决定的吗

**Comment by funnyzak** [comment]
多token的情况。这样用，貌似有封号风险。
