### ISSUE TITLE
v1/chat/completions  接口没有返回 usage 等字段

### ISSUE THREAD

**Issue by sheng-di** [aaamoon/copilot-gpt4-service#296]
### Description

这些字段是否可以进行 mock 处理？有的客户端严格按照 openAI 的接口返回值，如果没有 usage 字段就会报错。

```
promptTokens: json['prompt_tokens'],
      completionTokens: json['completion_tokens'],
      totalTokens: json['total_tokens'],

```

**Comment by Geniucker** [comment]
我记得在这个提交 299253a9817254405c68f86ff164535606822bf5 我加过，openai的标准不是json['usage']['promt_tokens']吗
参考：https://platform.openai.com/docs/api-reference/chat/object#chat/object-usage

**Comment by sheng-di** [comment]
> 我记得在这个提交 [299253a](https://github.com/aaamoon/copilot-gpt4-service/commit/299253a9817254405c68f86ff164535606822bf5) 我加过，openai的标准不是json['usage']['promt_tokens']吗 参考：https://platform.openai.com/docs/api-reference/chat/object#chat/object-usage



是的，类型上可能加了，不过我用 https://github.com/bravekingzhang/flutter_chat_box 这个项目去请求它，github 的返回值中提示 usage 是一个 null 空值。

是不是有的情况下，现在的接口会不返回 usage 字段？

**Comment by Geniucker** [comment]
当`stream=true`的时候不会有`usage`字段，但是openai API的行为也是这样的
