### ISSUE TITLE
请教一个风险相关的问题

### ISSUE THREAD

**Issue by deplives** [aaamoon/copilot-gpt4-service#297]
第一次搭建服务，有些不懂得问题还想请教一下
根据 [不建议方式](https://github.com/aaamoon/copilot-gpt4-service/blob/master/README_CN.md#%E4%B8%8D%E5%BB%BA%E8%AE%AE%E6%96%B9%E5%BC%8F) 中的描述，我现在在自己的一台 vps 上同时搭建了  ChatGPT-Next-Web 和 copilot-gpt4-service 的服务，同时 copilot-gpt4-service 可以通过域名在公网直接访问到。请问这种情况会存在封号之类的风险吗？

**Comment by aaamoon** [comment]
如果很多人通过域名访问你部署的copilot-gpt4-service服务，可能会有风险，不要大范围公开那个域名部署了copilot-gpt4-service服务就好

**Comment by deplives** [comment]
> 如果很多人通过域名访问你部署的copilot-gpt4-service服务，可能会有风险，不要大范围公开那个域名部署了copilot-gpt4-service服务就好

预计只给我自己和我老婆用用，肯定不会公开。这样风险是不是相对小一点

**Comment by aaamoon** [comment]
> > 如果很多人通过域名访问你部署的copilot-gpt4-service服务，可能会有风险，不要大范围公开那个域名部署了copilot-gpt4-service服务就好
> 
> 预计只给我自己和我老婆用用，肯定不会公开。这样风险是不是相对小一点

是的，这样风险比较小

**Comment by deplives** [comment]
> > > 如果很多人通过域名访问你部署的copilot-gpt4-service服务，可能会有风险，不要大范围公开那个域名部署了copilot-gpt4-service服务就好
> > 
> > 
> > 预计只给我自己和我老婆用用，肯定不会公开。这样风险是不是相对小一点
> 
> 是的，这样风险比较小

好的，谢谢。同时也感谢大佬的贡献。

**Comment by tankxiaodi** [comment]
ChatGPT-Next-Web加密码保护，copilot-gpt4-service 最好设定仅内网访问

**Comment by CNYoki** [comment]
用oneAPI再做一层代理会不会好一些？ChatGPT-Next-Web只访问oneAPI的地址
