### ISSUE TITLE
Access Error: 404 -- Not Found Cannot locate document: /

### ISSUE THREAD

**Issue by 160582221** [aaamoon/copilot-gpt4-service#299]
我下载了copilot-gpt4-service.exe
打开http://localhost:8080/ 显示
Access Error: 404 -- Not Found
Cannot locate document: /
我该怎么办

**Comment by Geniucker** [comment]
发下日志

**Comment by 160582221** [comment]
> 发下日志

{"level":"info","type":"initCache","time":"2024-03-01T14:51:33+08:00","message":"Initialized cache"}
{"level":"info","type":"config","time":"2024-03-01T14:51:33+08:00","message":"Host: localhost"}
{"level":"info","type":"config","time":"2024-03-01T14:51:33+08:00","message":"Port: 8080"}
{"level":"info","type":"config","time":"2024-03-01T14:51:33+08:00","message":"Cache: true"}
{"level":"info","type":"config","time":"2024-03-01T14:51:33+08:00","message":"CachePath: db/cache.sqlite3"}
{"level":"info","type":"config","time":"2024-03-01T14:51:33+08:00","message":"Debug: false"}
{"level":"info","type":"config","time":"2024-03-01T14:51:33+08:00","message":"LogLevel: info"}
{"level":"info","type":"config","time":"2024-03-01T14:51:33+08:00","message":"ShareToken: map[]"}
{"level":"info","type":"config","time":"2024-03-01T14:51:33+08:00","message":"Proxy: "}
{"level":"info","type":"startup","time":"2024-03-01T14:51:33+08:00","message":"Start server on localhost:8080"}
{"level":"fatal","type":"startup","time":"2024-03-01T14:51:33+08:00","message":"listen tcp 127.0.0.1:8080: bind: An attempt was made to access a socket in a way forbidden by its access permissions."}

**Comment by 160582221** [comment]
> 发下日志

Copilot-GPT4-Service startup configuration:
 - Port                : 8080
 - Cache               : true
 - CachePath           : db/cache.sqlite3
 - Host                : 0.0.0.0
 - Debug               : false
 - Logging             : true
 - LogLevel            : info
 - CopilotToken        :
 - CORSProxyNextChat   : false
 - RateLimit           : 0
 - EnableSuperToken    : false
 - SuperToken          :

Service is running at:
 - Local               : http://0.0.0.0:8080
 - Network             : http://169.254.24.116:8080
 - Network             : http://169.254.128.152:8080
 - Network             : http://169.254.167.136:8080
 - Network             : http://10.75.106.62:8080
 - Network             : http://127.0.0.1:8080
(Press CTRL+C to quit)

**Comment by Geniucker** [comment]
浏览器访问一次再发日志

**Comment by 160582221** [comment]
> 浏览器访问一次再发日志
我再次访问后日志是这样的，但是我的问题解决了，再次访问成功了，非常感谢大佬，一键三连了
{"level":"info","type":"updateLogLevel","time":"2024-03-01T15:09:06+08:00","message":"Set log level to info"}
{"level":"info","type":"initCache","time":"2024-03-01T15:09:06+08:00","message":"Initialized cache"}
{"level":"info","type":"config","time":"2024-03-01T15:09:06+08:00","message":"Host: localhost"}
{"level":"info","type":"config","time":"2024-03-01T15:09:06+08:00","message":"Port: 8080"}
{"level":"info","type":"config","time":"2024-03-01T15:09:06+08:00","message":"Cache: true"}
{"level":"info","type":"config","time":"2024-03-01T15:09:06+08:00","message":"CachePath: db/cache.sqlite3"}
{"level":"info","type":"config","time":"2024-03-01T15:09:06+08:00","message":"Debug: false"}
{"level":"info","type":"config","time":"2024-03-01T15:09:06+08:00","message":"LogLevel: info"}
{"level":"info","type":"config","time":"2024-03-01T15:09:06+08:00","message":"ShareToken: map[]"}
{"level":"info","type":"config","time":"2024-03-01T15:09:06+08:00","message":"Proxy: "}
{"level":"info","type":"startup","time":"2024-03-01T15:09:06+08:00","message":"Start server on localhost:8080"}
{"level":"fatal","type":"startup","time":"2024-03-01T15:09:06+08:00","message":"listen tcp 127.0.0.1:8080: bind: An attempt was made to access a socket in a way forbidden by its access permissions."}

**Comment by Geniucker** [comment]
不是，你发的不是这个项目的日志，是隔壁 [CoGPT](https://github.com/Geniucker/CoGPT)的。从你第一次发的日志来看，是8080端口被别的应用占了

**Comment by 160582221** [comment]
> 不是，你发的不是这个项目的日志，是隔壁 [CoGPT](https://github.com/Geniucker/CoGPT)的。从你第一次发的日志来看，是8080端口被别的应用占了

是的，我发的是CoGPT的log，因为我一开始尝试打开copilot-gpt4-service.exe不成功，copilot-gpt4-service.exe根目录下也没生成log，我就又下载了CoGPT，运行了一下发现生成了log，然后我就发了这个。我总结一下我遇到这个问题吧，应该就是您说的8080端口被别的应用占了，我一开始打开的网站是http://127.0.0.1:8080不成功，后来在您让我发日志时我又访问了http://localhost:8080/（这个网站也是在隔壁CoGPT那里看到的），发现成功了（很抱歉我的问题中描述错误的网址，我以为这个两个网站是一样的）
