### ISSUE TITLE
有些三方客户端无法使用

### ISSUE THREAD

**Issue by miniers** [aaamoon/copilot-gpt4-service#3]
copilot返回的数据结构和openai的不太一致，缺少了一些字段，导致有些三方客户端解析失败，例如opencat
<img width="1029" alt="image" src="https://github.com/aaamoon/copilot-gpt4-service/assets/2039910/32613dc5-13ae-4bc8-93c8-dfd32c59bf17">

**Comment by aaamoon** [comment]
可以考虑自行部署后端服务，稍微改动一下返回结构

**Comment by miniers** [comment]
嗯，自己改过了，可以用，不过对go不熟悉，写的代码稀烂，就不提PR了🤣

**Comment by aaamoon** [comment]
> 嗯，自己改过了，可以用，不过对go不熟悉，写的代码稀烂，就不提PR了🤣

哈哈，我也不会go，这个项目的代码基本都是GPT帮忙写的
