### ISSUE TITLE
使用 https://cocopilot.org/copilot/token 获取 token 是否安全呢？有替代方案吗？

### ISSUE THREAD

**Issue by zaleGZL** [aaamoon/copilot-gpt4-service#30]

**Comment by aaamoon** [comment]
应该是安全的，我用了很久都没问题，这个Token也可以在代码编辑器使用Github Copilot Chat时抓包获取
![img](https://camo.githubusercontent.com/acdfd1681bcb214faccc1ea5280097b8c4a9b0f2980ce7c9cacb4e4bd1d9c56a/68747470733a2f2f706963782e7a68696d672e636f6d2f76322d31373436653630383636633035616266343538353437646132376233383961652e706e67)

**Comment by lansley** [comment]
cocopilot其实是copilot plugin的名义发的请求，应该是并没有访问账户内容的权限的
![IMG_2392](https://github.com/aaamoon/copilot-gpt4-service/assets/114867070/15816711-1158-414d-8d9e-cd11fbfaef0b)

**Comment by hqzh** [comment]
在设置的接口地址填入本仓库项目部署出来的服务端 API 地址 https://gpt4copilot.tech（强烈建议自行部署服务端，因为不清楚后续 Github 会不会检测到从该服务端 IP 发出太多不同 Token 的请求导致有风险存在）

请问这个如何部署一个服务端呢

**Comment by aaamoon** [comment]
@hqzh 文档那里有写，可以通过docker部署

**Comment by hqzh** [comment]
@aaamoon 得境外服务器或服务器装了代理吧

**Comment by aaamoon** [comment]
@hqzh 是的，因为要请求github的接口，这两天会弄一下Vercel服务端部署，可以关注一下

**Comment by funnyzak** [comment]
建议不要提供公共的服务器地址了，这样大量用户的token会被 github 检测到来自同一服务器商。
感觉这样不太好，项目可以只提供一个工具方式，不提供服务和测试。

@Geniucker 获取Token还可以通过本地获取，算相对安全保险的一种方式：
1. 安装 github-copilot-cli；
2. 执行 `github-copilot-cli auth` 完成授权；
3. `cat ~/.copilot-cli-access-token` 获取token。

**Comment by Geniucker** [comment]
同意，后续我觉得也不用去加一些方便部署的事情，甚至可以把发布形式改成发布二进制文件，然后提供后台运行或者开机启动的方法，这样ip都是自己网络的ip，更加接近真实情况

**Comment by sahuidhsu** [comment]
> 建议不要提供公共的服务器地址了，这样大量用户的token会被 github 检测到来自同一服务器商。 感觉这样不太好，项目可以只提供一个工具方式，不提供服务和测试。
> 
> @Geniucker 获取Token还可以通过本地获取，算相对安全保险的一种方式：
> 
> 1. 安装 github-copilot-cli；
> 2. 执行 `github-copilot-cli auth` 完成授权；
> 3. `cat ~/.copilot-cli-access-token` 获取token。

但是这个包仅限拥有Copilot CLI的用户，普通copilot用户使用会提示不在CLI的waitlist中

**Comment by aaamoon** [comment]
@sahuidhsu 
我试了下不在waitlist中也是可以获取到 Token 的
<img width="498" alt="image" src="https://github.com/aaamoon/copilot-gpt4-service/assets/25700476/7c955fc8-bf36-4ffe-b8e9-a3dd858b7b1a">

**Comment by sahuidhsu** [comment]
> @sahuidhsu 我试了下不在waitlist中也是可以获取到 Token 的 <img alt="image" width="498" src="https://private-user-images.githubusercontent.com/25700476/294764522-7c955fc8-bf36-4ffe-b8e9-a3dd858b7b1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MzgwNDUsIm5iZiI6MTcwNDYzNzc0NSwicGF0aCI6Ii8yNTcwMDQ3Ni8yOTQ3NjQ1MjItN2M5NTVmYzgtYmYzNi00ZmZlLWI4ZTktYTNkZDg1OGI3YjFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDE0MjkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0YmM1Yjc5OWVkYWIxNDI2MzAwYjM3YjA2MTk2YzdjNjUzMmQ5MTZlOWQ4NzY2MmFhOWQ1MjMxOWM0OWQxNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OIps_jKyfe_wGNkV8ztz_j5pyMwFYCFgxYkNAzDaYaY">

噗 我看到这个提示就以为没获取到，原来也正常获取到了啊hhhh

**Comment by funnyzak** [comment]
@sahuidhsu 

github-copilot-cli 方式获取，试试这个命令：

```bash
bash -c "$(curl -fsSL https://raw.githubusercontent.com/aaamoon/copilot-gpt4-service/master/shells/get_copilot_token.sh)"
```

**Comment by abel533** [comment]
cloudflare workers 运行良好

**Comment by hqzh** [comment]
> cloudflare workers 运行良好

有教程吗

**Comment by ysicing** [comment]
你本地安装了vscode且装了copilot插件的话可以直接 `~/.config/github-copilot/hosts.json`

> @sahuidhsu
> 
> github-copilot-cli 方式获取，试试这个命令：
> 
> ```shell
> bash -c "$(curl -fsSL https://raw.githubusercontent.com/aaamoon/copilot-gpt4-service/master/shells/get_copilot_token.sh)"
> ```

**Comment by funnyzak** [comment]
> 你本地安装了vscode且装了copilot插件的话可以直接 `~/.config/github-copilot/hosts.json`
> 
> > @sahuidhsu
> > github-copilot-cli 方式获取，试试这个命令：
> > ```shell
> > bash -c "$(curl -fsSL https://raw.githubusercontent.com/aaamoon/copilot-gpt4-service/master/shells/get_copilot_token.sh)"
> > ```

Mac下没发现这个文件。

**Comment by ysicing** [comment]
@funnyzak  我看了我的两台macOS都有这个文件

可能是其他插件

```
11:20 ysicing-mba ➜  github-copilot ls -alh
total 16
drwx------   4 ysicing  staff   128B 12 21 10:03 .
drwxr-xr-x@ 13 ysicing  staff   416B 12 21 09:59 ..
-rw-r--r--   1 ysicing  staff    91B 12 21 10:03 hosts.json
-rw-r--r--   1 ysicing  staff    34B 12 21 09:59 versions.json
11:20 ysicing-mba ➜  github-copilot cat versions.json
{"copilot-intellij":"1.4.5.4049"}
11:20 ysicing-mba ➜  github-copilot cat hosts.json
```

**Comment by ysicing** [comment]
https://plugins.jetbrains.com/plugin/17718-github-copilot 应该是这个插件

**Comment by funnyzak** [comment]
> [plugins.jetbrains.com/plugin/17718-github-copilot](https://plugins.jetbrains.com/plugin/17718-github-copilot) 应该是这个插件

我在 IDEA 里安装这个插件，然后完成授权，就可以正常获取了。 这个也是一种方式。👍 @ysicing

**Comment by abel533** [comment]
@hqzh 当前项目首页有链接。。不过那边听说容易封号，还不知道后续。

**Comment by funnyzak** [comment]
> @hqzh 当前项目首页有链接。。不过那边听说容易封号，还不知道后续。

应该不会吧，封号应该是滥用吧。
部署到本地请求和本地使用VSCode插件一样的效果。 

我觉得被封，可能原因：
1. 可能是请求来源IP不停变化，被风控了。
2. 把自己CopilotToken公开给了很多人，大量请求，被判断非个人行为使用。

建议是：
1. 固定IP服务器或本机部署。
2. 不要大范围公开自己的Copilot Token。
