### ISSUE TITLE
curl 测试时需要sudo权限才能正确返回，且NextWeb回复错误

### ISSUE THREAD

**Issue by pigeonmg** [aaamoon/copilot-gpt4-service#303]
你好，我在windows11上进行部署，但使用curl测试时，发现需要sudo权限才有回复，不使用sudo的话没有任何回复内容，且在不使用sudo权限时，随便给个token也没有报错信息。另外，通过NextWeb进行问答时，会报如下图的error。想请教一下这是为什么呢
<img width="156" alt="image" src="https://github.com/aaamoon/copilot-gpt4-service/assets/88995948/ea93f998-57b1-4f9c-ba93-054558708e31">

**Comment by aaamoon** [comment]
猜测可能是以下原因：
1、将服务部署到了需要特权的端口，1024以下的端口（例如80或443）
2、防火墙或安全软件可能阻止了curl的网络访问

**Comment by pigeonmg** [comment]
> 猜测可能是以下原因： 1、将服务部署到了需要特权的端口，1024以下的端口（例如80或443） 2、防火墙或安全软件可能阻止了curl的网络访问

我把服务部署在了默认的8080端口，所以应该不是端口问题。网络问题的话，目前WSL2上curl可以访问百度之类的网络，但我的Windows主机和WSL2互相ping不通，试了在防火墙中给WSL2添加规则还是不行，不太懂是怎么回事。

**Comment by Geniucker** [comment]
wsl不能使用locahost访问宿主，宿主可以通过localhost访问wsl里服务

**Comment by pigeonmg** [comment]
> wsl不能使用locahost访问宿主，宿主可以通过localhost访问wsl里服务

我用的WSL2生成的虚拟内网给宿主和linux系统分配的IP互相ping，但无法ping通，不知道是什么原因

**Comment by pigeonmg** [comment]
后续我换到了VMware上，现在正常了，不过不太理解为什么用WSL就不成功
