### ISSUE TITLE
win10安全中心误杀

### ISSUE THREAD

**Issue by zealYOU** [aaamoon/copilot-gpt4-service#307]
win10出现误杀情况，小白不太了解，单纯反馈一下。
![Snipaste_03-06_19-57-26](https://github.com/aaamoon/copilot-gpt4-service/assets/91835185/50acf2a7-4cb8-4060-9c65-ac1d4d60602a)

**Comment by aaamoon** [comment]
试一下在防火墙或安全软件把项目添加到白名单吧，项目本身运行是没风险的
