### ISSUE TITLE
You don't have access to GitHub Copilot. Please sign up first

### ISSUE THREAD

**Issue by aw1d6xx** [aaamoon/copilot-gpt4-service#308]
### Description

![image](https://github.com/aaamoon/copilot-gpt4-service/assets/66401917/b422fd1c-a0a0-4ac9-9f4d-bfbbf8f50c53)
请问这个问题怎么解决 我部署在了本地 已开启科学上网

**Comment by Geniucker** [comment]
没开通Copilot
