### ISSUE TITLE
openai.com been blocked. how can set the proxy for copilot-gpt4-service?

### ISSUE THREAD

**Issue by raidtest** [aaamoon/copilot-gpt4-service#311]
### Description

openai.com been blocked. 
need let [copilot-gpt4-service] can reach it. how do set my proxy (such as 172.0.0.1, port :8001) to it? 
Can show the command or guide for the source run? 
Note : not this http://0.0.0.0:8080 , not this :CORS_PROXY_NEXTCHAT

**Comment by Geniucker** [comment]
why openai is needed

**Comment by raidtest** [comment]
@Geniucker , I guess this service can not generate the response. The nextchat send to http://0.0.0.0:8080/, this service forward it to openai.com,  is it?
the "/v1/chat/completions" belong to openai.com, guess. 

 [GIN] 2024/03/08 - 12:05:00 |[97;42m 200 [0m|            0s |       127.0.0.1 |[90;47m OPTIONS [0m "/v1/chat/completions"

**Comment by raidtest** [comment]
@Geniucker , I guess this service can not generate the response. The nextchat send to http://0.0.0.0:8080/, this service forward it to openai.com,  is it?
the "/v1/chat/completions" belong to openai.com, guess. 

 [GIN] 2024/03/08 - 12:05:00 |[97;42m 200 [0m|            0s |       127.0.0.1 |[90;47m OPTIONS [0m "/v1/chat/completions"

**Comment by Geniucker** [comment]
No, it's forwarded to GitHub copilot

**Comment by Geniucker** [comment]
To set proxy, you may try setting env variables like https_proxy. But socks5 proxy is not yet supposed since net/http doesn't natively support socks5. You can use http proxy.
