### ISSUE TITLE
GPT 版本疑问

### ISSUE THREAD

**Issue by Xiao-Fangff** [aaamoon/copilot-gpt4-service#313]
在选择 `gpt-4` 的情况下，训练数据似乎还是停留在 2021 年 9 月前，但是对于 `开枪打鸟` 之类的问题比 3.5 好的。请问大家都是这样吗？
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/92212954/ca20e7f6-39c2-4410-b004-4b831e8a660a)
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/92212954/88de9850-1c53-4f0c-891e-cf5b67832131)

**Comment by aaamoon** [comment]
gpt-4的训练数据似乎就是停留在 2021 年 9 月前
