### ISSUE TITLE
服务已经成功启动，但是在chatgpt-next-web上无法访问

### ISSUE THREAD

**Issue by lostHill** [aaamoon/copilot-gpt4-service#316]
我在阿里云服务器上安装了ubuntu22.04系统，并且在应用本项目之前就部署了chatgpt-next-web项目，用的是另外一家叫linkai的商家提供的api，可以在网页上通过api访问gpt，随后我在服务器上下载了copilot-gpt4-service文件夹，复制了一份config.env文件，但是并没有做出任何修改。然后输入：
docker run -d \
  --name copilot-gpt4-service \
  --restart always \
  -p 8080:8080 \
  aaamoon/copilot-gpt4-service:latest
  运行了服务，随后当我访问8080端口时，网页出现了Very important: please do not make this service public, for personal use only, otherwise the account or Copilot will be banned.
非常重要：请不要将此服务公开，仅供个人使用，否则账户或 Copilot 将被封禁。的字样，这说明服务已经被成功启动。
然后我访问了我早已经部署好的web网页，当我输入http://127.0.0.1：8080以及token后，提问题时报错：
{
  "error": true,
  "message": "Failed to fetch"
}
现在我不知道该怎么排查问题了。我的web是可以正常转发的（用了linkai的api是），本项目的服务我也正常启动了，token我没办法确定是否正确，反正是代码获得然后复制粘贴的。

**Comment by funnyzak** [comment]
```json
{
"error": true,
"message": "Failed to fetch"
}
```
这应该是网络问题，是 cnw 的错误提示。和 CGS 应该没关系。

你的docker命令是pull docker hub的镜像运行容器，且该命令也没有 -v 挂载磁盘目录。因此你说clone 代码文件夹和copy环境变量文件，不会对你的docker命令有任何作用/影响。

你阿里云部署，应该是本地终端通过域名访问 chatgpt-next-web 服务吧。你在 chatgpt-next-web 设置里，填写 127.0.0.1:8080 肯定是不对的，这个只是表示访问你本地终端的 8080 服务。 

你应该把 cgs 也设置转发并绑定域名，然后把绑定的域名地址，填写到 cnw 的服务器地址里；或者如果不设置cgs域名的话，你可以根据 cnw 的文档，通过设置cnw支持的环境变量把： cgs 的服务器本地访问地址、对应token 设置上，这样 cnw前端就不用单独设置 地址和token了。

**Comment by lostHill** [comment]
已经成功解决，感谢您！
