### ISSUE TITLE
https://api.github.com/copilot_internal/v2/token 这个接口报错 500 和 403，是账户问题 还是 代码问题呢

### ISSUE THREAD

**Issue by tomridder** [aaamoon/copilot-gpt4-service#321]
https://api.github.com/copilot_internal/v2/token 这个接口报错 500 和 403，是账户问题 还是 代码问题呢

**Comment by aaamoon** [comment]
返回403表示账号没有开通GitHub Copilot，你的那个账号有可以使用GitHub Copilot吗

**Comment by tomridder** [comment]
copilot是开通了的。没有到期。10刀。但是自己github的 copilot 显示 buy copilot

**Comment by tomridder** [comment]
![IMG_5786](https://github.com/aaamoon/copilot-gpt4-service/assets/13205117/91e19c93-4aca-4f77-8e65-03fbc2215ed6)
![IMG_5785](https://github.com/aaamoon/copilot-gpt4-service/assets/13205117/e9c37db9-3fce-4589-acc9-4e16b489f18b)
自己的copilot主页显示这个 但是看日期是没有过期的

**Comment by mosimod** [comment]
同样有500的报错，有解决办法吗

**Comment by Geniucker** [comment]
发日志

**Comment by tomridder** [comment]
> 同样有500的报错，有解决办法吗

500 和403都是账户 权限问题。copilot被封了

**Comment by mosimod** [comment]
> > 同样有500的报错，有解决办法吗
> 
> 500 和403都是账户 权限问题。copilot被封了

重复请求就暂时性好了，有时候还会出现这个问题，我在找一下怎么输出日志

**Comment by mosimod** [comment]
> 发日志

请问在docker部署的，映射哪个文件夹出来查看日志

**Comment by mosimod** [comment]
好像是网络的问题，我部署在外网的服务器暂时没有遇见 500的错误问题了

**Comment by Geniucker** [comment]
> > 发日志
> 
> 请问在docker部署的，映射哪个文件夹出来查看日志

```
docker logs copilot-gpt4-service
```

**Comment by mosimod** [comment]
> > > 发日志
> > 
> > 
> > 请问在docker部署的，映射哪个文件夹出来查看日志
> 
> ```
> docker logs copilot-gpt4-service
> ```

Host: 192.168.1.1:8080
URL: /v1/chat/completions
2024-03-19 05:32:35 ERR Encountering an error when sending the request: Post "https://api.githubcopilot.com/chat/completions": EOF error="Post \"https://api.githubcopilot.com/chat/completions\": EOF"
2024-03-19 05:32:35 INF Response Time: 5.014929856s
Status: 500
[GIN] 2024/03/19 - 05:32:35 | 500 |  5.015006603s |      172.17.0.1 | POST     "/v1/chat/completions"
2024-03-19 05:32:54 INF Request Info:
Method: POST

**Comment by tomridder** [comment]
基本都是账户被禁止 copilot权限了 …给github 发邮件



https://support.github.com/contact/account

链接这个
