### ISSUE TITLE
本地docker搭建报错

### ISSUE THREAD

**Issue by s1916** [aaamoon/copilot-gpt4-service#33]
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/62732367/e021014a-cf7d-433d-9c83-362d44e823cd)

**Comment by s1916** [comment]
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/62732367/fa031fc1-6821-40ee-862f-7f1b97e956e8)

**Comment by s1916** [comment]
填写完token在本地通过命令的方式可以调用，但是使用nextchat会报错

**Comment by aaamoon** [comment]
可以截图一下nextchat配置页面的接口地址是怎么填的吗，会不会是跨域的问题

**Comment by s1916** [comment]
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/62732367/dafb9388-230a-4e90-8fb8-11188d9b5148)

**Comment by s1916** [comment]
我是在云服务器搭建的，在这台云服务器上和另一台linux云服务器上都可以通过curl命令使用，但是在我window电脑上用nextchat用不了
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/62732367/ddf100d7-db0d-4f79-adb0-8888cbaa817f)
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/62732367/0ca6cd09-f3c4-4123-8d05-72b7f7787409)

**Comment by aaamoon** [comment]
nextchat客户端部署的是https，你在接口地址那里填的是http的服务器ip，可能是这个问题导致的

**Comment by s1916** [comment]
那有解决办法吗

**Comment by aaamoon** [comment]
你可以在你那台云服务器部署客户端，在window电脑上访问你云服务器部署的nextchat

**Comment by s1916** [comment]
好的，非常感谢
