### ISSUE TITLE
Cloudflare Worker 部署问题

### ISSUE THREAD

**Issue by TomBener** [aaamoon/copilot-gpt4-service#36]
使用 [Cloudflare Worker](https://github.com/wpv-chan/cf-copilot-service) 部署服务端，但无法使用。在 ChatGPT-Next-Web 和沉浸式翻译配置都提示 `500: Missing or malformed Authorization header`。直接访问 Cloudflare Worker 的 Endpoint 显示如下：

```
{"object":"list","data":[{"id":"gpt-4","object":"model","created":1687882411,"owned_by":"openai"},{"id":"gpt-3.5-turbo","object":"model","created":1677610602,"owned_by":"openai"}]}
```

同一个 GitHub Copilot token 可以在 https://gpt4copilot.tech 中正常使用。

**Comment by aaamoon** [comment]
Cloudflare Worker版本是另外一个大佬的项目，建议可以去那边issue问一下
