### ISSUE TITLE
流式传输的问题

### ISSUE THREAD

**Issue by Geniucker** [aaamoon/copilot-gpt4-service#39]
4de3bcedb7b4aa994f106deecaa0ad33d847222f 中试图添加流式传输缺失字段，但是他检测  
他是通过检测当前的缓冲区里面是否有特定字段比如`choice`等，判断是不是应该加入缺失的字段  
但是由于字段可能被截断 (比如`choi`在上一个缓冲区里，`ce`在下一个缓冲区里)，这样就会出问题  
所以其实流式传输的部分应该再改一次，应该读取一个stream event，处理后发给客户端，而不是用固定大小的缓冲区读取固定大小

**Comment by Geniucker** [comment]
我的能力估计也就仅限于review了哈哈哈，go只有hello world的水平233

**Comment by aaamoon** [comment]
哈哈，大佬谦虚了

**Comment by Geniucker** [comment]
刚没看PR，发现已经有的 #37

**Comment by funnyzak** [comment]
@GGGGarlic 基于这个问题，我调整了下。看看 #37

**Comment by aaamoon** [comment]
@Geniucker @funnyzak 好的，测试了一下OK，已合并，感谢大佬们

**Comment by GGGGarlic** [comment]
感谢, 现在就去验证一下.  随后会关闭 issue ,并引用 pr.
