### ISSUE TITLE
能解释一下这些参数的含义吗？谢谢

### ISSUE THREAD

**Issue by lnsane** [aaamoon/copilot-gpt4-service#4]
https://github.com/aaamoon/copilot-gpt4-service/blob/ebeb9eede8719833351f5289fc5503e9e525e955/main.go#L97-L109

**Comment by aaamoon** [comment]
这些是兜底的默认值，参数具体含义可以在 http://gpt4copilot.tech/#/settings 看到
<img width="1131" alt="image" src="https://github.com/aaamoon/copilot-gpt4-service/assets/25700476/ca1eae37-0de8-4b22-88c4-ec027ea7bdc2">
