### ISSUE TITLE
关于此项目

### ISSUE THREAD

**Issue by liaozhangsheng** [aaamoon/copilot-gpt4-service#40]
之前有位大佬写了一个copilot破解的小脚本，也是通过修改token实现的，后来他的账号被封禁、仓库被删。希望本仓库作者小心为妙

**Comment by Geniucker** [comment]
指的是Zhile大佬吗

**Comment by liaozhangsheng** [comment]
> 指的是Zhile大佬吗，就是Pandora的开发者

是的

**Comment by aaamoon** [comment]
不清楚本项目这种调用ChatGPT的方式违不违反Github Copilot的使用规则呢😓

**Comment by Geniucker** [comment]
Zhile大佬被封可能是因为CoCopilot的问题（仅仅是猜测），人们都拼车或共享账号微 软就没钱赚了233

**Comment by Geniucker** [comment]
感觉如果仅仅是自己或和熟悉的朋友用，请求量不是大的过分的话，也许会好一点  
如果拿去做商用，估计这个方法很快就会寄

**Comment by aaamoon** [comment]
这个获取Github Copilot Token的方法是Zhile大佬维护的， `https://cocopilot.org/copilot/token`

**Comment by aaamoon** [comment]
之前问过一个国内卖 ChatGPT API 的老板，他们也知道这种从 Github Copilot 逆向的方法，只是觉得这种方法大量用的话会被 Github 那边发现从而导致封号，太麻烦不稳定而且 Github Copilot 账号也有购买成本，所以他们没有用这种方法搞

**Comment by CaoYunzhou** [comment]
大佬牛逼

**Comment by ysicing** [comment]
> 这个获取Github Copilot Token的方法是Zhile大佬维护的， `https://cocopilot.org/copilot/token`

如果装了vscode copilot插件也可以直接获取token `~/.config/github-copilot/hosts.json`

**Comment by Geniucker** [comment]
> > 这个获取Github Copilot Token的方法是Zhile大佬维护的， `https://cocopilot.org/copilot/token`
> 
> 如果装了vscode copilot插件也可以直接获取token `~/.config/github-copilot/hosts.json`

Windows上貌似没有这个文件

**Comment by ImasakaYue** [comment]
> > 这个获取Github Copilot Token的方法是Zhile大佬维护的， `https://cocopilot.org/copilot/token`
> 
> 如果装了vscode copilot插件也可以直接获取token `~/.config/github-copilot/hosts.json`

mac 上也没有找到这个文件，这有什么前置条件吗？我的 copilot 一直可以在 vscode 正常使用的

**Comment by aaamoon** [comment]
> > > 这个获取Github Copilot Token的方法是Zhile大佬维护的， `https://cocopilot.org/copilot/token`
> > 
> > 
> > 如果装了vscode copilot插件也可以直接获取token `~/.config/github-copilot/hosts.json`
> 
> mac 上也没有找到这个文件，这有什么前置条件吗？我的 copilot 一直可以在 vscode 正常使用的

https://github.com/aaamoon/copilot-gpt4-service/issues/30#issuecomment-1880339152

**Comment by jurieo** [comment]
号没了

**Comment by toor4nsn** [comment]
这要是被Github官方发现了后果比较严重，搞不好运气差购买的copilot连同GitHub账号都被封杀了

**Comment by liwenfengg** [comment]
> 号没了

github 号没了？
