### ISSUE TITLE
nil pointer exception

### ISSUE THREAD

**Issue by chanyk-joseph** [aaamoon/copilot-gpt4-service#41]
`
$ docker logs e279b6349f44
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] POST   /v1/chat/completions      --> main.chatCompletions (4 handlers)
[GIN-debug] GET    /v1/models                --> main.createMockModelsResponse (4 handlers)
[GIN-debug] GET    /healthz                  --> main.main.func1 (4 handlers)
[GIN-debug] Listening and serving HTTP on :8080
[GIN] 2024/01/06 - 15:01:06 | 200 |       9.209µs |    192.168.65.1 | OPTIONS  "/v1/chat/completions"

2024/01/06 15:01:06 [Recovery] 2024/01/06 - 15:01:06 panic recovered:
POST /v1/chat/completions HTTP/1.1
Host: 127.0.0.1:8080
[GIN] 2024/01/06 - 15:01:06 | 500 |  274.797667ms |    192.168.65.1 | POST     "/v1/chat/completions"
Accept: text/event-stream
Accept-Encoding: gzip, deflate, br
Accept-Language: en-HK,en;q=0.9,zh-HK;q=0.8,zh;q=0.7,en-US;q=0.6,en-GB;q=0.5,zh-TW;q=0.4
Authorization: *
Connection: keep-alive
Content-Length: 404
Content-Type: application/json
Origin: https://gpt4copilot.tech
Sec-Ch-Ua: "Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "macOS"
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
X-Requested-With: XMLHttpRequest

runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:261 (0x5c53b)
/usr/local/go/src/runtime/signal_unix.go:861 (0x5c508)
/app/utils/utils.go:49 (0x30271c)
/app/utils/utils.go:83 (0x3029c7)
/app/main.go:158 (0x303dbf)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165 (0x2f876b)
/app/main.go:30 (0x304b7b)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165 (0x2fd38f)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99 (0x2fd374)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165 (0x2fc76f)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241 (0x2fc738)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165 (0x2fb917)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489 (0x2fb648)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445 (0x2fb393)
/usr/local/go/src/net/http/server.go:2938 (0x227e2b)
/usr/local/go/src/net/http/server.go:2009 (0x2251d7)
/usr/local/go/src/runtime/asm_arm64.s:1197 (0x782a3)
`

**Comment by GGGGarlic** [comment]
出现该情况一般是因为网络无法访问 https://api.github.com/copilot_internal/v2/token 导致的连接超时等情况. 
#42 修复该问题. 可参考 #27  更换为可以访问 api.github.com 的网络环境.

**Comment by aaamoon** [comment]
@GGGGarlic 感谢

**Comment by aaamoon** [comment]
@chanyk-joseph 已发布了最新的镜像，可以再试一下

**Comment by chanyk-joseph** [comment]
Thanks!
