### ISSUE TITLE
服务器docker部署后访问网页8080端口提示Method not allowed

### ISSUE THREAD

**Issue by ArkURL** [aaamoon/copilot-gpt4-service#43]
服务部署后，访问服务地址报405 method not allowed，无法访问服务。
服务器可以ping通github api地址
还是说服务器需要能够直连github copilot或者openai才行？

**Comment by maltivaliasana** [comment]
yes i got the same error here

**Comment by funnyzak** [comment]
是的，默认返回 405。目前只处理路径：
- 聊天API： `/v1/chat/completions` 
- 模型列表API：`/v1/models`
