### ISSUE TITLE
How To Get GitHub Copilot Token

### ISSUE THREAD

**Issue by code4you2021** [aaamoon/copilot-gpt4-service#45]
### Get GitHub Copilot Token

Install github-copilot-cli:
```bash
# https://www.npmjs.com/package/@githubnext/github-copilot-cli
npm i @githubnext/github-copilot-cli -g
```

Retrieve the token:
```bash
github-copilot-cli auth
```

View the token:
```bash
vim ~/.copilot-cli-access-token
```

**Comment by aaamoon** [comment]
It seems that you need to have GitHub Copilot CLI waitlist access to use this method?

**Comment by sahuidhsu** [comment]
This method is only working if you have access to Copilot CLI.

**Comment by funnyzak** [comment]
Thanks for contribution.

#46 Already written this way as a shell script.
