### ISSUE TITLE
ChatGPT-Next-Web不会自动生成标题是APP问题还是API问题？

### ISSUE THREAD

**Issue by abel533** [aaamoon/copilot-gpt4-service#51]
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/1787798/504f1a3b-4e96-4544-a480-84eb1c5d7170)
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/1787798/c42d8170-1ad1-4792-bcd4-ea3acabee1a7)

next chat 使用 v2.10.1 版本。
api 使用的 cloudflare workers 版本。

**Comment by aaamoon** [comment]
APP应该没问题的，可以看下自动生成标题那个请求有没有返回什么错误？

**Comment by abel533** [comment]
@aaamoon 谢谢回复，发现生成标题的请求返回出错：
```
SyntaxError: Unexpected end of JSON input
    at c.chat (page-46f80b7055ddd0c9.js:1:29960)
```

跟踪前端代码似乎返回空。。看 @wpv-chan 代码，查看 https://github.com/wpv-chan/cf-copilot-service/blob/380e1bf44c72ef60cc67e78b21fe8ba5b8532784/cf_copilot_service.js#L128C7-L128C7
这里代码返回了正确的结果。

**Comment by funnyzak** [comment]
大佬，可帮助贡献代码优化。

**Comment by abel533** [comment]
@funnyzak cloudflare workers 最新版本代码已经解决该bug
