### ISSUE TITLE
本地部署使用http://127.0.0.1:8080做接口地址，提示NetworkError when attempting to fetch resource

### ISSUE THREAD

**Issue by lzx4627** [aaamoon/copilot-gpt4-service#53]
### Description

大佬帮忙看看是什么问题

![image](https://github.com/aaamoon/copilot-gpt4-service/assets/29448965/8294df3b-5c44-4924-95c0-885408af4e4e)

![image](https://github.com/aaamoon/copilot-gpt4-service/assets/29448965/464ecf8b-d3d1-4491-ae82-d7db1814369e)

**Comment by lzx4627** [comment]
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/29448965/5136ca2f-5ca9-43a6-aa74-9fa371a49dcd)

**Comment by aaamoon** [comment]
试下curl能不能正常请求：
curl --location 'http://127.0.0.1:8080/v1/chat/completions' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer ghu_xx' \
--data '{
  "model": "gpt-4",
  "messages": [ {"role": "user", "content": "你好"}]
}'

docker 内部 `ping api.github.com` 有返回吗

**Comment by GGGGarlic** [comment]
在 next 配置 127.0.0.1 代表的是当前的容器.   
针对于目前您这里的问题, 
如果想要访问到另外一个容器或宿主机, 请使用 `172.16.0.1(docker default bridge gateway)` 或者当前主机的局域网 IP 地址. 

其他方案如下: 
1. 创建独立 docker  network
2. Container link
3. 均使用 --network host

**Comment by lzx4627** [comment]
太感谢，解决了！
