### ISSUE TITLE
支持持久化缓存

### ISSUE THREAD

**Issue by Geniucker** [aaamoon/copilot-gpt4-service#55]
### Description

使用sqlite实现持久化缓存

### Why

在目前的实现中，缓存仅存在于一个map中，重启程序缓存就没了
对于本机部署，重启是经常的事，这样会加大请求github api的次数。所以持久化缓存比较适合本地使用

### Alternatives

已经初步实现了Cache结构体，同时支持存储在map里和sqlite里，下一步尝试实现配置文件解析，添加是否启用持久化缓存的配置

**Comment by Geniucker** [comment]
我感觉`getAuthorizationFromToken`做成一个中间件就很奇怪，这样只能通过一个变量来传递token，是不是应该弄成一个普通函数然后调用一下就好了

**Comment by funnyzak** [comment]
> 我感觉`getAuthorizationFromToken`做成一个中间件就很奇怪，这样只能通过一个变量来传递token，是不是应该弄成一个普通函数然后调用一下就好了

再拆下比较好，易读性、复用也清晰。
