### ISSUE TITLE
请教下 。部署到自己服务器上 大概一天请求 700次 这样 。会面临 需要更换token的问题吗。

### ISSUE THREAD

**Issue by tomridder** [aaamoon/copilot-gpt4-service#57]
### Description

部署到自己服务器上 大概一天请求 700次 这样 。会面临 需要更换token的问题吗。

**Comment by aaamoon** [comment]
应该不需要更换token的

**Comment by tomridder** [comment]
最新发现 用copliot 替换 api key 会 没有流失传输 效果的问题，有啥办法没 大佬

**Comment by aaamoon** [comment]
请求的时候加上参数 stream: true

**Comment by tomridder** [comment]
> 请求的时候加上参数 stream: true

这个其实是 有的 。但是效果不如一些第三方的api提供商流式传输那么顺

**Comment by tomridder** [comment]
> > 请求的时候加上参数 stream: true
> 
> 这个其实是 有的 。但是效果不如一些第三方的api提供商流式传输那么顺

也是断断续续的

**Comment by tomridder** [comment]
问下大佬 用  cloadfareworker的那种方式 支持 流失传输吗
