### ISSUE TITLE
docker部署在阿里云后无法访问

### ISSUE THREAD

**Issue by shiping998** [aaamoon/copilot-gpt4-service#59]
### Description

大佬，你好，我用docker部署在了阿里云上，但是访问报错。不知道怎么回事，求助。

**Comment by hashqueue** [comment]
可以确认下你的阿里云服务器的防火墙是否开了copilot-gpt4-service的8080端口；不过又感觉是你的服务端口冲突了，可能有另外的服务已经占用了8080端口了。

**Comment by funnyzak** [comment]
看看这个 #28

**Comment by shiping998** [comment]
> 看看这个 #28
你好，我看了一下容器内可以ping通
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/6678324/8ae41eec-6575-4ab0-93eb-d69c210524ac)

**Comment by shiping998** [comment]
> 可以确认下你的阿里云服务器的防火墙是否开了copilot-gpt4-service的8080端口；不过又感觉是你的服务端口冲突了，可能有另外的服务已经占用了8080端口了。

我又改成了8081还是一样的

**Comment by hashqueue** [comment]
> > 可以确认下你的阿里云服务器的防火墙是否开了copilot-gpt4-service的8080端口；不过又感觉是你的服务端口冲突了，可能有另外的服务已经占用了8080端口了。
> 
> 我又改成了8081还是一样的

![image](https://github.com/aaamoon/copilot-gpt4-service/assets/42225052/e6abea9a-ca36-4f18-b289-d4308a631de8)
看样子是可以的

**Comment by shiping998** [comment]
> > > 可以确认下你的阿里云服务器的防火墙是否开了copilot-gpt4-service的8080端口；不过又感觉是你的服务端口冲突了，可能有另外的服务已经占用了8080端口了。
> > 
> > 
> > 我又改成了8081还是一样的
> 
> ![image](https://private-user-images.githubusercontent.com/42225052/294830377-e6abea9a-ca36-4f18-b289-d4308a631de8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2OTc5NzAsIm5iZiI6MTcwNDY5NzY3MCwicGF0aCI6Ii80MjIyNTA1Mi8yOTQ4MzAzNzctZTZhYmVhOWEtY2EzNi00ZjE4LWIyODktZDQzMDhhNjMxZGU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA3MDc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5MmNlMWNkMTAxZTNjNmE3N2Y3NTdlNzNmZTZkYjU0NTU3ZGNiYjA1YjIzMzIyNGYyMmJjZTQ3YzI2NjgxNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6HeqMZbQJCDQ9BoYhsSuCw7bH5emuLMQChUSnAbyBnE) 看样子是可以的
ChatGPT-Next-Web上还是这个错
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/6678324/dba7037a-279f-4c86-be08-51c09f0f6112)

**Comment by hashqueue** [comment]
> > > > 可以确认下你的阿里云服务器的防火墙是否开了copilot-gpt4-service的8080端口；不过又感觉是你的服务端口冲突了，可能有另外的服务已经占用了8080端口了。
> > > 
> > > 
> > > 我又改成了8081还是一样的
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/42225052/294830377-e6abea9a-ca36-4f18-b289-d4308a631de8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2OTc5NzAsIm5iZiI6MTcwNDY5NzY3MCwicGF0aCI6Ii80MjIyNTA1Mi8yOTQ4MzAzNzctZTZhYmVhOWEtY2EzNi00ZjE4LWIyODktZDQzMDhhNjMxZGU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA3MDc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5MmNlMWNkMTAxZTNjNmE3N2Y3NTdlNzNmZTZkYjU0NTU3ZGNiYjA1YjIzMzIyNGYyMmJjZTQ3YzI2NjgxNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6HeqMZbQJCDQ9BoYhsSuCw7bH5emuLMQChUSnAbyBnE) 看样子是可以的
> > ChatGPT-Next-Web上还是这个错
> > ![image](https://private-user-images.githubusercontent.com/6678324/294830834-dba7037a-279f-4c86-be08-51c09f0f6112.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2OTgwMzIsIm5iZiI6MTcwNDY5NzczMiwicGF0aCI6Ii82Njc4MzI0LzI5NDgzMDgzNC1kYmE3MDM3YS0yNzlmLTRjODYtYmUwOC01MWMwOWYwZjYxMTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMDcwODUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWI3ZTQzMWE2MDQ5ZGZiZGU3YzkzNGRkNTMyYjYyZjM3YTI5MzhkYjczN2RjZDI5YjMzMTI0ZDM2OWJmYjg2YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KwHNfKjNkGIYhRnMUMLGqG1V4uTTl42Janxmu_arLYo)

确认下下边的选项，还是不行浏览器当前标签页里F12清除下localstorage，然后刷新页面，重新填一下配置项再试试呢

**Comment by hashqueue** [comment]
> > > > > 可以确认下你的阿里云服务器的防火墙是否开了copilot-gpt4-service的8080端口；不过又感觉是你的服务端口冲突了，可能有另外的服务已经占用了8080端口了。
> > > > 
> > > > 
> > > > 我又改成了8081还是一样的
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/42225052/294830377-e6abea9a-ca36-4f18-b289-d4308a631de8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2OTc5NzAsIm5iZiI6MTcwNDY5NzY3MCwicGF0aCI6Ii80MjIyNTA1Mi8yOTQ4MzAzNzctZTZhYmVhOWEtY2EzNi00ZjE4LWIyODktZDQzMDhhNjMxZGU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA3MDc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5MmNlMWNkMTAxZTNjNmE3N2Y3NTdlNzNmZTZkYjU0NTU3ZGNiYjA1YjIzMzIyNGYyMmJjZTQ3YzI2NjgxNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6HeqMZbQJCDQ9BoYhsSuCw7bH5emuLMQChUSnAbyBnE) 看样子是可以的
> > > ChatGPT-Next-Web上还是这个错
> > > ![image](https://private-user-images.githubusercontent.com/6678324/294830834-dba7037a-279f-4c86-be08-51c09f0f6112.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2OTgwMzIsIm5iZiI6MTcwNDY5NzczMiwicGF0aCI6Ii82Njc4MzI0LzI5NDgzMDgzNC1kYmE3MDM3YS0yNzlmLTRjODYtYmUwOC01MWMwOWYwZjYxMTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMDcwODUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWI3ZTQzMWE2MDQ5ZGZiZGU3YzkzNGRkNTMyYjYyZjM3YTI5MzhkYjczN2RjZDI5YjMzMTI0ZDM2OWJmYjg2YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KwHNfKjNkGIYhRnMUMLGqG1V4uTTl42Janxmu_arLYo)
> 
> 确认下下边的选项，还是不行浏览器当前标签页里F12清除下localstorage，然后刷新页面，重新填一下配置项再试试呢

![企业微信截图_17046981173887](https://github.com/aaamoon/copilot-gpt4-service/assets/42225052/77f8bfc7-7df0-45bd-bbed-77392322afd1)

**Comment by shiping998** [comment]
> localstorage

试过了，还是不行。用http://gpt4copilot.tech/就可以，自己建的就不行
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/6678324/db4bc381-2739-4f1c-a722-9ed481b5e763)

**Comment by hashqueue** [comment]
> > localstorage
> 
> 试过了，还是不行。用[http://gpt4copilot.tech/就可以，自己建的就不行](http://gpt4copilot.tech/%E5%B0%B1%E5%8F%AF%E4%BB%A5%EF%BC%8C%E8%87%AA%E5%B7%B1%E5%BB%BA%E7%9A%84%E5%B0%B1%E4%B8%8D%E8%A1%8C) ![image](https://private-user-images.githubusercontent.com/6678324/294834045-db4bc381-2739-4f1c-a722-9ed481b5e763.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2OTkyMzMsIm5iZiI6MTcwNDY5ODkzMywicGF0aCI6Ii82Njc4MzI0LzI5NDgzNDA0NS1kYjRiYzM4MS0yNzM5LTRmMWMtYTcyMi05ZWQ0ODFiNWU3NjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMDcyODUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2NjYjc3ZjkwYzIyOTg5MTFmOTg1ZjhiN2I0NjY4YWFlNTc5OWM0NjRiYWIyZjkxYTQ3YWIwZDRlNmM4OGI0YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7djbt6qo3pf8A5TdKkfbTp6nUuLQiO0l9MPS4DDpVZw)

那就奇怪了，我的一次就成了。。。

**Comment by shiping998** [comment]
> > > localstorage
> > 
> > 
> > 试过了，还是不行。用[http://gpt4copilot.tech/就可以，自己建的就不行](http://gpt4copilot.tech/%E5%B0%B1%E5%8F%AF%E4%BB%A5%EF%BC%8C%E8%87%AA%E5%B7%B1%E5%BB%BA%E7%9A%84%E5%B0%B1%E4%B8%8D%E8%A1%8C) ![image](https://private-user-images.githubusercontent.com/6678324/294834045-db4bc381-2739-4f1c-a722-9ed481b5e763.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2OTkyMzMsIm5iZiI6MTcwNDY5ODkzMywicGF0aCI6Ii82Njc4MzI0LzI5NDgzNDA0NS1kYjRiYzM4MS0yNzM5LTRmMWMtYTcyMi05ZWQ0ODFiNWU3NjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMDcyODUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2NjYjc3ZjkwYzIyOTg5MTFmOTg1ZjhiN2I0NjY4YWFlNTc5OWM0NjRiYWIyZjkxYTQ3YWIwZDRlNmM4OGI0YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7djbt6qo3pf8A5TdKkfbTp6nUuLQiO0l9MPS4DDpVZw)
> 
> 那就奇怪了，我的一次就成了。。。

试了chatbox可以用，chat-gpt-next-web就报这个错

**Comment by GGGGarlic** [comment]
chat-gpt-next-web 的部署是否开启了 https?

**Comment by shiping998** [comment]
> chat-gpt-next-web 的部署是否开启了 https?

开启了，是因为这个原因吗？

**Comment by aaamoon** [comment]
> > chat-gpt-next-web 的部署是否开启了 https?
> 
> 开启了，是因为这个原因吗？

在https的客户端去调用http的接口是会报错的

**Comment by shiping998** [comment]
> 这里说明一下, chatgpt-next-web 是有两种部署模式的.
> 
> ### 第一种:
> 启动进程时通过 env 注入 `BASE_URL` 的情况. 此方式下, 是通过服务内部的 client 进行代理请求. (就算是 next-web 开启了 https, copilot-gpt4-service 开不开 https 无所谓) 所以, 其实在部署方式上, 只要 browser -> next-web 服务器-> copilot-gpt4-service 服务器 -> github api 的链路是通的, 那么该服务就是可用的(对于地理位置之类的可以自己想想怎么组合)
> 
> ### 第二种
> 通过 web-ui 配置 open api 自定义接口的方式. 此方式是以纯前端的方式构建的 client. 并且是完全遵循页面安全的. 即, 如果 next-web 客气了 https, copilot-gpt4-service 必须开启. 在当前部署方式上, 需要 browser -> next-web 服务器 -> copilot-gpt4-service 服务器 -> github api 这样的链路是通的,并且安全等级相同, 那么该服务就是可用的.

我用docker部署chatgpt-next-web并且注入BASE_URL的方式成功了

**Comment by GGGGarlic** [comment]
> > 这里说明一下, chatgpt-next-web 是有两种部署模式的.
> > ### 第一种:
> > 启动进程时通过 env 注入 `BASE_URL` 的情况. 此方式下, 是通过服务内部的 client 进行代理请求. (就算是 next-web 开启了 https, copilot-gpt4-service 开不开 https 无所谓) 所以, 其实在部署方式上, 只要 browser -> next-web 服务器-> copilot-gpt4-service 服务器 -> github api 的链路是通的, 那么该服务就是可用的(对于地理位置之类的可以自己想想怎么组合)
> > ### 第二种
> > 通过 web-ui 配置 open api 自定义接口的方式. 此方式是以纯前端的方式构建的 client. 并且是完全遵循页面安全的. 即, 如果 next-web 客气了 https, copilot-gpt4-service 必须开启. 在当前部署方式上, 需要 browser -> next-web 服务器 -> copilot-gpt4-service 服务器 -> github api 这样的链路是通的,并且安全等级相同, 那么该服务就是可用的.
> 
> 我用docker部署chatgpt-next-web并且注入BASE_URL的方式成功了

是的, 我也喜欢第一种方式部署,这样对于 `copilot-gpt4-service` 服务来说就相对安全多了.

**Comment by zhanghongyong123456** [comment]
> > 这里说明一下, chatgpt-next-web 是有两种部署模式的.
> > ### 第一种:
> > 启动进程时通过 env 注入 `BASE_URL` 的情况. 此方式下, 是通过服务内部的 client 进行代理请求. (就算是 next-web 开启了 https, copilot-gpt4-service 开不开 https 无所谓) 所以, 其实在部署方式上, 只要 browser -> next-web 服务器-> copilot-gpt4-service 服务器 -> github api 的链路是通的, 那么该服务就是可用的(对于地理位置之类的可以自己想想怎么组合)
> > ### 第二种
> > 通过 web-ui 配置 open api 自定义接口的方式. 此方式是以纯前端的方式构建的 client. 并且是完全遵循页面安全的. 即, 如果 next-web 客气了 https, copilot-gpt4-service 必须开启. 在当前部署方式上, 需要 browser -> next-web 服务器 -> copilot-gpt4-service 服务器 -> github api 这样的链路是通的,并且安全等级相同, 那么该服务就是可用的.
> 
> 我用docker部署chatgpt-next-web并且注入BASE_URL的方式成功了

大佬，能说一下如何操作吗，这个如何设置（注入BASE_URL的方式成功了）

**Comment by corp0ra1** [comment]
> > localstorage
> 
> 试过了，还是不行。用[http://gpt4copilot.tech/就可以，自己建的就不行](http://gpt4copilot.tech/%E5%B0%B1%E5%8F%AF%E4%BB%A5%EF%BC%8C%E8%87%AA%E5%B7%B1%E5%BB%BA%E7%9A%84%E5%B0%B1%E4%B8%8D%E8%A1%8C) ![image](https://private-user-images.githubusercontent.com/6678324/294834368-6b90cd6a-4554-4d97-924a-a2d60bf6ea57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MTk5OTEsIm5iZiI6MTcwNDcxOTY5MSwicGF0aCI6Ii82Njc4MzI0LzI5NDgzNDM2OC02YjkwY2Q2YS00NTU0LTRkOTctOTI0YS1hMmQ2MGJmNmVhNTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMTMxNDUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2M4Y2ZmMGFhYmNkYWNiOWNmZmIyNjFmOTg3ZmZmNzY3NGMwOTA1YWM2OTNmY2JmOWI3MzhlN2ZjNmY3MWRjOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mPFVAQMRIhPYEJIxCw4mbZ8dBy1m_2swr8x6Zu3fHiU)

你漏点了老哥，要么删掉这个issus要么换密钥
