### ISSUE TITLE
ChatGPT-Next-Web failed to fetch

### ISSUE THREAD

**Issue by joeyscave** [aaamoon/copilot-gpt4-service#60]
在 ChatBox 和 ChatX 上都成功了（OpenCat 不支持 http 协议就没尝试）
但是 ChatGPT-Next-Web 上一直失败，不论是自己部署在 Vercel 的实例还是官方的 demo，都报 failed to fetch

**Comment by zhonghphuan** [comment]
<img width="368" alt="image" src="https://github.com/aaamoon/copilot-gpt4-service/assets/20340709/2462464f-6e9a-41d2-871b-0efe3dfcf004">

**Comment by aaamoon** [comment]
@zhonghphuan https://github.com/aaamoon/copilot-gpt4-service/issues/43

**Comment by aaamoon** [comment]
@joeyscave 客户端是https，服务端是本地的http吗？

**Comment by zhonghphuan** [comment]
> @zhonghphuan #43

必现部署在能科学上网的服务器上对吗？

**Comment by aaamoon** [comment]
> > @zhonghphuan #43
> 
> 必现部署在能科学上网的服务器上对吗？

是的，因为要请求github的接口

**Comment by shiping998** [comment]
我跟你同样的问题，你解决了吗？

**Comment by joeyscave** [comment]
> @joeyscave 客户端是https，服务端是本地的http吗？

sry 没太理解这句话，我的情况是：
+ 我把这个项目部署在阿里云的 vps（不能科学上网），api 地址是 http://[domain]:8080
+ 我把这个 api 地址和 token 填在 ChatGPT-Next-Web 设置中，报 failed to fetch 错误（官方 demo 和自己部署的都会报错）
+ 我把这个 api 地址和 token 填在 ChatBox 和 ChatX 的设置中可以良好运行

**Comment by yanzhidan90** [comment]
> > @joeyscave 客户端是https，服务端是本地的http吗？
> 
> sry 没太理解这句话，我的情况是：
> 
> * 我把这个项目部署在阿里云的 vps（不能科学上网），api 地址是 http://[domain]:8080
> * 我把这个 api 地址和 token 填在 ChatGPT-Next-Web 设置中，报 failed to fetch 错误（官方 demo 和自己部署的都会报错）
> * 我把这个 api 地址和 token 填在 ChatBox 和 ChatX 的设置中可以良好运行

和你情况一样，不明觉厉

**Comment by shiping998** [comment]
> > > @joeyscave 客户端是https，服务端是本地的http吗？
> > 
> > 
> > sry 没太理解这句话，我的情况是：
> > 
> > * 我把这个项目部署在阿里云的 vps（不能科学上网），api 地址是 http://[domain]:8080
> > * 我把这个 api 地址和 token 填在 ChatGPT-Next-Web 设置中，报 failed to fetch 错误（官方 demo 和自己部署的都会报错）
> > * 我把这个 api 地址和 token 填在 ChatBox 和 ChatX 的设置中可以良好运行
> 
> 和你情况一样，不明觉厉

好像是因为chat-gpt-next-web是https的，自己部署的服务端是http，导致的问题

**Comment by aaamoon** [comment]
<img width="625" alt="截屏2024-01-08 下午4 10 59" src="https://github.com/aaamoon/copilot-gpt4-service/assets/25700476/917ce494-765c-4153-b8bd-5cc814e93f52">

**Comment by GGGGarlic** [comment]
[可以根据这个对](https://github.com/aaamoon/copilot-gpt4-service/issues/59#issuecomment-1880542838)服务部署进行调整.

**Comment by yanzhidan90** [comment]
> > > > @joeyscave 客户端是https，服务端是本地的http吗？
> > > 
> > > 
> > > sry 没太理解这句话，我的情况是：
> > > 
> > > * 我把这个项目部署在阿里云的 vps（不能科学上网），api 地址是 http://[domain]:8080
> > > * 我把这个 api 地址和 token 填在 ChatGPT-Next-Web 设置中，报 failed to fetch 错误（官方 demo 和自己部署的都会报错）
> > > * 我把这个 api 地址和 token 填在 ChatBox 和 ChatX 的设置中可以良好运行
> > 
> > 
> > 和你情况一样，不明觉厉
> 
> 好像是因为chat-gpt-next-web是https的，自己部署的服务端是http，导致的问题

这就去安装证书试试

**Comment by zhonghphuan** [comment]
> * api 地址和 token 填在 ChatBox 和 ChatX 的设置中可以良好运行

不能科学上网的情况下，api 地址（本机部署，127.0.0.1:8080）和 token 填在 ChatBox 和 ChatX 的设置中可以良好运行 ?

**Comment by shiquda** [comment]
自建[copilot-gpt4-service](https://github.com/aaamoon/copilot-gpt4-service)，chatbox可以调用http，但是next-web里面调用http就报错

**Comment by GGGGarlic** [comment]
> 自建[copilot-gpt4-service](https://github.com/aaamoon/copilot-gpt4-service)，chatbox可以调用http，但是next-web里面调用http就报错

参考 #59

**Comment by xiaodeyue2** [comment]
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/50286492/88c67251-afa8-404a-81de-e5e3eb21dbd7)
我这样做了，但是没效果，我部署了云服务和本地进行测试，都失败了，
![Uploading image.png…]()

**Comment by joeyscave** [comment]
> <img alt="截屏2024-01-08 下午4 10 59" width="625" src="https://private-user-images.githubusercontent.com/25700476/294842010-917ce494-765c-4153-b8bd-5cc814e93f52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MjM4MDMsIm5iZiI6MTcwNDcyMzUwMywicGF0aCI6Ii8yNTcwMDQ3Ni8yOTQ4NDIwMTAtOTE3Y2U0OTQtNzY1Yy00MTUzLWI4YmQtNWNjODE0ZTkzZjUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDE0MTgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3NzI1ZWI1Y2I2NWY2Y2JmNmUwZTljNjNkODFhZGVhYzI3YjhlZjA3OTE0NGM3ZjBlNzRlNjA1OTczODM2NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6IG0U8vJyZRWXXVqycUCrhCo_yistB2NtY7jSA3gsEU">

原来如此！套了 SSL 之后 chat-gpt-next-web 果然也能访问了，感谢！🙏
