### ISSUE TITLE
成功了，非常感谢

### ISSUE THREAD

**Issue by wolffyFeng** [aaamoon/copilot-gpt4-service#61]
**Are there certain things to report that are not a bug or feature?**
Please tell us as exactly as possible about your request, thanks.
We will reply as soon as possible.

但是不能画画吗，用的gpt-4

**Comment by aaamoon** [comment]
https://github.com/aaamoon/copilot-gpt4-service?tab=readme-ov-file#%E6%A8%A1%E5%9E%8B%E6%94%AF%E6%8C%81%E6%83%85%E5%86%B5

**Comment by zhengzhanpeng** [comment]
请问怎么使用copilot调用 daille 3接口啊，求教 @aaamoon

**Comment by aaamoon** [comment]
> 请问怎么使用copilot调用 daille 3接口啊，求教 @aaamoon

不支持 daille 3 接口
