### ISSUE TITLE
第三方生成接口授权之后如何取消/刷新掉？

### ISSUE THREAD

**Issue by Lpbzzz** [aaamoon/copilot-gpt4-service#62]
### Description

比如https://cocopilot.org 如何让它失效？

**Comment by aaamoon** [comment]
`https://github.com/settings/apps/authorizations`，在这里试一下
<img width="1224" alt="截屏2024-01-08 下午4 35 55" src="https://github.com/aaamoon/copilot-gpt4-service/assets/25700476/5a490b2d-fa69-4c0a-84f5-77b5ae25e8c6">
