### ISSUE TITLE
关于如何使用：

### ISSUE THREAD

**Issue by zhanghongyong123456** [aaamoon/copilot-gpt4-service#63]
服务新手，找不到相应位置，期待大佬指点一下
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/48466610/6fabbb4e-348f-466b-a919-47331b2af592)
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/48466610/58b85039-1d66-4779-a77e-88b6d0f17e7e)

**Comment by GGGGarlic** [comment]
点击自定义接口后面的 checkbox. 
然后输入 `copilot-gpt4-service` 的 IP 地址 + 端口. 

eg: 
`http(s)://copilot-gpt4-service.example.com:8080` # 如果 chatgpt-next 开启了 https, 则通过这样的方式必须在部署 `copilot-gpt4-service` 的时候配置 https. 


输入 [Token](https://github.com/aaamoon/copilot-gpt4-service?tab=readme-ov-file#%E8%8E%B7%E5%8F%96-copilot-token)

**Comment by zhanghongyong123456** [comment]
> 点击自定义接口后面的 checkbox. 然后输入 `copilot-gpt4-service` 的 IP 地址 + 端口.
> 
> eg: `http(s)://copilot-gpt4-service.example.com:8080` # 如果 chatgpt-next 开启了 https, 则通过这样的方式必须在部署 `copilot-gpt4-service` 的时候配置 https.
> 
> 输入 [Token](https://github.com/aaamoon/copilot-gpt4-service?tab=readme-ov-file#%E8%8E%B7%E5%8F%96-copilot-token)

是的，我配置了，但是出现这个错误：请问BASE_URL 应该设置成什么？  
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/48466610/c09ade42-8a5c-410d-9b11-3c18309dca13)
我看到这个问题，说是可能是  http和https问题：https://github.com/aaamoon/copilot-gpt4-service/issues/59#issuecomment-1880617861

**Comment by GGGGarlic** [comment]
> > 点击自定义接口后面的 checkbox. 然后输入 `copilot-gpt4-service` 的 IP 地址 + 端口.
> > eg: `http(s)://copilot-gpt4-service.example.com:8080` # 如果 chatgpt-next 开启了 https, 则通过这样的方式必须在部署 `copilot-gpt4-service` 的时候配置 https.
> > 输入 [Token](https://github.com/aaamoon/copilot-gpt4-service?tab=readme-ov-file#%E8%8E%B7%E5%8F%96-copilot-token)
> 
> 是的，我配置了，但是出现这个错误：请问BASE_URL 应该设置成什么？ ![image](https://private-user-images.githubusercontent.com/48466610/294863219-c09ade42-8a5c-410d-9b11-3c18309dca13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDgzMjAsIm5iZiI6MTcwNDcwODAyMCwicGF0aCI6Ii80ODQ2NjYxMC8yOTQ4NjMyMTktYzA5YWRlNDItOGE1Yy00MTBkLTliMTEtM2MxODMwOWRjYTEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDEwMDAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5ZmRlZTk5M2Y0YjRkYWNlMjdjYTZhOGYzNjJhZTVjNmI2Y2VhYTA4ZWQ1MmNmY2U2OWQ3ODk3NmY4ZjU2ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BXdK3kJ_39yw42CcEzDqJndrTyqfz3uKbmy8OQAdUtc) 我看到这个问题，说是可能是 http和https问题：[#59 (comment)](https://github.com/aaamoon/copilot-gpt4-service/issues/59#issuecomment-1880617861)

填写当前主机的 IP 地址以及启动该服务时监听的端口号即可.

**Comment by Tspm1eca** [comment]
> > > 点击自定义接口后面的 checkbox. 然后输入 `copilot-gpt4-service` 的 IP 地址 + 端口.
> > > eg: `http(s)://copilot-gpt4-service.example.com:8080` # 如果 chatgpt-next 开启了 https, 则通过这样的方式必须在部署 `copilot-gpt4-service` 的时候配置 https.
> > > 输入 [Token](https://github.com/aaamoon/copilot-gpt4-service?tab=readme-ov-file#%E8%8E%B7%E5%8F%96-copilot-token)
> > 
> > 
> > 是的，我配置了，但是出现这个错误：请问BASE_URL 应该设置成什么？ ![image](https://private-user-images.githubusercontent.com/48466610/294863219-c09ade42-8a5c-410d-9b11-3c18309dca13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDgzMjAsIm5iZiI6MTcwNDcwODAyMCwicGF0aCI6Ii80ODQ2NjYxMC8yOTQ4NjMyMTktYzA5YWRlNDItOGE1Yy00MTBkLTliMTEtM2MxODMwOWRjYTEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDEwMDAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5ZmRlZTk5M2Y0YjRkYWNlMjdjYTZhOGYzNjJhZTVjNmI2Y2VhYTA4ZWQ1MmNmY2U2OWQ3ODk3NmY4ZjU2ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BXdK3kJ_39yw42CcEzDqJndrTyqfz3uKbmy8OQAdUtc) 我看到这个问题，说是可能是 http和https问题：[#59 (comment)](https://github.com/aaamoon/copilot-gpt4-service/issues/59#issuecomment-1880617861)
> 
> 填写当前主机的 IP 地址以及启动该服务时监听的端口号即可.

借題一問，部署好後，127.0.0.1:8080會顯示什麼嗎？

**Comment by funnyzak** [comment]
请求URL路径 `/healthz` 会返回：
```json
{"message":"ok"}
```

> > > > 点击自定义接口后面的 checkbox. 然后输入 `copilot-gpt4-service` 的 IP 地址 + 端口.
> > > > eg: `http(s)://copilot-gpt4-service.example.com:8080` # 如果 chatgpt-next 开启了 https, 则通过这样的方式必须在部署 `copilot-gpt4-service` 的时候配置 https.
> > > > 输入 [Token](https://github.com/aaamoon/copilot-gpt4-service?tab=readme-ov-file#%E8%8E%B7%E5%8F%96-copilot-token)
> > > 
> > > 
> > > 是的，我配置了，但是出现这个错误：请问BASE_URL 应该设置成什么？ ![image](https://private-user-images.githubusercontent.com/48466610/294863219-c09ade42-8a5c-410d-9b11-3c18309dca13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDgzMjAsIm5iZiI6MTcwNDcwODAyMCwicGF0aCI6Ii80ODQ2NjYxMC8yOTQ4NjMyMTktYzA5YWRlNDItOGE1Yy00MTBkLTliMTEtM2MxODMwOWRjYTEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDEwMDAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5ZmRlZTk5M2Y0YjRkYWNlMjdjYTZhOGYzNjJhZTVjNmI2Y2VhYTA4ZWQ1MmNmY2U2OWQ3ODk3NmY4ZjU2ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BXdK3kJ_39yw42CcEzDqJndrTyqfz3uKbmy8OQAdUtc) 我看到这个问题，说是可能是 http和https问题：[#59 (comment)](https://github.com/aaamoon/copilot-gpt4-service/issues/59#issuecomment-1880617861)
> > 
> > 
> > 填写当前主机的 IP 地址以及启动该服务时监听的端口号即可.
> 
> 借題一問，部署好後，127.0.0.1:8080會顯示什麼嗎？

**Comment by Cassius0924** [comment]
是的，我通过 `curl localhost:8080/healthz`，测试了服务没问题，Docker logs 也有反应。在容器内部 `ping api.github.com` 也是正常的。

我是 Docker + Vercel的NextChat，但是就是不能正常使用服务，NextChat也是返回下面错误。

```
{
  "error": true,
  "message": "Failed to fetch"
}
```

而且在 NextChat 问问题的时候， Docker logs 没有反应。请问问题出在哪里？

![CleanShot 2024-01-08 at 21 38 13@2x](https://github.com/aaamoon/copilot-gpt4-service/assets/62874592/dbf39c5d-df3d-43fa-86ef-7000aa13927c)


> 请求URL路径 `/healthz` 会返回：
> 
> ```json
> {"message":"ok"}
> ```
> 
> > > > > 点击自定义接口后面的 checkbox. 然后输入 `copilot-gpt4-service` 的 IP 地址 + 端口.
> > > > > eg: `http(s)://copilot-gpt4-service.example.com:8080` # 如果 chatgpt-next 开启了 https, 则通过这样的方式必须在部署 `copilot-gpt4-service` 的时候配置 https.
> > > > > 输入 [Token](https://github.com/aaamoon/copilot-gpt4-service?tab=readme-ov-file#%E8%8E%B7%E5%8F%96-copilot-token)
> > > > 
> > > > 
> > > > 是的，我配置了，但是出现这个错误：请问BASE_URL 应该设置成什么？ ![image](https://private-user-images.githubusercontent.com/48466610/294863219-c09ade42-8a5c-410d-9b11-3c18309dca13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDgzMjAsIm5iZiI6MTcwNDcwODAyMCwicGF0aCI6Ii80ODQ2NjYxMC8yOTQ4NjMyMTktYzA5YWRlNDItOGE1Yy00MTBkLTliMTEtM2MxODMwOWRjYTEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDEwMDAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5ZmRlZTk5M2Y0YjRkYWNlMjdjYTZhOGYzNjJhZTVjNmI2Y2VhYTA4ZWQ1MmNmY2U2OWQ3ODk3NmY4ZjU2ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BXdK3kJ_39yw42CcEzDqJndrTyqfz3uKbmy8OQAdUtc) 我看到这个问题，说是可能是 http和https问题：[#59 (comment)](https://github.com/aaamoon/copilot-gpt4-service/issues/59#issuecomment-1880617861)
> > > 
> > > 
> > > 填写当前主机的 IP 地址以及启动该服务时监听的端口号即可.
> > 
> > 
> > 借題一問，部署好後，127.0.0.1:8080會顯示什麼嗎？

**Comment by Cassius0924** [comment]
我刚刚试了一下 Chatbox，一切正常，可以连上GPT4使用。而且 Docker logs 正常响应。

**Comment by lifeiteng** [comment]
> http(s)://copilot-gpt4-service.example.com

为什么是 http(s)://copilot-gpt4-service.example.com？ 不是本地起 docker 吗

**Comment by Cassius0924** [comment]
> > http(s)://copilot-gpt4-service.example.com
> 
> 为什么是 http(s)://copilot-gpt4-service.example.com？ 不是本地起 docker 吗

这是填在 NextChat 设置里的，肯定是填你的服务器的IP地址或者域名

**Comment by lifeiteng** [comment]
> > > http(s)://copilot-gpt4-service.example.com
> > 
> > 
> > 为什么是 http(s)://copilot-gpt4-service.example.com？ 不是本地起 docker 吗
> 
> 这是填在 NextChat 设置里的，肯定是填你的服务器的IP地址或者域名

都是本地起的 为啥要域名 不能理解

**Comment by lifeiteng** [comment]
@zhanghongyong123456 一样的疑问

**Comment by Cassius0924** [comment]
> > > > http(s)://copilot-gpt4-service.example.com
> > > 
> > > 
> > > 为什么是 http(s)://copilot-gpt4-service.example.com？ 不是本地起 docker 吗
> > 
> > 
> > 这是填在 NextChat 设置里的，肯定是填你的服务器的IP地址或者域名
> 
> 都是本地起的 为啥要域名 不能理解

nextchat不在本地吧

**Comment by GGGGarlic** [comment]
> > > > http(s)://copilot-gpt4-service.example.com
> > > 
> > > 
> > > 为什么是 http(s)://copilot-gpt4-service.example.com？ 不是本地起 docker 吗
> > 
> > 
> > 这是填在 NextChat 设置里的，肯定是填你的服务器的IP地址或者域名
> 
> 都是本地起的 为啥要域名 不能理解

完全本地部署可以尝试
https://github.com/aaamoon/copilot-gpt4-service/blob/master/example/docker-compose/with-next-chatgpt-web.docker-compose.yaml

**Comment by glitterlip** [comment]
出现Failed to fetch是因为请求接口报错了，打开控制台看一看
我自己的错误是接口地址没填协议，默认了请求了https，custom endpoint 勾上 然后openai endpoint 填 http://localhost:8080/ 即可

原来的api/openai不需要这个 填了会405

还有可能会出现 Failed to get authorization from token 
这个原因是因为你填错了 拿到的 ghu_XXXXX token应该填到openai api key里 access_code 应该留空

![Screen Shot 2024-01-09 at 17 38 01](https://github.com/aaamoon/copilot-gpt4-service/assets/16644496/3bc9d7fb-df25-4d11-af78-49e1ffa6a614)
![Screen Shot 2024-01-09 at 17 38 34](https://github.com/aaamoon/copilot-gpt4-service/assets/16644496/e9d1468b-7a9f-424f-9725-fdc09c50f713)

**Comment by Cassius0924** [comment]
> 出现Failed to fetch是因为请求接口报错了，打开控制台看一看 我自己的错误是接口地址没填协议，默认了请求了https，custom endpoint 勾上 然后openai endpoint 填 http://localhost:8080/ 即可
> 
> 原来的api/openai不需要这个 填了会405
> 
> 还有可能会出现 Failed to get authorization from token 这个原因是因为你填错了 拿到的 ghu_XXXXX token应该填到openai api key里 access_code 应该留空
> 
> ![Screen Shot 2024-01-09 at 17 38 01](https://private-user-images.githubusercontent.com/16644496/295163559-3bc9d7fb-df25-4d11-af78-49e1ffa6a614.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MDIyMzksIm5iZiI6MTcwNDgwMTkzOSwicGF0aCI6Ii8xNjY0NDQ5Ni8yOTUxNjM1NTktM2JjOWQ3ZmItZGYyNS00ZDExLWFmNzgtNDllMWZmYTZhNjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDEyMDUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiYzZiMmEyMWRiOGRhYjljNTU4ZGZkNmZhZTAwYmZiZGI1NDdhMzUzOGFkYTY3ZDI3Zjg4MjIwYmE5ODFmYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bNamtsSnyneHm2d3Fs5ywqoTUAlAiu3nXY-O-OYRazg) ![Screen Shot 2024-01-09 at 17 38 34](https://private-user-images.githubusercontent.com/16644496/295163580-e9d1468b-7a9f-424f-9725-fdc09c50f713.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MDIyMzksIm5iZiI6MTcwNDgwMTkzOSwicGF0aCI6Ii8xNjY0NDQ5Ni8yOTUxNjM1ODAtZTlkMTQ2OGItN2E5Zi00MjRmLTk3MjUtZmRjMDljNTBmNzEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDEyMDUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExOTZkYTUyN2Y2ZjU3ZWJlNWIyODRkNDdkNWMwYzViMWEwY2UwZTRlMjVlMGE5YjBlMzFkOGVjYzRkZWY4MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-bag3tsyfE4wYs-5u1Er1DaaR9U2Gkyka0mNePdxxdM)

 已经填了，我的F12报错是这样的
 
![CleanShot 2024-01-09 at 20 08 36@2x](https://github.com/aaamoon/copilot-gpt4-service/assets/62874592/5f0a764a-fa1f-44e7-97ec-42a792086eef)

**Comment by Cassius0924** [comment]
找到解决方法了。

原因同这个回答 [# 59](https://github.com/aaamoon/copilot-gpt4-service/issues/59#issuecomment-1880617861) 。是由于是 NextChat 是 HTTPS 协议的，而的 CopilotGPT4 是 HTTP 协议的，安全等级不同导致的 [Mixed Conten Error](https://github.com/vercel/vercel/discussions/5287#discussion-24094)

需要将 CopilotGPT4 服务也升级成 HTTPS 协议。如果不支持，可以使用下面方法。

解决方法在见 Vercel 论坛的一个[回答](https://github.com/vercel/vercel/discussions/5287#discussioncomment-3596055)，在浏览器中允许 NextChat 页面的不安全内容即可。

![CleanShot 2024-01-09 at 20 37 37@2x](https://github.com/aaamoon/copilot-gpt4-service/assets/62874592/1d60948a-e425-4f58-b2a4-12741ca8638b)

![CleanShot 2024-01-09 at 20 39 27@2x](https://github.com/aaamoon/copilot-gpt4-service/assets/62874592/1c969b08-d84b-4b1f-8828-68e3deb96bd8)

**Comment by YoungDan-hero** [comment]
> 出现Failed to fetch是因为请求接口报错了，打开控制台看一看 我自己的错误是接口地址没填协议，默认了请求了https，custom endpoint 勾上 然后openai endpoint 填 http://localhost:8080/ 即可
> 
> 原来的api/openai不需要这个 填了会405
> 
> 还有可能会出现 Failed to get authorization from token 这个原因是因为你填错了 拿到的 ghu_XXXXX token应该填到openai api key里 access_code 应该留空
> 
> ![Screen Shot 2024-01-09 at 17 38 01](https://private-user-images.githubusercontent.com/16644496/295163559-3bc9d7fb-df25-4d11-af78-49e1ffa6a614.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NjUwMDgsIm5iZiI6MTcwNDg2NDcwOCwicGF0aCI6Ii8xNjY0NDQ5Ni8yOTUxNjM1NTktM2JjOWQ3ZmItZGYyNS00ZDExLWFmNzgtNDllMWZmYTZhNjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA1MzE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiYmY0YjgwNWY4YTM3NGY0OGY0OTNhZmY4MGE1MTJlMWNlMWIxYTEwZDU5MjQ1MzgwZTNlZTY2OWRkOTE5YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VdsibA0aVGgtrFFdKqi-tSMDEQjkZYE1Njd1c3Z-w4Q) ![Screen Shot 2024-01-09 at 17 38 34](https://private-user-images.githubusercontent.com/16644496/295163580-e9d1468b-7a9f-424f-9725-fdc09c50f713.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NjUwMDgsIm5iZiI6MTcwNDg2NDcwOCwicGF0aCI6Ii8xNjY0NDQ5Ni8yOTUxNjM1ODAtZTlkMTQ2OGItN2E5Zi00MjRmLTk3MjUtZmRjMDljNTBmNzEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA1MzE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhMWM0OGVhNzY3ZGExOGIyODkyYjFlZjAxM2YzNDcxNGE3ZWI0MzhhOGZlZTc3MTA0YmZjYzkzMGM1NTJlMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YFDM8zb5vlhBof5oBlsVNlQcOsG95tIVfKTYNKpQ0_8)

我也是这样配置的，依旧报这样：
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/66891653/4fdc363d-46bc-44bb-b4b7-559d67aa10c9)

**Comment by aaamoon** [comment]
@YoungDan-hero 这个报错一般是token过期或者账号没开通copilot返回的

**Comment by YoungDan-hero** [comment]
> @YoungDan-hero 这个报错一般是token过期或者账号没开通copilot返回的

好的

**Comment by Guanyuansheng** [comment]
> 我刚刚试了一下 Chatbox，一切正常，可以连上GPT4使用。而且 Docker logs 正常响应。

大佬，想问下chatbox是如何使用的？没找到在哪输入API和token。。

**Comment by qyaaaa** [comment]
> http://localhost:8080/



> 出现Failed to fetch是因为请求接口报错了，打开控制台看一看 我自己的错误是接口地址没填协议，默认了请求了https，custom endpoint 勾上 然后openai endpoint 填 http://localhost:8080/ 即可
> 
> 原来的api/openai不需要这个 填了会405
> 
> 还有可能会出现 Failed to get authorization from token 这个原因是因为你填错了 拿到的 ghu_XXXXX token应该填到openai api key里 access_code 应该留空
> 
> ![Screen Shot 2024-01-09 at 17 38 01](https://private-user-images.githubusercontent.com/16644496/295163559-3bc9d7fb-df25-4d11-af78-49e1ffa6a614.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxMTM4NTksIm5iZiI6MTcwNTExMzU1OSwicGF0aCI6Ii8xNjY0NDQ5Ni8yOTUxNjM1NTktM2JjOWQ3ZmItZGYyNS00ZDExLWFmNzgtNDllMWZmYTZhNjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEzVDAyMzkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmYzVjZTEzYzhlYjNlNjg5MjRjMjRlYWYxZDE3ZGYyZjEyMzEwZmYwNzZiMTI5MjIzNGZhNWRhOWIyMWE2OWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HEfCSTKA8-aRI50GRvqx-UGcOmUh60_eiB2PslpcSQk) ![Screen Shot 2024-01-09 at 17 38 34](https://private-user-images.githubusercontent.com/16644496/295163580-e9d1468b-7a9f-424f-9725-fdc09c50f713.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxMTM4NTksIm5iZiI6MTcwNTExMzU1OSwicGF0aCI6Ii8xNjY0NDQ5Ni8yOTUxNjM1ODAtZTlkMTQ2OGItN2E5Zi00MjRmLTk3MjUtZmRjMDljNTBmNzEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEzVDAyMzkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5ZWQ5MzNlZjZmYzFkNWFhMWYzYTRkNzM5NGIxNDNjNzQ0NWFmZmQ5ZTMxODc0MmFlNjg3MTNmOTdmM2MyNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7NRFUP6i9oDI-LujTZaNVY9c1EisPK68MAFU9-NB7I4)

有用，感谢
