### ISSUE TITLE
已经设置好了api,但是每条消息前都会有"强烈建议自行部署 copilot-gpt4-service 服务端..."的提醒

### ISSUE THREAD

**Issue by fencesitter1** [aaamoon/copilot-gpt4-service#65]
现在已经可以进行正常对话,但最近好像每条消息之前都会有"强烈建议自行部署 [copilot-gpt4-service](https://github.com/aaamoon/copilot-gpt4-service) 服务端，否则大量用户的Token会被Github检测到来自同一IP，有可能会对Github账号造成影响，本接口服务将会逐渐下线。
It is strongly recommended to deploy the [copilot-gpt4-service](https://github.com/aaamoon/copilot-gpt4-service) server by yourself, otherwise a large number of users' tokens will be detected by Github from the same IP, which may affect the Github account, and the API service will be gradually offline.
强烈建议自行部署 copilot-gpt4-service 服务器，否则 Github 会检测到来自同一 IP 的大量用户令牌，从而影响 Github 账户，API 服务也会逐渐离线。"的提醒.是我自己的问题还是什么问题

**Comment by aaamoon** [comment]
如果接口地址填的是`http://gpt4copilot.tech`会出现这个提示，考虑到直接用这个接口地址会有风险，可以自行部署服务

**Comment by fencesitter1** [comment]
哦哦好的感谢,我去看看如何部署
