### ISSUE TITLE
any easy guide for a non programmer?

### ISSUE THREAD

**Issue by thangckt** [aaamoon/copilot-gpt4-service#66]
hi @aaamoon 

I am a very newbie.

Do you have any easier docs that shows step-by-steps an amature can understand and follow to deploy the service

Thank you so much

**Comment by aaamoon** [comment]
@thangckt You try [this document](https://github.com/aaamoon/copilot-gpt4-service/blob/master/README_EN.md#server) first, what you don't understand at any time to communicate.

**Comment by thangckt** [comment]
hi, 

after I start sever locally, can check the url `http://127.0.0.1:8080` with this return
````
非常重要：请不要将此服务公开，仅供个人使用，否则账户或 Copilot 将被封禁。Very important: please do not make this service public, for personal use only, otherwise the account or Copilot will be banned. 非常に重要：このサービスを公開しないでください、個人使用のみにしてください。そうしないと、アカウントまたは Copilot が禁止されます。
```

Can you guide me how to input the API address `http://127.0.0.1:8080` into the [ChatGPT-Next-Web](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web)

Thank you so much for your help
