### ISSUE TITLE
关于这个接口会不损耗tokens?还是全免费？

### ISSUE THREAD

**Issue by cossin20** [aaamoon/copilot-gpt4-service#67]
这个会不会损耗copilot的tokens？还是copilot的api接口是免费的？无论gpt3.5还是gpt4?

**Comment by aaamoon** [comment]
copilot没有tokens的概念，只要开通了copilot然后就是免费的了

**Comment by cossin20** [comment]
> copilot没有tokens的概念，只要开通了copilot然后就是免费的了

我的意思这会不会不安全，我听其他人说可能会封号？因为我也是在vercel部署的，然后本地获取的api

**Comment by aaamoon** [comment]
@cossin20 https://github.com/aaamoon/copilot-gpt4-service/issues/30#issuecomment-1880423812
