### ISSUE TITLE
验证在服务端部署成功

### ISSUE THREAD

**Issue by Paul-Georgeee** [aaamoon/copilot-gpt4-service#68]
我在服务端上使用README中提供的docker命令进行执行后，使用curl 127.0.0.1:8080/healthz命令返回curl: (52) Empty reply from server，请问可能是什么原因呢？
<img width="1201" alt="image" src="https://github.com/aaamoon/copilot-gpt4-service/assets/88041433/204605b5-ee10-437a-b1c5-2b21cef9a850">

**Comment by GGGGarlic** [comment]
可以尝试在 docker run 的参数中添加 `--env HOST=0.0.0.0`

**Comment by Paul-Georgeee** [comment]
可以了，感谢！原来README中环境变量是指docker里面设置的，一时半会没有反应过来
