### ISSUE TITLE
404: NOT FOUNT once I click in the app link

### ISSUE THREAD

**Issue by niabnn** [aaamoon/copilot-gpt4-service#73]
### Description

After I click on the app link this error message comes up in the screen:
404: NOT_FOUND
Code: NOT_FOUND
ID: gru1::8x78n-xxxxxxxxxxxxxx

**Comment by aaamoon** [comment]
You can deploy the client and server on your own based on the documentation.

**Comment by GGGGarlic** [comment]
> ### Description
> After I click on the app link this error message comes up in the screen: 404: NOT_FOUND Code: NOT_FOUND ID: gru1::8x78n-xxxxxxxxxxxxxx

apologize for modifying the content you posted. For the security of your account, it is not advisable to display **TOKENs** on public pages.
