### ISSUE TITLE
安全预警

### ISSUE THREAD

**Issue by LashauntayYeldell** [aaamoon/copilot-gpt4-service#76]
### Description

以下情况可能存在吊销token甚至封号的风险：
①同一token通过不同IP访问，如通过cf worker、vecel搭建的服务端访问
②大量token通过同一服务端IP访问，如作者之前创建的服务地址
③滥用行为
请将服务端部署在固定IP的服务器上或本地环境，如果同期存在该大量异常数据，可能存在github官方排查增强安全策略造成该项目over。

**Comment by funnyzak** [comment]
这个可以考虑更新到首页README，提醒使用者勿滥用。

**Comment by GGGGarlic** [comment]
正有此意 , 对于 vecel 和 cf worker 的部署场景不再进行支持, 并提示风险.

**Comment by funnyzak** [comment]
那考虑把文档里的 CF 和 第三方提供的授权服务去掉吧，安全考虑。

**Comment by aaamoon** [comment]
②大量token通过同一服务端IP访问，如作者之前创建的服务地址
这种方式昨天已经下掉了

**Comment by funnyzak** [comment]
开个docs分支可以更新下首页

**Comment by MarshallEriksen-shaomingyang** [comment]
chat-next-web 怎么用啊 我看只有
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/59674455/4dfc3e16-d6ab-471c-85c2-cb1933f9e60f)
token 写在哪啊

**Comment by GGGGarlic** [comment]
结论:
1. 该服务部建议以公共服务的方式提供, 最好本地或个人小规模使用. 
- 多个 Token 在同一个 IP 地址进行请求, 容易被判定为异常行为.
- 同一个 Token 请求频率过高, 容易被判定为异常行为. 
2. 对于该服务的网络环境, 不建议以 serverless 类型的提供商进行部署. 
- 因为服务生命周期短, 并且更换 IP 地址频繁, 容易被判定为异常行为.

**Comment by funnyzak** [comment]
> 结论:
> 
> 1. 该服务部建议以公共服务的方式提供, 最好本地或个人小规模使用.
> 
> * 多个 Token 在同一个 IP 地址进行请求, 容易被判定为异常行为.
> * 同一个 Token 请求频率过高, 容易被判定为异常行为.
> 
> 2. 对于该服务的网络环境, 不建议以 serverless 类型的提供商进行部署.
> 
> * 因为服务生命周期短, 并且更换 IP 地址频繁, 容易被判定为异常行为.
> 
> 建议的部署方式:
> 
> 1. 本地部署
> 2. 服务器集成 chatgpt next web 部署, 该服务不公开
> 3. 服务器部署, 公开但个人使用(例如有多个端的场景)

我觉得直接写结论，经社区验证，最佳部署方式为..

**Comment by GGGGarlic** [comment]
已提交 PR #78

**Comment by MagicalMadoka** [comment]
> 这个可以考虑更新到首页README，提醒使用者勿滥用。

提醒使用者勿滥用？ 直接给我整笑了。有没有可能从用了这个项目那一刻起，就已经是滥用了。
