### ISSUE TITLE
接入 oneapi 后 response为空

### ISSUE THREAD

**Issue by emtry** [aaamoon/copilot-gpt4-service#77]
### Description

```
curl -s http://192.168.x.x:8184/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer ghu_xxx" \
  -d '{
     "model": "gpt-4",        
     "messages": [{"role": "user", "content": "Just say one word: success. No punctuation."}]
   }'
```
返回, 正常使用
`{"object": "chat.completion.chunk", "model": "gpt-4", "choices":[{"finish_reason":"stop","index":0,"message":{"content":"Success","role":"assistant"}}],"created":1704770125,"id":"chatcmpl-8ewsHwJufB3joF9yw44YDoT0ZoEOD","usage":{"completion_tokens":1,"prompt_tokens":17,"total_tokens":18}}`

接入 oneapi
```
curl -s http://192.168.x.x:2999/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer sk-xxx" \
  -d '{
     "model": "gpt-4",
     "messages": [{"role": "user", "content": "Just say one word: success. No punctuation."}]
   }'
```
无返回
`copilot-gpt4-service`和`oneapi`容器均是 200，无错误

**Comment by funnyzak** [comment]
OneApi 目前还没有测过

**Comment by emtry** [comment]
昨天还是前天接入 oneapi还是正常使用的，今天更新了一下镜像容器就不行了

**Comment by funnyzak** [comment]
目前新的PR加了日志功能，可能调试看下。

如果回退能解决的话，你暂时先用旧的镜像这个：`funnyzak/copilot-gpt4-service:240105`

考虑主项目镜像打包得加tag了，方便如遇到问题，回退版本。

> 昨天还是前天接入 oneapi还是正常使用的，今天更新了一下镜像容器就不行了

**Comment by emtry** [comment]
旧的镜像也是空返回，最新镜像 debug=true ，返回 200，无更多信息

**Comment by emtry** [comment]
经测试，"stream":false 时，oneapi 空返回
