### ISSUE TITLE
使用 docker 部署 copilot-gpt4-service + ChatGPT-Next-Web 经验

### ISSUE THREAD

**Issue by lqxhub** [aaamoon/copilot-gpt4-service#79]
安装 **copilot-gpt4-service**

```bash
podman run -d --name copilot-gpt4-service \
--restart always \
-p 8080:8080 \
--env HOST=0.0.0.0 \
aaamoon/copilot-gpt4-service
```
安装 **chatgpt-next-web**

```bash
podman run -d -p 3000:3000 yidadaa/chatgpt-next-web
```

### 关键点:

1. 记得加这个`--env HOST=0.0.0.0` 要不然 不能非本地访问

2. 如果 copilot-gpt4-service 使用的非 https , 不要用 `chatgpt-next-web` 的网页版当做客户端, 要不然 会造成 请求失败, 因为在https的网页中不能 访问 http的服务, 所以推荐自建 `chatgpt-next-web` 服务

**Comment by liwenfengg** [comment]
> 记得加这个--env HOST=0.0.0.0 要不然 不能非本地访问
谢谢大哥！

**Comment by syx-413** [comment]
楼主说的对，如果在vps 想办法支持 HTTPS 访问

**Comment by sheng-di** [comment]
好像 next chat 的客户端在 chromium 新版中也会限制非本地 127 、https 的 http 访问。

**Comment by IwfWcf** [comment]
请问 copilot-gpt4-service 要怎样支持 https？

**Comment by lqxhub** [comment]
> 请问 copilot-gpt4-service 要怎样支持 https？

我能想的的  Nginx 反向代理一下吧

**Comment by zhanghongyong123456** [comment]
> 安装 **copilot-gpt4-service**
> 
> ```shell
> podman run -d --name copilot-gpt4-service \
> --restart always \
> -p 8080:8080 \
> --env HOST=0.0.0.0 \
> aaamoon/copilot-gpt4-service
> ```
> 
> 安装 **chatgpt-next-web**
> 
> ```shell
> podman run -d -p 3000:3000 yidadaa/chatgpt-next-web
> ```
> 
> ### 关键点:
> 1. 记得加这个`--env HOST=0.0.0.0` 要不然 不能非本地访问
> 2. 如果 copilot-gpt4-service 使用的非 https , 不要用 `chatgpt-next-web` 的网页版当做客户端, 要不然 会造成 请求失败, 因为在https的网页中不能 访问 http的服务, 所以推荐自建 `chatgpt-next-web` 服务

不太理解 自建 `chatgpt-next-web` 服务，我是在国外服务器，同时构建   copilot-gpt4-service 和 chatgpt-next-web  两个docker， 将copilot-gpt4-service IP+端口号 和 token 复制到 chatgpt-next-web 设置里面，  依旧 不可用，我看问题集了说是  因为  https 问题，因为我自己 构建的  copilot-gpt4-service IP，前缀是 http://  + IP + 端口，所以 还是不能使用，能给一个具体操作步骤解决这个问题吗
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/48466610/f1c23801-352e-44e0-ad96-5d155b45c2c5)

**Comment by syx-413** [comment]
> 请问 copilot-gpt4-service 要怎样支持 https？
我使用的是这是[nginx-proxy-manager] 
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/104879935/dfab816f-2160-4279-aac5-d9ebff9102a1)
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/104879935/b6b27f0e-a8f1-4ff1-8803-f0ab26abdf04)
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/104879935/9f0977e1-0df9-4fc7-a9e9-92567208acc3)

**Comment by lqxhub** [comment]
> > 安装 **copilot-gpt4-service**
> > ```shell
> > podman run -d --name copilot-gpt4-service \
> > --restart always \
> > -p 8080:8080 \
> > --env HOST=0.0.0.0 \
> > aaamoon/copilot-gpt4-service
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 安装 **chatgpt-next-web**
> > ```shell
> > podman run -d -p 3000:3000 yidadaa/chatgpt-next-web
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### 关键点:
> > 
> > 1. 记得加这个`--env HOST=0.0.0.0` 要不然 不能非本地访问
> > 2. 如果 copilot-gpt4-service 使用的非 https , 不要用 `chatgpt-next-web` 的网页版当做客户端, 要不然 会造成 请求失败, 因为在https的网页中不能 访问 http的服务, 所以推荐自建 `chatgpt-next-web` 服务
> 
> 不太理解 自建 `chatgpt-next-web` 服务，我是在国外服务器，同时构建 copilot-gpt4-service 和 chatgpt-next-web 两个docker， 将copilot-gpt4-service IP+端口号 和 token 复制到 chatgpt-next-web 设置里面， 依旧 不可用，我看问题集了说是 因为 https 问题，因为我自己 构建的 copilot-gpt4-service IP，前缀是 http:// + IP + 端口，所以 还是不能使用，能给一个具体操作步骤解决这个问题吗 ![image](https://private-user-images.githubusercontent.com/48466610/295114637-f1c23801-352e-44e0-ad96-5d155b45c2c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3ODA4OTUsIm5iZiI6MTcwNDc4MDU5NSwicGF0aCI6Ii80ODQ2NjYxMC8yOTUxMTQ2MzctZjFjMjM4MDEtMzUyZS00NGUwLWFkOTYtNWQxNTViNDVjMmM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDA2MDk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiODc1MmI1NzBhZDYwMzU4NzA4ZjkxYTE5MTYwMTdkYmY4MmRjMzI1OGFjZmRiZGZmYWYxODYxYTE0OWM4YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RhRTePU7ph-olGoDEMECF-aj9YzWYN-P2_GG48aHm5c)

你的服务器开放 对应的端口了吗

**Comment by lqxhub** [comment]
> > 请问 copilot-gpt4-service 要怎样支持 https？
> > 我使用的是这是[nginx-proxy-manager]
> > ![image](https://private-user-images.githubusercontent.com/104879935/295115621-dfab816f-2160-4279-aac5-d9ebff9102a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3ODExNTYsIm5iZiI6MTcwNDc4MDg1NiwicGF0aCI6Ii8xMDQ4Nzk5MzUvMjk1MTE1NjIxLWRmYWI4MTZmLTIxNjAtNDI3OS1hYWM1LWQ5ZWJmZjkxMDJhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQwNjE0MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MzUwYTlmMmE4ZGFlMTE1YWU1YTQ4NmRhMWY4ZmJjZDBiZWFjM2VmMjRlMWE1Yjk2YjQ5OGMwMTdlZDU5ZDEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oXsRcDpvv_WDO0MYKtX_a269X8FqEM_c_PVyBL5YCGU)
> > ![image](https://private-user-images.githubusercontent.com/104879935/295115740-b6b27f0e-a8f1-4ff1-8803-f0ab26abdf04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3ODExNTYsIm5iZiI6MTcwNDc4MDg1NiwicGF0aCI6Ii8xMDQ4Nzk5MzUvMjk1MTE1NzQwLWI2YjI3ZjBlLWE4ZjEtNGZmMS04ODAzLWYwYWIyNmFiZGYwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQwNjE0MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzAzYTQ5YWIzNTExMmY3YmRhNDhjOGNmMzQ4MmZmNGU0MjE5YmViMzI5OGFmMGI0M2E2OWNmMTkyYmU1YzNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.y5JV1hhQ3ej3hU5byrgNrQ_ebWbIJZugCLerFjQ3DyE)
> > ![image](https://private-user-images.githubusercontent.com/104879935/295115868-9f0977e1-0df9-4fc7-a9e9-92567208acc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3ODExNTYsIm5iZiI6MTcwNDc4MDg1NiwicGF0aCI6Ii8xMDQ4Nzk5MzUvMjk1MTE1ODY4LTlmMDk3N2UxLTBkZjktNGZjNy1hOWU5LTkyNTY3MjA4YWNjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQwNjE0MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YmZiMTQ4NjEzN2ZmZjc0YTkzZDExOGM0ODg4ZDkxYzQ1ZGJiMjU1NDc4YzVlNTU0NDQwMWMyNDhmZmZlNjkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IGfTTZFSYJMdKbnVQBYfaUIORV8uxcnpfiA9Ikz8mfU)

Nginx 接收 https 请求, 然后使用 http 转发到 `copilot-gpt4-service` 上, nginx-proxy-manager 这种控制面板没用过, 我都是写配置文件

**Comment by IwfWcf** [comment]
> > 请问 copilot-gpt4-service 要怎样支持 https？
> 
> 我使用的是这是 [nginx-proxy-manager] ![image](https://private-user-images.githubusercontent.com/104879935/295115621-dfab816f-2160-4279-aac5-d9ebff9102a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3ODQzOTcsIm5iZiI6MTcwNDc4NDA5NywicGF0aCI6Ii8xMDQ4Nzk5MzUvMjk1MTE1NjIxLWRmYWI4MTZmLTIxNjAtNDI3OS1hYWM1LWQ5ZWJmZjkxMDJhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQwNzA4MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTgwZmViYThiOTcxOWUwNGQ1NjYzZTYxN2Q4NjU2YmRmOTViYjAxZGZiNjUzMWMxMzIxNThiNDkxNWVhZjRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jcIXZm1Vz0nxDoU2ux3Kd9_8ssGm45yM_TKaGEflakM) ![image](https://private-user-images.githubusercontent.com/104879935/295115740-b6b27f0e-a8f1-4ff1-8803-f0ab26abdf04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3ODQzOTcsIm5iZiI6MTcwNDc4NDA5NywicGF0aCI6Ii8xMDQ4Nzk5MzUvMjk1MTE1NzQwLWI2YjI3ZjBlLWE4ZjEtNGZmMS04ODAzLWYwYWIyNmFiZGYwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQwNzA4MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NzgxOGNhY2IxMzQ5ZjFmZGJkZjc4NGI4YmNhNDQ4YmJmY2JiZTNmZGIxMjMxNTc3NWUyMDI5YmU3NDNlYTM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NB7xurUWTwsCLHPOzZpShCCWrDTJKAuvUT4qBD00M4I) ![image](https://private-user-images.githubusercontent.com/104879935/295115868-9f0977e1-0df9-4fc7-a9e9-92567208acc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3ODQzOTcsIm5iZiI6MTcwNDc4NDA5NywicGF0aCI6Ii8xMDQ4Nzk5MzUvMjk1MTE1ODY4LTlmMDk3N2UxLTBkZjktNGZjNy1hOWU5LTkyNTY3MjA4YWNjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQwNzA4MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MmI3MGM1ZWRlMmIxNGUzOGZkMjI1ZDRmNGI5Y2M5ODc5Y2JkODIxYmRmMTlmMjI3ZmRiNGYwMDRlNDVmZmQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.75Y7QYyjkQIqL-v4HOaJlM3jLYMTPZ3EM6dHYshiYow)

感谢，用 nginx-proxy-manager 搞定了

**Comment by dw763j** [comment]
加入https的最简方式是使用caddy2服务器。

**Comment by stuartofmine** [comment]
请问ChatGPTNextWeb 中到底应该怎样设置api地址和token？搜了issue也没人给出准确的回复。

**Comment by aaamoon** [comment]
> 请问ChatGPTNextWeb 中到底应该怎样设置api地址和token？搜了issue也没人给出准确的回复。

在设置页面的接口地址和API KEY中填入api地址和token

**Comment by stuartofmine** [comment]
> > 请问ChatGPTNextWeb 中到底应该怎样设置api地址和token？搜了issue也没人给出准确的回复。
> 
> 在设置页面的接口地址和API KEY中填入api地址和token

感谢🙏。我知道为什么之前不行了，使用ChatGPTNextWeb部署在远程服务器上需要使用nginx反向代理以规避CORS，将我的nginx conf列出以供其他人参考：

```
location / { 
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        }
```
假设部署在 MyNmae.com 上，反向代理12138端口到服务器 http://127.0.0.1:8080， ChatGPTNextWeb 设置中api地址应该填写 https://MyNmae.com:12138 ，Token填写 ghu_xxxxxxxx

**Comment by stuartofmine** [comment]
> > > 请问ChatGPTNextWeb 中到底应该怎样设置api地址和token？搜了issue也没人给出准确的回复。
> > 
> > 
> > 在设置页面的接口地址和API KEY中填入api地址和token
> 
> 感谢🙏。我知道为什么之前不行了，使用ChatGPTNextWeb部署在远程服务器上需要使用nginx反向代理以规避CORS，将我的nginx conf列出以供其他人参考：
> ```
> location / { 
>         proxy_pass http://127.0.0.1:8080;
>         proxy_set_header Host $host;
>         proxy_set_header X-Real-IP $remote_addr;
>         }
> ```
> 
> 假设部署在 MyNmae.com 上，反向代理12138端口到服务器 [http://127.0.0.1:8080，](http://127.0.0.1:8080%EF%BC%8C) ChatGPTNextWeb 设置中api地址应该填写 https://MyNmae.com:12138 ，Token填写 ghu_xxxxxxxx

或者通过docker 部署时指定: ```docker run -d -p 3000:3000    -e CODE=252659  -e OPENAI_API_KEY=ghu_xxxxxxxx -e BASE_URL='https://MyNmae.com:12138'  yidadaa/chatgpt-next-web```
