### ISSUE TITLE
请问作者在最新的readme中去除了使用Cloudflare Worker搭建的方式，是否由于安全性或其他原因考量？

### ISSUE THREAD

**Issue by usefortemp** [aaamoon/copilot-gpt4-service#80]
**Are there certain things to report that are not a bug or feature?**
Please tell us as exactly as possible about your request, thanks.
We will reply as soon as possible.

**Comment by aaamoon** [comment]
https://github.com/aaamoon/copilot-gpt4-service/issues/76
