### ISSUE TITLE
部署成功，但是感觉不是GPT4，而是3.5

### ISSUE THREAD

**Issue by maxmeng93** [aaamoon/copilot-gpt4-service#84]
```
我的知识库截止到2021年9月，是基于那个时间点之前的信息进行训练的。
所以我可能无法提供关于2021年9月之后的最新信息。不过我会尽力帮助你回答问题和提供信息。
如果你有具体的问题，请随时告诉我。
```
知识库截止2021年9月。

**Comment by dream2333** [comment]
![微信截图_20240109144705](https://github.com/aaamoon/copilot-gpt4-service/assets/39302391/7796f13c-1d9c-4f2e-bddb-87a40ac38650)
copilot之前我记得用的是codex，现在再问他已经是gpt4了

**Comment by maxmeng93** [comment]
> ![微信截图_20240109144705](https://private-user-images.githubusercontent.com/39302391/295122348-7796f13c-1d9c-4f2e-bddb-87a40ac38650.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3ODM1MTIsIm5iZiI6MTcwNDc4MzIxMiwicGF0aCI6Ii8zOTMwMjM5MS8yOTUxMjIzNDgtNzc5NmYxM2MtMWQ5Yy00ZjJlLWJkZGItODdhNDBhYzM4NjUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDA2NTMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhZmVhMGMyM2UzMjYzMzY3MDJkM2I4ODgyZTlkOTI1ODI5ZWM3MmE5ZjI1Nzc4MTQ1YjljMDYwYmE5Njc1YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1yXi5TQ25FFmMxPaNo36UgP23bojG5_Vyt62hf3BjVU) copilot之前我记得用的是codex，现在再问他已经是gpt4了

那应该是早就训练好的GPT4，而不是openAI最新版本的GPT4，所以知识库不一样

**Comment by aaamoon** [comment]
@dream2333 可以看看https://github.blog/changelog/2023-11-30-github-copilot-november-30th-update/#copilot-chat-is-powered-by-gpt-4

**Comment by aaamoon** [comment]
文档里面有两个提问可以判断是不是GPT4，可以试一下

**Comment by aaamoon** [comment]
@maxmeng93 GPT4数据的截止时间就是2021.09

**Comment by dream2333** [comment]
> 文档里面有两个提问可以判断是不是GPT4，可以试一下

嗯嗯，这个问题之前试过了，现在版本的copilot不会回答非编程的提问，所以不行了
