### ISSUE TITLE
本地部署NextChat报错“failed to fetch”

### ISSUE THREAD

**Issue by tomleung1996** [aaamoon/copilot-gpt4-service#9]
你好，我尝试在本地安装NextChat并使用Docker部署了copilot-gpt4-service，接口地址填http://127.0.0.1:8080时可以正常使用。

然后我尝试在局域网另一台服务器使用podman部署了copilot-gpt4-service，在本机使用NextChat，接口地址填http://服务器地址:8080 则报错
```
{
  "error": true,
  "message": "Failed to fetch"
}
```
该服务器的防火墙已经允许8080的入站访问，浏览器访问http://服务器地址:8080 可以出现404 page not found页面。

此外，在本地安装的NextChat中接口地址填入http://gpt4copilot.tech/ 也报同样的错误。

想问一下这个问题该怎么解决呢？谢谢！

**Comment by aaamoon** [comment]
帮你问了一下GPT-4：
这个问题可能是由于跨域请求（CORS）的限制导致的。浏览器出于安全考虑，会限制跨域的请求，除非服务器明确允许。
解决这个问题的一个可能的方法是在你的 copilot-gpt4-service 服务器上设置 CORS headers，允许来自你的 NextChat 客户端的请求。

**Comment by tomleung1996** [comment]
感谢回复。我尝试在同一台Linux服务器上用podman部署了copilot-gpt4-service和NextChat，接口地址填http://127.0.0.1:8080 但仍然报同样的错误，可否咨询一下您在http://gpt4copilot.tech/ 这个站点是怎么进行两者配置的吗？

**Comment by aaamoon** [comment]
你在同一台Linux服务器部署了copilot-gpt4-service和NextChat的话，比如你的Linux服务器的IP是1.1.1.1，接口地址就填http://1.1.1.1:8080，这时候你在你的电脑去访问http://1.1.1.1:3000就可以了

**Comment by tomleung1996** [comment]
还是不行呢，1.1.1.1、127.0.0.1、localhost、本机IP都试了，还是不行… 您的copilot-gpt4-service和NextChat也都是用podman或者docker部署么？

**Comment by aaamoon** [comment]
@tomleung1996 你截图一下整个网页url和配置那里的接口地址我看看？

**Comment by lxzcpro** [comment]
我试了一试NextChat的网页版跟本地版 如果直接修改API跟接口都是会报错的 只有用在http://gpt4copilot.tech/网页中的NextChat修改接口与API才可用

**Comment by aaamoon** [comment]
@lxzcpro 这就是跨域的问题，如果你客户端用的是http://gpt4copilot.tech ，那么你的接口地址就只能填http://gpt4copilot.tech ；如果你客户端用本地版，那你的接口地址就只能填本地接口地址

**Comment by tomleung1996** [comment]
在同一台服务器通过podman部署的NextChat和copilot-gpt4-service成功了，填写的具体地址是http://服务器地址:8080 ，不过跨域问题尚未得到解决（其他及其的nextchat客户端无法通过这样填写来访问），应该在哪里修改配置允许跨域呢？谢谢！

**Comment by aaamoon** [comment]
@tomleung1996 其他机器能够通过http://服务器地址:3000 访问到服务器部署的客户端吗

**Comment by tomleung1996** [comment]
> @tomleung1996 其他机器能够通过[http://服务器地址:3000](http://%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%9C%B0%E5%9D%80:3000) 访问到服务器部署的客户端吗

可以的，其他机器可以通过浏览器使用NextChat。但如果是安装在其他机器的NextChat就不行

**Comment by aaamoon** [comment]
@tomleung1996 其他机器能够通过curl请求到服务器部署的copilot-gpt4-service
curl --location 'http://服务器地址:8080/v1/chat/completions' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer ghu_xx' \
--data '{
  "model": "gpt-4",
  "messages": [ {"role": "user", "content": "你好"}]
}'

**Comment by tomleung1996** [comment]
是有回复的，那看来这个问题是NextChat的问题？
