### ISSUE TITLE
Any ways to call it through its API?

### ISSUE THREAD

**Issue by Ezharjan** [aaamoon/copilot-gpt4-service#91]
When using it locally, are there any ways to call it through its API? Just like the example codes below:
```python
import openai
openai.api_key = "YOUR_API_KEY" 

prompt = "Hello, my name is John and I am a software engineer."
model = "text-davinci-003"
response = openai.Completion.create(engine=model, prompt=prompt, max_tokens=50)

generated_text = response.choices[0].text
print(generated_text)
```

Are there any way to purely gain the GPT's response through commandline rather than a web application like ChatNextWeb or Chatbox? 
If there is one, how to call it through Python code. 
**Would you mind providing a simple example on calling it through Python code like the example above.**

**Comment by aaamoon** [comment]
curl --location 'http://localhost:8080 \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer ghu_xx' \
--data '{
  "model": "gpt-4",
  "messages": [ {"role": "user", "content": "hello"}]
}'

**Comment by Ezharjan** [comment]
> ```
> curl --location 'http://localhost:8080' \
> --header 'Content-Type: application/json' \
> --header 'Authorization: Bearer ghu_xx' \
> --data '{
>   "model": "gpt-4",
>   "messages": [ {"role": "user", "content": "hello"}]
> }'
> ```

Thank you.
But after running this command, it says "Method Not Allowed".

Does it mean that I have to manually delete some of the following codes in `main.go`?
```go
func CORSMiddleware() gin.HandlerFunc {
	return func(c *gin.Context) {
		c.Writer.Header().Set("Access-Control-Allow-Origin", "*")
		c.Writer.Header().Set("Access-Control-Allow-Credentials", "true")
		c.Writer.Header().Set("Access-Control-Allow-Methods", "*")
		c.Writer.Header().Set("Access-Control-Allow-Headers", "*")

		if c.Request.Method == "OPTIONS" {
			c.AbortWithStatus(200)
			return
		}

		c.Next()
	}
}
```

**Comment by aaamoon** [comment]
I'm sorry, it was my mistake, it should be:
```
curl --location 'http://localhost:8080/v1/chat/completions' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer ghu_xx' \
--data '{
  "model": "gpt-4",
  "messages": [ {"role": "user", "content": "hello"}]
}'
```
