### ISSUE TITLE
Misleading ChatGPT version 3.5 vs 4 validation in English

### ISSUE THREAD

**Issue by alexander-gritsok** [aaamoon/copilot-gpt4-service#94]
READMI_EN.md contains incorrect answers to determine bot version: suggested answer can be produced by version 3.5

Current READMI_EN.md [content](READMI_EN.md):
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/65299267/330e5985-f0b1-481f-bdb3-0a09862bd7a9)

Actual ChatGPT 3.5 answer as of 09.01.2024:
![image](https://github.com/aaamoon/copilot-gpt4-service/assets/65299267/023308d6-e3d7-4a10-99a9-75c98ae0dfc3)

Here's the link for 3.5 questions: https://chat.openai.com/share/0b3cc5d0-fdaf-4662-8b8b-acfeb1da7219

**Comment by thangnqs** [comment]
So what exactly does it look like to right?

**Comment by aaamoon** [comment]
> So, what is the accurate explanation for this?那么，对此的准确解释是什么呢？

GPT-3.5 seems to be getting "smarter".

**Comment by lisakhan** [comment]
according the officials document, the model name is return in the chat completion API
https://platform.openai.com/docs/api-reference/chat/object

**Comment by felipecrs** [comment]
I don't know if it matters or not, but when I select `gpt-4` as model, it says its knowledge is up to 2021. When I change to `gpt-4-1106-preview`, it now says its knowledge is up to 2023.

**Comment by aaamoon** [comment]
@felipecrs Copilot only supports 4.0 and 3.5, and the effect when selecting other models is actually equivalent to 3.5, and its answer is that it is interfered with by the model of parameters.

**Comment by aaamoon** [comment]
@felipecrs Yes, exactly.
