### ISSUE TITLE
Support for tools (aka function calling)

### ISSUE THREAD

**Issue by dumbasPL** [aaamoon/copilot-gpt4-service#98]
I've tried:
```json
{
  "model": "gpt-4",
  "messages": [
    {
      "role": "user",
      "content": "What's the weather like in San Francisco, Tokyo, and Paris?"
    }
  ],
  "tools": [
    {
      "type": "function",
      "function": {
        "name": "get_current_weather",
        "description": "Get the current weather in a given location",
        "parameters": {
          "type": "object",
          "properties": {
            "location": {
                "type": "string",
                "description": "The city and state, e.g. San Francisco, CA"
            },
            "unit": {"type": "string", "enum": ["celsius", "fahrenheit"]}
          },
          "required": ["location"]
        }
      }
    }
  ],
  "tool_choice": "auto"
}
```
but got `Sorry, as an AI, I don't have real-time capabilities to provide current weather updates. Please check a reliable weather forecasting website or app for this information.` in response.

I don't see any mention of `tools` or `tool_choice` in the code of this project, have you tried it? Is it even possible with the copilot API or is it too restricted?

here are the openai docs for this feature: 
https://platform.openai.com/docs/guides/function-calling
https://platform.openai.com/docs/api-reference/chat/create#chat-create-tools

**Comment by luciamaj** [comment]
@dumbasPL have you found a possible solution looking at the extension code?

**Comment by dumbasPL** [comment]
> @dumbasPL have you found a possible solution looking at the extension code?

Unfortunately no, I've tried sending this directly to the GitHub copilot endpoint (because as I expected this project ignores unknown properties) but it still didn't work so I don't think it's possible. I didn't find anything interesting in the extension either.
