### ISSUE TITLE
能够加上https吗？

### ISSUE THREAD

**Issue by CarberryChai** [aaamoon/copilot-gpt4-service#99]
### Description

本地部署用，像OenCat自定义域名只能https，希望可以加上这个功能😊

### Why

RT

### Alternatives

RT

**Comment by lqxhub** [comment]
这个简单  我有空实现一下

**Comment by dw763j** [comment]
用caddy部署一下就好了吧，服务还是精简来的好，不要增加过多的东西。

**Comment by 5700pgf** [comment]
我觉得在README里写一下反代的配置就行了，我想用NGINX反代，但不知道配置应该怎么写，是不是按一般的配置来就行了？
有会的朋友给个配置呗，感谢！

**Comment by tisfeng** [comment]
nginx 反代可以，但证书可能要自己用 acme 去搞，略微点麻烦。

这种活还是 caddy 最适合，反代 + HTTPS 一把梭，全自动，省心省力。

等会我简单写个文档吧。

**Comment by clayclaw** [comment]
> 我觉得在README里写一下反代的配置就行了，我想用NGINX反代，但不知道配置应该怎么写，是不是按一般的配置来就行了？ 有会的朋友给个配置呗，感谢！

我是先用acme.sh去生成SSL certificate 因為我不能用443端口
跟一般的配置分別應該不大 這是我目前在用的

```
server {
    listen 4443 ssl http2;
    server_name <domain>;

    sendfile off;

    ssl_certificate /etc/letsencrypt/live/<domain>/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/<domain>/privkey.pem;
    ssl_session_cache shared:SSL:10m;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384";
    ssl_prefer_server_ciphers on;

    # See https://hstspreload.org/ before uncommenting the line below.
    # add_header Strict-Transport-Security "max-age=15768000; preload;";
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Robots-Tag none;
    add_header Content-Security-Policy "frame-ancestors 'self'";
    add_header X-Frame-Options DENY;
    add_header Referrer-Policy same-origin;

    location ~ /\.ht {
        deny all;
    }

    location / {
        proxy_pass <proxy_url>;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
```

**Comment by tisfeng** [comment]
我加了一个使用 Caddy 支持 HTTPS 的文档 https://github.com/aaamoon/copilot-gpt4-service/pull/185 

## 支持 HTTPS

<details> <summary> 使用 Caddy 支持 HTTPS </summary>

<p>

[Caddy](https://caddyserver.com/docs/) 可以很方便地为端口服务提供 HTTPS 支持，自动管理证书，省心省力。

以下是一个 Debian/Ubuntu 系统上使用 Caddy 的示例，其他系统请参考 [Caddy 官方文档](https://caddyserver.com/docs/)。

### 安装 Caddy

```bash
sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https curl
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
sudo apt update
sudo apt install caddy
```

### 配置 Caddy

```bash
sudo vi /etc/caddy/Caddyfile
```

假如你准备使用的域名为 `your.domain.com`，请先进行 DNS 解析，将域名解析到服务器 IP 地址，然后在 Caddyfile 中添加以下内容：

```bash
your.domain.com {
    reverse_proxy localhost:8080
}
```

### 启动 Caddy

请先确保 443 端口没有被其他程序占用，如 Nginx、Xray 等，然后执行以下命令启动 Caddy：

```bash
# 启动 Caddy
sudo systemctl start caddy

# 设置 Caddy 开机自启
sudo systemctl enable caddy

# 查看 Caddy 运行状态
sudo systemctl status caddy
```

如果命令执行成功，此时就可以通过 `https://your.domain.com` 访问 copilot-gpt4-service 服务了。

</p>

</details>

**Comment by 5700pgf** [comment]
> > 我觉得在README里写一下反代的配置就行了，我想用NGINX反代，但不知道配置应该怎么写，是不是按一般的配置来就行了？ 有会的朋友给个配置呗，感谢！
> 
> 我是先用acme.sh去生成SSL certificate 因為我不能用443端口 跟一般的配置分別應該不大 這是我目前在用的
> 
> ```
> server {
>     listen 4443 ssl http2;
>     server_name <domain>;
> 
>     sendfile off;
> 
>     ssl_certificate /etc/letsencrypt/live/<domain>/fullchain.pem;
>     ssl_certificate_key /etc/letsencrypt/live/<domain>/privkey.pem;
>     ssl_session_cache shared:SSL:10m;
>     ssl_protocols TLSv1.2 TLSv1.3;
>     ssl_ciphers "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384";
>     ssl_prefer_server_ciphers on;
> 
>     # See https://hstspreload.org/ before uncommenting the line below.
>     # add_header Strict-Transport-Security "max-age=15768000; preload;";
>     add_header X-Content-Type-Options nosniff;
>     add_header X-XSS-Protection "1; mode=block";
>     add_header X-Robots-Tag none;
>     add_header Content-Security-Policy "frame-ancestors 'self'";
>     add_header X-Frame-Options DENY;
>     add_header Referrer-Policy same-origin;
> 
>     location ~ /\.ht {
>         deny all;
>     }
> 
>     location / {
>         proxy_pass <proxy_url>;
>         proxy_http_version 1.1;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection 'upgrade';
>         proxy_set_header Host $host;
>         proxy_cache_bypass $http_upgrade;
>     }
> }
> ```

十分感谢！
